opengovsg/postmangovsg

- worker/src/core/loaders/message-worker/email.class.ts
- worker/src/core/loaders/message-worker/sms.class.ts
- worker/src/core/loaders/message-worker/util/assignment.ts
- worker/src/core/resources/sql/get-next-job.sql
- worker/src/core/resources/sql/resume-worker.sql
- worker/src/core/resources/sql/retry-jobs.sql
- worker/src/core/resources/sql/stop-jobs.sql
- worker/src/email/resources/sql/enqueue-messages-email.sql
- worker/src/email/resources/sql/get-messages-to-send-email.sql
- worker/src/email/resources/sql/log-job-email.sql
- worker/src/email/resources/sql/log-next-job-email.sql
- worker/src/email/resources/sql/retry-jobs-email.sql
- worker/src/sms/resources/sql/enqueue-messages-sms.sql
- worker/src/sms/resources/sql/get-messages-to-send-sms.sql
- worker/src/sms/resources/sql/log-job-sms.sql
- worker/src/sms/resources/sql/log-next-job-sms.sql
- worker/src/sms/resources/sql/retry-jobs-sms.sql
Closes #255
Although sequelize helps to set the `updated_at`, if we decide to not use sequelize in the future the columns will not be set at all.
> chore: set updated_at in sql scripts

- backend/src/email/routes/email-campaign.routes.ts
- frontend/src/components/dashboard/create/email/EmailTemplate.tsx
A user could enter new lines or spaces in the reply-to input box, which would cause a valid email to be rejected
Trim emails on backend, and do not accept new lines on frontend
> fix: new line in reply-to email

- amplify.yml
`style-src-elem` CSP directive not support on firefox and safari, blocking google fonts from loading.
Use `style-src`
> fix: google fonts blocked by csp headers on certain browsers

- frontend/src/contexts/auth.context.tsx
When a user's cookie has expired, making any requests that require authorization will display a stuck spinner. 
Intercept requests so that any requests that return 401 will redirect the user back to the public page.
> fix: redirect if any axios requests return unauthorized

- frontend/src/components/common/text-area/TextArea.module.scss
- frontend/src/components/common/text-area/TextArea.tsx
TextArea component with singleRow flag shows ugly scrollbar when user presses enter or text wraps.
Allow TextArea to resize when text wraps but prevent line breaks and `Enter` keypress.
> fix: singlerow textarea scrolls with multiple lines

- backend/src/core/models/user.ts
- frontend/src/components/dashboard/settings/api-key/ApiKey.tsx
Manually whitelisted users cannot create api key.
Error uncaught on server side and client side.
Remove BeforeUpdate hook and handle errors.
> fix: remove BeforeUpdate hook for user model, uncaught error for api gen

- backend/src/core/models/campaign.ts
Foreign key missing for campaignId in statistics table 
Add to campaign model file.
Manually add foreign key to staging and prod db
> fix: add missing foreign key for statistics

- backend/src/core/services/template-client.class.ts
- frontend/src/components/common/error-block/ErrorBlock.module.scss
Closes #273.
This is currently covered in test suite, just that error message isn't informative.
**BEFORE**:
**AFTER**:
> chore: Informative error for unclosed string

- backend/src/core/config.ts
- backend/src/core/loaders/cloudwatch.loader.ts
- backend/src/core/services/credential.service.ts
- backend/src/core/services/s3-client.class.ts
- backend/src/core/services/template.service.ts
- backend/src/core/utils/aws-endpoint.ts
To allow dev work to be self-contained, we need to remove the hard
dependency on hosted services like AWS at runtime. The first step to
this requires us to accept a parameter - an explicit RESTful endpoint -
that will be injected into Postman's AWS JavaScript clients, overriding
`AWS_REGION` in the process.
Doing so will allow developers to get Postman to connect to a specified
mock AWS service when running on their own machines, and would also
help with more invasive testing. This would also allow for external devs
to contribute, since they no longer need to have an AWS account to work
on Postman.
Note that this does not allow overrides for workers, as frameworks that
mock AWS services (eg localstack) do not have a freely available ECS API
Prep work for #284
- Add a new parameter in …
> refactor(backend): allow aws endpoint override

- worker/src/email/resources/sql/log-job-email.sql
- worker/src/sms/resources/sql/log-job-sms.sql
Closes #312
Pick the non null value to update to. 
> The COALESCE function accepts an unlimited number of arguments. It returns the first argument that is not null. If all arguments are null, the COALESCE function will return null.
> fix: do not override message logs (received_at and error_code)

- .travis.yml
Closes #311 
Use $TRAVIS_BUILD_DIR instead of a relative directory path.
Here's the successful build: https://travis-ci.com/github/opengovsg/postmangovsg/jobs/340351162
> fix: deploy authorizer on travis

- worker/src/core/resources/sql/resume-worker.sql
- worker/src/email/resources/sql/log-next-job-email.sql
- worker/src/sms/resources/sql/log-next-job-sms.sql
Closes #254 
For the explanation of the problem, refer to the issue above.
For job_status=SENT and job_status=STOPPED,  
- When all the ops messages that have sent_at also have delivered_at set, the job will be logged.
- Otherwise, if a worker had died, then some inflight ops messages that have sent_at will not have delivered_at set yet. After 20 seconds, the logger will assume that this job is stuck, and log it back to the messages table. 
For job_status = ENQUEUED or job_status=SENDING,
- if a worker dies, the job will not be logged. The good news is that when a respawned worker resumes the job, it will just start sending from the ops table. 
- If one of the workers for this campaign dies,
- Since the live workers are still updating the ops, the job will not be logged.
- A respawned …
> fix: log orphan ops records if they havent been updated after 20s

- backend/.ebextensions/00-elb-timeout.config
- backend/.ebextensions/10-nginx-timeout.config
- backend/src/core/config.ts
- backend/src/core/utils/aws-endpoint.ts
- backend/src/email/middlewares/email-template.middleware.ts
- backend/src/sms/middlewares/sms-template.middleware.ts
- frontend/src/config.ts
- frontend/src/services/upload.service.ts
On hitting the `upload/complete` route, the handler takes quite a while to run, with the bulk of the time spent on the `addToMessageLogs` functions. For files that are large, this actually takes a significant amount of time, the connection to our API server is kept open, and our app (at various points - Axios instance on frontend [1], Express API [2], Cloudflare, ELB [3], Nginx within beakstalk [4]) times out before a response is obtained.
1. https://github.com/axios/axios#config-order-of-precedence
2. https://github.com/expressjs/express/issues/3330#issuecomment-307009713
3. https://jaxenter.com/troubleshooting-aws-elastic-beanstalk-134700.html
4. https://stackoverflow.com/a/49759065
This is a stop gap fix. 
Since we have zero control [5] over cloudflare's timeout of 100s, we adjust all …
> Fix: Upload timeout

- backend/src/core/services/campaign.service.ts
- backend/src/email/middlewares/email-template.middleware.ts
- backend/src/email/services/email-template.service.ts
- backend/src/sms/middlewares/sms-template.middleware.ts
- backend/src/sms/services/sms-template.service.ts
Closes #268
- Updates s3 meta data only when csv file is valid, ie after parsing and test hydrate.
- Wraps updating of `campaign` and `message_logs` tables in a transaction.
- Move updating of campaign out of `addMessageLogs` function.
> chore: Prevent invalid files from updating s3 meta data

- backend/src/core/middlewares/auth.middleware.ts
- backend/src/core/utils/morgan.ts
We are not tracking whether api-keys are being used.
Append `-api` to the userId if the API key is being used to authenticate against the APIs instead of a session created via otp login.
> chore: log if api key is used

- backend/src/core/services/s3-client.class.ts
The following error was crashing our server. To reproduce consistently, upload a file to the presigned url, then delete the file from the s3 bucket, then call /upload/complete 
```
NoSuchKey: The specified key does not exist.
at Request.extractError (/usr/home/postmangovsg/node_modules/aws-sdk/lib/services/s3.js:835:35)
at Request.callListeners (/usr/home/postmangovsg/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
at Request.emit (/usr/home/postmangovsg/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
at Request.emit (/usr/home/postmangovsg/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/usr/home/postmangovsg/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/usr/home/postmangovsg/node_modules/aws-sdk/lib/state_machine.js:14:12) …
```
> fix: catch s3 error

- backend/__tests__/s3.service.test.ts
- backend/src/core/errors/s3.errors.ts
- backend/src/core/errors/template.errors.ts
- backend/src/core/services/s3-client.class.ts
- backend/src/email/middlewares/email-template.middleware.ts
- backend/src/sms/middlewares/sms-template.middleware.ts
The error occurs when a user has double quote that are not being used as `quotes`. 
In a CSV file, double quotes are used as `quotes`.
For example, `hi,my name is` will be separated into two fields. If we want it to be in one field, we have to use the double quotes: `"hi,my name is". 
However, when a unquoted field has double quotes, it results in an error because the parser doesn't know how to handle it.
Error: `404246"N` 
No error: `"404246"N"`
Closes #274.
Initially, what I wanted to do was to silence the double quote, meaning `"hello, Tom"` will end up being `"hello, Tom"` instead of `hello, Tom`.
However, this can be confusing to users and it probably creates alot of edge cases that we have to handle.
Instead, what we will throw a 400 and display a meaningful error message.
Im …
> chore: throws 400 when double quote is misused in csv

- worker/src/email/resources/sql/enqueue-messages-email.sql
- worker/src/email/resources/sql/update-stats-email.sql
- worker/src/sms/resources/sql/enqueue-messages-sms.sql
- worker/src/sms/resources/sql/update-stats-sms.sql
The `error_code` column is not overwritten on successful retry, due to coalescing of error_code from ops and message table. This means that successfully retried messages adds to the errored count as well.
- Set `error_code`, `delivered_at` and `sent_at` on enqueue
- Errored count should not include message with `message_id`
> fix: messages with message_id and error_code double counted

- backend/.ebextensions/10-nginx-timeout.config
We were unable to deploy reliably to release.
```[Instance: i-06a69d396f01f0a76] Command failed on instance. Return code: 7 Output: container_command 01_restart_nginx in .ebextensions/10-nginx-timeout.config failed. For more detail, check /var/log/eb-activity.log using console or EB CLI.```
The nginx-timeout config was introduced in 1.4.1 
According to https://stackoverflow.com/questions/54992337/aws-elastic-beanstalk-nginx-reload-failed , we don't need to reload nginx.
A possible explanation is that because the `/etc/nginx/conf.d/timeout.conf` file is included as part of the default `nginx.conf`, Elastic Beanstalk would automatically start nginx with the timeout configuration when it is first deployed.
Timeout still occurs at 100 seconds so I presume nginx is somehow configured with the …
> chore: remove nginx reload command

- backend/src/sms/middlewares/sms.middleware.ts
- backend/src/sms/routes/sms-settings.routes.ts
- frontend/src/components/dashboard/settings/credentials/Credentials.module.scss
- frontend/src/components/dashboard/settings/credentials/Credentials.tsx
- frontend/src/components/dashboard/settings/verify-credential-modal/VerifyCredentialModal.module.scss
- frontend/src/components/dashboard/settings/verify-credential-modal/VerifyCredentialModal.tsx
- frontend/src/components/dashboard/settings/verify-credential-modal/index.ts
- frontend/src/services/sms.service.ts
Users were not able to verify their credentials after they have added it in on the Settings page. 
Closes #221 
**Features**:
- Implemented an endpoint (`/settings/sms/credentials/verify`) to allow for verification of user sms credentials.
- Implemented a modal to allow user to trigger a verification message on the Settings page.
**BEFORE**:
**AFTER**:
**Successful Verification Test**
1. Ensure there is an existing set of credentials on the Settings page
2. Verify the credentials by entering phone number
3. Modal should show a success message + sms 
**Failed Verification Test**
1. Ensure there is an existing set of credentials on the Settings page
2. Modify Twilio credentials in .env file to be invalid
3. Verify the credentials by entering phone number
4. Modal should show a error message …
> feat: Allow user to verify their credentials after creation

- backend/src/core/middlewares/campaign.middleware.ts
- backend/src/core/routes/campaign.routes.ts
- backend/src/core/services/campaign.service.ts
- frontend/src/components/common/pagination/Pagination.tsx
- frontend/src/components/dashboard/campaigns/Campaigns.tsx
- frontend/src/services/campaign.service.ts
Offset and limit were not used for pagination on the frontend. 
Closes #317 
- Make use of offset and limit on the frontend API calls
- Return a `total_count` on the response for pagination component. 
- Set `loading` to true on page change to give user a visual indicator that the page is being fetched. 
Tests with 1000 campaigns in database.
**BEFORE**:
**AFTER**:
**Regression tests:**
- Make sure that empty placeholder is still shown when there are no campaigns.
- Ensure that title still shows the correct total campaign count. 
**Functional tests:**
- Navigate between pages.
- Observe the following through Chrome dev tools:
- `offset` and `limit` are being used.
- Only the campaigns in the current page are loaded.
- Throttle network to "Slow 3G" and observe spinner …
> feat: Use offset and limit for campaign pagination

- worker/src/email/resources/sql/log-job-email.sql
- worker/src/email/resources/sql/update-stats-email.sql
- worker/src/sms/resources/sql/log-job-sms.sql
- worker/src/sms/resources/sql/update-stats-sms.sql
PG function changes:
log-job:
- log statuses from ops table to message
- also fix coalescing order
update-stats:
- counts are now based on statuses
- new invalid count
> feat: log statuses, count stats based on statuses

- backend/src/core/interfaces/campaign.interface.ts
- backend/src/core/services/stats.service.ts
- frontend/src/classes/Campaign.ts
- frontend/src/components/common/progress-details/ProgressDetails.module.scss
- frontend/src/components/common/progress-details/ProgressDetails.tsx
- frontend/src/services/campaign.service.ts
- Get unsent, sent, error and invalid count from ops table based on status column
- Display invalid recipient count on frontend
> Display invalid stats

- .travis.yml
- backend/src/core/interfaces/mail.interface.ts
- backend/src/core/services/mail-client.class.ts
- serverless/log-email-sns/src/index.ts
- serverless/log-email-sns/src/interfaces.ts
- worker/src/core/loaders/message-worker/email.class.ts
- worker/src/email/interfaces/index.ts
- worker/src/email/services/mail-client.class.ts
The previous implementation updated the email_messages table using the message_id returned by an email callback event. Unfortunately, if the ops table has yet to be logged back to email_messages, no record will be updated since email_messages does not have the message_id set.
This PR adds an header containing the id of the record in email_messages, when sending emails. The callback lambda uses this id to update email_messages, instead of message_id. 
The SES event then returns it as a header.
Sample event
```
{
"Records": [
{
"EventSource": "aws:sns",
"EventVersion": "1.0",
"EventSubscriptionArn": "arn:aws:sns:us-east-1:306667300165:postmangovsg-staging-ses:bb96353e-13fa-4ddb-91e7-46f0c7bbdb51",
"Sns": {
"Type": "Notification",
"MessageId": "5151f7fb-e0ec-5ff2-ba78-a0a4f47d7933", …
```
> Add X-Postman-ID for email callback to update the correct record

- backend/src/telegram/models/telegram-message.ts
- backend/src/telegram/models/telegram-op.ts
- backend/src/telegram/models/telegram-subscriber.ts
The current Telegram schema has a couple of missing constraints and inconsistent types. 
- `telegram_messages` and `telegram_ops`
- Make `campaign_id` and `recipient` not null
- Add `status` column
- `telegram_ops`
- Change `recipient` datatype to `number / BIGINT` – this matches the datatype of `telegram_id` in `bot_subscribers` and `telegram_subscribers`
- `telegram_subscribers`
- Set `phone_number` to primary key
- Set unique constraint on `telegram_id` – there should never be more than one mapping for any phone number or Telegram ID
> chore: Improve Telegram schema

- package.json
The root package.json does not list its licensing, even though we (GovTech) intend for the codebase to be available under MIT.
Add the license entry in `package.json`
> chore: add licensing

- backend/src/core/services/s3-client.class.ts
- backend/src/core/services/template-client.class.ts
- backend/src/core/services/template.service.ts
- backend/src/email/middlewares/email-template.middleware.ts
- backend/src/email/services/email-template.service.ts
- backend/src/sms/middlewares/sms-template.middleware.ts
- backend/src/sms/services/sms-template.service.ts
`testHydration` was doing too many things. Functions should ideally have a single responsibility.
`testHydration` used to do a couple of things: 
- Download the csv file from S3
- Parse the csv file
- Checks that the csv headers have all the template keys
- Transform the file content into records
- Hydrates the first record using `template` function
All these functionalities are now achieved by three functions: 
- `s3Client.getCsvFile`: Downloads and parses the CSV file 
- `getRecordsFromCsv`: Checks csv headers  & transform file content into records
- `testHydration`: Hydrates the first record
> [Template Module] refactor:  test hydration

- backend/src/core/config.ts
- backend/src/core/loaders/express.loader.ts
We had separate DSNs for each environment. 
Create 1 sentry project with multiple environments
Remember to change `SENTRY_DSN` to `https://fedcd4e7d5d8480b852423c04ee2aab6@o399364.ingest.sentry.io/5272357` on prod! It's set for staging.
> chore: use environments in sentry backend

- .travis.yml
- backend/Dockerfile
- backend/Dockerrun.aws.json
- worker/Dockerfile
- worker/deploy.sh
Deployment to backend/worker/frontend will have to change to accommodate the local `postman-templating` module.
- Build docker image on travis
- Push build to ECR (Elastic Container Registry)
- Deploy zip file with `Dockerrun.aws.json` in it to EB (Elastic Beanstalk)
- EB will pull image from ECR
- Changes to the deploy script and builds on the root folder instead of the worker folder.
> [Template Module] chore: Deployment changes to backend & worker

- frontend/src/components/common/confirm-modal/ConfirmModal.tsx
- frontend/src/components/common/primary-button/PrimaryButton.tsx
- frontend/src/components/common/progress-details/ProgressDetails.tsx
- frontend/src/components/common/text-input-with-button/TextInputWithButton.tsx
- frontend/src/components/dashboard/create/email/EmailValidationInput.tsx
- frontend/src/components/dashboard/create/sms/SMSValidationInput.tsx
- frontend/src/components/dashboard/settings/api-key/ApiKey.tsx
- frontend/src/components/login/login-input/LoginInput.tsx
Some of our inputs and buttons are not disabled when an async function call is fired, allowing unwanted duplicate calls to be made (e.g. by double-clicking a button). 
Closes #407.
This PR introduces a local state variable `asyncLoading` in `PrimaryButton` and `TextInputWithButton` that signifies if an async function execution is ongoing. The input and button are disabled based on `asyncLoading` to prevent unwanted user interaction while waiting for a response. 
The default behavior is to re-enable the input/button after the async function execution completes, but there are quite a few cases where the component is unmounted right after the response is received – for example when navigating away after clicking a button. Trying to re-enable an unmounted component would throw an exception. …
> feat: Automatic input and button disabling when executing async functions

- frontend/src/styles/_mixins.scss
The italics text in email template previews are larger than expected.
InfoBlock styling has a css style targeting `i` boxicon elements. The target element was defined as `i` which includes all elements with the `<i>` html tag - boxicon elements and italic text. 
Closes #444
Modify the css style to target only `i` elements with the global style `.bx` which identifies it to be a boxicon. This removes the unwanted styling on the `<i>` tag for italic text.
**BEFORE**:
**AFTER**:
> Fix exceptionally large italics text in InfoBlock component

- backend/src/telegram/middlewares/telegram-stats.middleware.ts
- backend/src/telegram/routes/telegram-campaign.routes.ts
- backend/src/telegram/services/telegram-stats.service.ts
Export of invalid recipients is not supported on Telegram. 
- Add `/campaign/{campaignId}/telegram/export` endpoint
- Create a new telegram campaign with a number with no subscription
- Send the campaign
- Wait for 5 minutes and download the exported list of invalid recipients either from the main campaign page or from the campaign details page.
> feat: Add invalid recipients export for Telegram

- .travis.yml
Update travis.yml to include deployment for Telegram workers and change function name for Telegram callback lambda. Also made the following minor changes on AWS:
1. Add missing `DB_READ_REPLICA_URI` for Elastic Beanstalk config
2. Update `STAGING_TELEGRAM_HANDLER_DB_URI` on Travis to point to new `telegram` database on staging RDS instance
3. Added `halted` column to `campaigns` table
Tested deployment on Telegram AWS environment. 
- Change `TELEGRAM_BRANCH` back to `telegram` on Travis after merge.
> chore: Add deploy config for Telegram branch workers

- backend/src/core/config.ts
- frontend/src/components/common/preview-block/PreviewBlock.module.scss
- frontend/src/components/dashboard/create/telegram/TelegramRecipients.tsx
Normal links were being stripped by the previous xss options for Telegram. 
Closes #465 
**Bug Fixes**:
- Use `onTagAttr` instead of `safeAttrValue`. I wrongly assumed previously that `safeAttrValue` default behaviour will just use the default `safeAttrValue` function when nothing is returned. 
- Reference: [docs](https://github.com/leizongmin/js-xss/tree/v1.0.6#customize-the-handler-function-for-attributes-of-matched-tags) for `onTagAttr`
- Add CSS to show styles for `pre` and `code` blocks. 
- Replace `\n` with `<br />` in recipients page preview to show line breaks in preview. 
Create a Telegram campaign and send a test message with this template to try out all the supported tags:
```
<b>bold</b>, bold
<i>italic</i>, italic
<u>underline</u>, underline
<s>strikethrough</s>, …
```
> Fix normal links in Telegram templates

- frontend/src/components/common/side-nav/SideNav.module.scss
- frontend/src/components/dashboard/settings/credentials/Credentials.module.scss
- frontend/src/components/dashboard/settings/credentials/Credentials.tsx
SideNav was not filling the entire height of the Settings page.
Closes #463 
**Bug Fixes**:
- Added `min-height` to SideNav component's style (similar to ProgressPane) 
- Updated Credentials table style to more closely match design on Zeplin
**BEFORE**:
**AFTER**:
> fix: Minimum height for SideNav

- README.md
- backend/.env-example
- backend/src/core/config.ts
- backend/src/core/utils/aws-endpoint.ts
- localstack/bucket-cors.json
- localstack/init-localstack.sh
Fixes #284 - currently, anybody who wishes to work on the postman
codebase needs to have an AWS account with an S3 bucket to exercise
the uploading of recipient lists. This can be tedious to set up, and 
places avoidable burden on the developer, especially if only contributing
casually.
To facilitate local development, make code changes, add support
scripts and provide documentation to allow the running of postman
against the S3 module in localstack. This would allow developers
to exercise the uploading of recipient lists over S3, without the
need for an AWS account.
[backend]
- `core/config` - change `aws.awsEndpoint` to have any format, to
allow a null default or user-specified string
- `core/utils/aws-endpoint` - if `aws.awsEndpoint` specified, provide:
- a boolean flag that forces …
> feat(localstack): handle S3 calls on localstack

- worker/src/core/config.ts
- worker/src/core/loaders/message-worker/telegram.class.ts
- worker/src/core/services/template-client.class.ts
- worker/src/telegram/services/telegram-client.class.ts
This PR: 
- Sets Telegram `parse_mode` to HTML
- Adds missing XSS options for Telegram workers
- Strip extra backslash from newline character
Closes #466 #464.
> fix: Worker templating

- serverless/telegram-handler/src/bot/PostmanTelegramError.ts
- serverless/telegram-handler/src/bot/handlers/contact.ts
- serverless/telegram-handler/src/bot/index.ts
- serverless/telegram-handler/src/index.ts
Error messaging was unclear. 
- Simplify response when handling contact updates
- Introduce a new `PostmanTelegramError` class to differentiate between our own errors and those thrown by libraries. This allows us to: 
- Provide more descriptive error messages for our own errors
- Hide details from uncaught exceptions, responding with a generic "please try again" message
> chore: Improve error messaging

- serverless/telegram-handler/src/bot/handlers/contact.ts
Some Telegram clients send contact objects with `+` already prefixed to the phone number.
Detect and avoid double-prefixing.
> fix: Avoid double + prefix

- backend/src/core/config.ts
Adds `telegram` NODE_ENV option for convict for backend, so we can switch it on for sentry
> chore: add telegram as node_env option for sentry

- .prettierignore
- amplify.yml
- package.json
Amplify could not render our app when our amplify.yml file's new lines were appended with slashes.
Do not lint the amplify.yml file
Maybe there's a better rule for this?
> chore: remove slashes in amplify

- README.md
- backend/src/core/loaders/cloudwatch.loader.ts
- backend/src/core/services/credential.service.ts
- frontend/.env-example
- localstack/init-localstack.sh
As part of efforts to better replicate the dev experience as close to deployed
environments as possible, continue work to support localstack
- if `AWS_ENDPOINT` is specified, assume localstack present, and allow:
- managing secrets from SecretManager even if not `IS_PROD`
- configuring `machineId` to be dev machine hostname for CloudWatch
- update `localstack/init-localstack.sh` to add log stream, name taken from
hostname
- update README with instructions to use cw to tail CloudWatch logs
- update frontend/.env-example with a properly formatted `SENTRY_DSN`
Part of work for #284 
Run on local dev environment, localstack cloudwatch verified working as follows:
```bash
$ cw tail -r ap-northeast-1 -u $AWS_ENDPOINT -f $AWS_LOG_GROUP_NAME:`node --eval='console.log(require("os").hostname())'` …
```
> feat(localstack): localstack CloudWatch, secrets

- backend/src/core/interfaces/campaign.interface.ts
- backend/src/core/models/campaign.ts
- backend/src/core/services/job.service.ts
- frontend/src/classes/Campaign.ts
- frontend/src/components/common/progress-details/ProgressDetails.tsx
- serverless/log-email-sns/src/query.ts
We could not reliably enable the resumption of a campaign which had been halted because it probably would halt again on the next retry. 
A campaign can only be halted if `halted` is `false`.
To unhalt, that is, forcefully override the halting mechanism, set `halted` to `null`. 
- Delete the bounce email from blacklist 
- Insert some records (check the min number and min percentage required by the log-email-callback-staging lambda)
```sql
DELETE FROM email_blacklist WHERE recipient='bounce@simulator.amazonses.com';
-- Example for campaign 178
INSERT INTO email_messages ("campaign_id", "recipient", "params", "created_at", "updated_at")
SELECT t.* FROM  generate_series(1,10) num_recipient
CROSS JOIN LATERAL ( 
SELECT 178 as "campaign_id", 'success@simulator.amazonses.com' as "recipient", …
```
> chore: override halting

- serverless/log-email-sns/src/query.ts
Soft bounces should not halt the campaign as they do not contribute to the bounce rate computed by SES.
Halt only when error_code=Hard bounce.
> chore: halt only on hard bounce

- backend/.eslintrc.js
- backend/src/email/middlewares/email.middleware.ts
- frontend/.eslintrc.js
- worker/.eslintrc.js
Our previous ESLint config had a blanket disable for the `camelcase` rule, allowing non-camelcase variables in places we didn't intend. 
This PR makes the config stricter, only allowing `camelcase` exceptions for object properties and destructuring (input/output).
> chore: Stricter camelcase config

- backend/src/core/services/stats.service.ts
- frontend/src/classes/Campaign.ts
- frontend/src/components/common/export-recipients/ExportRecipients.tsx
- frontend/src/services/campaign.service.ts
Closes #506 
- Include error code in the backend `/export` endpoints
- Include `errorCode` in `CampaignInvalidRecipient`
1. Create campaign with invalid recipients
2. Send campaign
3. Export CSV when available and look for `errorCode` column
> feat: Include error code in exported CSV

- backend/src/core/middlewares/protected.middleware.ts
- backend/src/core/routes/index.ts
- backend/src/core/routes/protected.routes.ts
- backend/src/core/routes/protectedCampaign.routes.ts
- backend/src/core/services/protected.service.ts
The password entered by the user on to decrypt the protected message needs to be verified by the server before sending over the encrypted payload. 
Closes #368 
**Features**:
- `verifyPasswordHash` endpoint verifies the password hash and returns the encrypted payload on success, or returns `401 Unauthorized` on mismatch
- compare the input password hash with the password hash stored in the `protected_messages` table
- use `crypto.timingSafeEqual` function to compare the hashes to prevent timing attacks
> Verify password endpoint for protected campaigns

- backend/src/core/routes/settings.routes.ts
- frontend/src/components/common/primary-button/PrimaryButton.tsx
- frontend/src/components/dashboard/create/Create.module.scss
- frontend/src/components/dashboard/create/create-modal/CreateModal.tsx
- frontend/src/components/dashboard/create/telegram/TelegramCredentialsInput.tsx
- frontend/src/components/dashboard/settings/Settings.tsx
- frontend/src/components/dashboard/settings/add-credential-modal/AddCredentialModal.module.scss
- frontend/src/components/dashboard/settings/add-credential-modal/AddCredentialModal.tsx
- frontend/src/components/dashboard/settings/credentials/Credentials.tsx
- frontend/src/styles/app.scss
Link in the create modal should directly link user to the add Telegram credential modal.
Closes #491 
**Features**:
- Link user to `AddCredentialModal` directly from `CreateModal`
- Load stored credentials within `AddCredentialModal` 
- Added `loadingPlaceholder` to `PrimaryButton` to allow display of custom content when loading (e.g. spinner)
- Add link to guide for Telegram bot token field in modal 
1. Open campaign creation modal 
2. Fill in a name for the campaign
3. Select Telegram as channel type
4. Click on the link "store and validate your credentials"
5. Fill in form with label and Telegram bot token and validate credential
6. Upon successful validation, user should be redirected back to the create campaign modal. The name for the campaign should be preserved …
> feat: Directly link user to add credential modal from create modal for Telegram

- frontend/src/components/dashboard/create/Create.tsx
- frontend/src/components/dashboard/create/email/EmailCreate.tsx
- frontend/src/components/dashboard/create/email/EmailTemplate.tsx
- frontend/src/components/dashboard/create/sms/SMSCreate.tsx
- frontend/src/components/dashboard/create/sms/SMSTemplate.tsx
- frontend/src/components/dashboard/create/telegram/TelegramCreate.tsx
- frontend/src/components/dashboard/create/telegram/TelegramCredentials.tsx
- frontend/src/components/dashboard/create/telegram/TelegramDetail.tsx
- frontend/src/components/dashboard/create/telegram/TelegramTemplate.tsx
Collection of minor tweaks in messaging to improve UX from Sarah's feedback/testing.
- Updates in `campaign` status was not propagated to the top level `Create` component. As such, a page refresh is required to fetch the updated `campaign` from the backend. This cause the button to show the wrong message at the final send step. 
1. Messaging for bot token insertion
2. Information on recipient column
3. Export instructions for Telegram statistics page
4. "Back to campaigns" button
> chore: Messaging tweaks to improve UX

- backend/src/core/middlewares/protected.middleware.ts
- backend/src/core/services/protected.service.ts
- backend/src/email/routes/email-campaign.routes.ts
- frontend/src/components/dashboard/create/email/EmailTemplate.tsx
Multiple `protectedlink` would throw an error:
Template A's subject was allowed to have keywords:
- Added checks for subject to ensure it has no keywords. (We could allow them to add `protectedlink`)
- Allow multiple mentions of `protectedlink` in `checkTemplateBody`
**AFTER**:
Multiple `protectedlink`:
Keywords in subject:
> [Registered] chore: Template A checks

- .travis.yml
Made the following changes:
- Added additional section to deploy `telegram-handler-production`
- Add roles env var for Telegram handler
- Updated `telegram-test` to deploy on staging branch instead
The following env vars need to be set/update in travis:
> chore: Add travis deploy for prod Telegram handler

- amplify.yml
Frontend env var for backend url was not set back to `api-staging.postmang.gov.sg`.
Set env var to in `amplify.yml` back.
> fix: Set backend url back to staging

- backend/package-lock.json
- backend/package.json
- backend/src/core/config.ts
- backend/src/core/middlewares/protected.middleware.ts
- backend/src/core/services/protected.service.ts
- backend/src/email/services/email-template.service.ts
- backend/src/sms/services/sms-template.service.ts
- backend/src/telegram/services/telegram-template.service.ts
- frontend/src/services/validate-csv.service.ts
- modules/postman-templating/src/index.ts
- modules/postman-templating/src/template-client.ts
- modules/postman-templating/src/xss-options.ts
- modules/postman-templating/test/template-client.test.ts
- worker/package-lock.json
- worker/package.json
- worker/src/core/config.ts
- worker/src/core/loaders/message-worker/email.class.ts
- worker/src/core/loaders/message-worker/sms.class.ts
- worker/src/core/loaders/message-worker/telegram.class.ts
Closes #532, #516 
To use the xss options :
`import { TemplateClient, XssEmailOption } from 'postman-templating'`
`const client = new TemplateClient(XssEmailOption)`
Initially we installed `xss` on backend and worker to use the default `safeAttrValue` from `xss`, now that we moved the options into postman-templating we can uninstall `xss`.
> chore: add xss options into postman-templating module

- .travis.yml
- backend/src/telegram/services/telegram.service.ts
- serverless/telegram-handler/package-lock.json
- serverless/telegram-handler/package.json
- serverless/telegram-handler/src/bot/index.ts
- serverless/telegram-handler/src/config.ts
- serverless/telegram-handler/src/credentials.ts
- serverless/telegram-handler/src/index.ts
- serverless/telegram-handler/src/parser.ts
- serverless/telegram-handler/src/server.ts
We currently use bot ID as the path parameter for bot webhook URLs. Anyone who knows the bot ID (which is not meant to be a secret) can start sending updates to our handler. 
Although an attacker can't make use of this because we have additional checks, ideally our handler should only be handling updates from trusted sources (i.e. from Telegram only and not strangers). 
- Extend the path parameter to include the full bot token instead of just the bot ID. The bot token is a secret that is only known to the bot owner. 
- Verify that the incoming bot token is valid and not revoked with a call to Telegram's `getMe` endpoint. 
1. Save a new bot credential in the app
- Your bot's webhook URL should be set to `telegramOptions.webhookUrl` + the full bot token. Verify this via `GET …
> feat: Use full bot token instead of bot ID in Telegram webhook URLs

- serverless/telegram-handler/src/bot/handlers/start.ts
- serverless/telegram-handler/src/bot/handlers/updatenumber.ts
- serverless/telegram-handler/src/utils/generatePadding.ts
From the comment in `generatePadding`: 
```
* If a user has previously hidden/dismissed the custom keyboard, some Telegram clients (e.g. iOS)
* continue hiding the custom keyboard sent with subsequent messages if there are no changes
* detected in the button labels. A random-length whitespace string is padded to the button labels
* to force clients to always show the custom keyboard. This has no visible effect to users because
* Telegram trims whitespace before it reaches the user.
```
1. Run the handler locally
2. Send `/start` then hide the custom keyboard
3. Continue sending `/start` – Each time a response is received, the custom keyboard should be brought up again.
> feat: Force custom Telegram keyboards to be shown

- .travis.yml
- backend/src/core/config.ts
Closes #545 
- Remove Telegram Elastic Beanstalk and ECS deployments from `travis.yml`
- Remove `telegram` from `NODE_ENV` that was added previously for monitoring Telegram deployment
> chore: Telegram cleanup

- frontend/src/services/validate-csv.service.ts
Closes #565
Turns all the params into lowercase before looking for the missing params. 
Although this solution solves the problem, a better solution would be for `postman-templating` module to retain the original value of the params instead of converting them into lowercase. However, this probably requires alot more work and I'm not sure if it's worth it.
> chore: Convert params into lowercase when looking for missing keys

- modules/postman-templating/src/template-client.ts
- modules/postman-templating/test/template-client.test.ts
Closes #566 
Add underscore to the the regex that is validating the template keys.
**AFTER**:
> chore: support underscore for keywords in template

- backend/src/core/middlewares/protected.middleware.ts
- backend/src/core/routes/protected.routes.ts
- frontend/src/services/decrypt-mail.service.ts
401 logs users out of postman. Error message from 429 not showing due to CORS.
Returning 403 instead of 401. 
Unable to read status code 429 from cloudflare as cors header not sent with response. Generic error message 'Please try again later.' shown on all any network errors (includes rate limit or disconnected).
> Protected error msg fix

- backend/package-lock.json
- backend/package.json
- backend/src/core/errors/s3.errors.ts
- backend/src/core/services/s3-client.class.ts
- backend/src/email/middlewares/email-template.middleware.ts
- backend/src/sms/middlewares/sms-template.middleware.ts
- backend/src/telegram/middlewares/telegram-template.middleware.ts
Closes #379
Made use of `async-retry` to retry only when s3 fails to find the specified key. There are other errors that could be thrown from `parseCsv`, so I had to check the error code.
Alternatively, I can do the retry on the frontend by reading the error code given by the backend after calling `upload/complete`. If it is the error message related to this, I will retry using axios.
Not sure which approach is better tbh. 
New dependencies for backend.
- `async-retry` : For async retries operations
**New dev dependencies**:
- `@types/async-retry`
> chore: Retry getting s3 object in backend

- .travis.yml
Inconsistent naming of lambda
- Renamed lambda in travis
- Set up new lambda in staging vpc
- Redeployed API gateway to point to this lambda
> chore: update travis with renamed telegram handler lambda

- backend/src/sms/middlewares/sms-template.middleware.ts
- backend/src/sms/services/sms-template.service.ts
- backend/src/sms/services/sms.service.ts
- backend/src/sms/services/twilio-client.class.ts
- backend/src/telegram/services/telegram-template.service.ts
- worker/src/core/config.ts
- worker/src/sms/services/twilio-client.class.ts
Closes #546 
- Uses `PhoneNumberService` to normalise phone numbers before insertion into messages table (similar to Telegram)
- Remove appending of country code in `TwilioClient` for both `backend` and `worker`
1. Run unit tests added in previous PR to confirm the validation and normalisation logic
2. Create an SMS campaign with the following recipients:
```
recipient
91234567
14128018888
+8613910998888
6580123456
```
3. Check in `sms_messages` table that all the messages should be normalised  
4. Upload a recipient list with the following numbers. Each of them should raise an error.
```
recipient
612345678   (Invalid length)
8123456     (Invalid length)
11234567    (Number not starting with 6, 8 or 9) 
```
- Deploy workers after merge
- Removed `DEFAULT_COUNTRY_CODE` environment …
> feature: Normalise SMS phone numbers with libphonenumber-js

- worker/src/core/config.ts
- worker/src/core/loaders/message-worker/email.class.ts
- worker/src/core/loaders/message-worker/index.ts
- worker/src/core/loaders/message-worker/interface.ts
- worker/src/email/resources/sql/get-messages-to-send-email.sql
Closes #579
Initially I thought that appending unsubscribe url through the workers wasn't a very good idea because:
- User won't be able to see it in the test message (We don't use the workers to send the test message)
- Single responsibility; workers should focus on sending messages and not editing messages
However, after considering other ways to achieve this like adding it to every email template & storing the url as a param, I find that the other ways are significantly more complicated.
We could append a test url to the body for the test message if we wanted to.
**Features**:
- Calculate hash, create unsubscribe url and append it to the hydrated message body.
- Added an interface named `Message` to make `message-worker/index.ts` neater
> feat: Append unsubscribe url to email message body

- frontend/.eslintrc.js
- frontend/.gitignore
- frontend/.linguirc
- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.tsx
- frontend/src/components/login/login-input/LoginInput.tsx
- frontend/src/locales/README.md
- frontend/src/locales/en-custom/messages.po
- frontend/src/locales/en/messages.po
- frontend/src/locales/index.tsx
Someone who wants to deploy Postman will have to dive into particular parts of the code base to change the copywriting.
Closes #288 
Installed and configured [lingui](https://lingui.js.org/tutorials/react.html) to have `en` as the source language and `en-custom` as a "translated" language. User can change the copywriting by providing "translation" for `en-custom` language These copywriting will be displayed when the language is set to `en-custom` (default language is set to `en-custom` in this PR).
**Features**:
- User can change the copywriting offline via translation file without diving into the code.
- Developer can use command line to extract the text to be translated. This is provided by lingui.
**BEFORE**:
**AFTER**:
As a proof-of-concept, the translated copywriting is the original …
> Add package for interpolating the copywriting on frontend

- .travis.yml
- backend/src/telegram/services/telegram.service.ts
- serverless/telegram-handler/.env-example
- serverless/telegram-handler/src/bot/handlers/help.ts
- serverless/telegram-handler/src/bot/index.ts
- serverless/telegram-handler/src/config.ts
From the issue: 
> If users are confused while talking to the Telegram bot, there's no easy way for them to get help.
Closes #593.
Add a new `/help` command that:
- Shows a short summary of the commands available (similar to BotFather)
- Provides a way for recipients to contact us via a support form
Already tested on staging, to test locally: 
1. Make sure the new env vars are set, then run the handler locally
2. Send a `/help`, you should receive the message shown above
3. Storing your bot token via the frontend should also add a `/help` option to the suggestion list when you type `/`
- `TELEGRAM_BOT_CONTACT_US_URL`: Support form URL
- `TELEGRAM_BOT_GUIDE_URL`: Recipient guide URL
Also remember to update all current bots with the new command.
> feat: Telegram help command

- backend/src/core/middlewares/unsubscriber.middleware.ts
- backend/src/core/routes/unsubscriber.routes.ts
- backend/src/core/services/unsubscriber.service.ts
GET endpoint wasn't required. Should be removed to minimise API surface. 
- Removed `GET /unsubscribe` endpoint
- Changed `POST /unsubscribe` to `PUT /unsubscribe/:campaignId/:recipient`
- Used `PUT` instead as `POST` endpoints are typically not idempotent
- Moved `campaignId` and `recipient` to URL params to be in line with [RFC2616](https://tools.ietf.org/html/rfc2616#section-9.6) where the _"PUT method requests that the enclosed entity be stored under the supplied Request-URI"_
- Also conforming with [RFC2616](https://tools.ietf.org/html/rfc2616#section-9.6), if a new unsubscriber is added, the  endpoint should return `201 Created`. Otherwise a `200 OK` is returned if the unsubscriber already exists. 
- `h` and `v` are still passed in the request body JSON …
> refactor: Remove GET unsubscriber status endpoint

- amplify.yml
Images were broken. 
Allow images to be shown if they are hosted on go.
> chore: update csp headers to allow files from go

- frontend/src/components/dashboard/create/email/EmailTemplate.tsx
Remove `message A` from template instructions
> fix: wording for non-protected email template

- backend/src/core/services/unsubscriber.service.ts
- backend/src/email/services/email.service.ts
- frontend/src/components/unsubscribe/Unsubscribe.tsx
Test emails did not include the unsubscribe footer. Users might be interested to test out the unsub user flow without trigger an actual unsub. 
**Features**:
- Appended a test unsubscribe footer to test emails. Link direct to `/unsubscribe/test`. 
- Skip actual API call if the version is set to `test` on the frontend 
- Create an email campaign
- Send a test email to yourself
- Click on unsubscribe link in test email footer and go through unsubscribe flow
- `unsubscribers` table should remain unchanged
> feat: Add unsubscribe footer in test email

- backend/src/sms/services/sms-template.service.ts
- worker/package-lock.json
- worker/package.json
- worker/src/core/config.ts
- worker/src/core/loaders/message-worker/sms.class.ts
- worker/src/core/services/phone-number.service.ts
PR #573 did phone number normalisation and validation during the insertion into `sms_message` table (similar to Telegram). After moving validation of recipient to the worker, appending of +65 is no longer done as #573 removed the logic in the Twilio client. In addition, this might create an issue for campaigns that were created but not yet sent when merged into production.
This PR went with the approach for solving this by copying `PhoneNumberService` from the backend and using it as the validator and formatter for phone numbers in the worker. 
Alternative considered:
- Adopt same approach as Telegram and does normalisation in the backend. 
- This wasn't chosen as I wanted to maintain the pattern of validating in the worker when possible. Telegram is not able to do this as it requires …
> fix: Phone number normalisation in worker

- .travis.yml
- amplify.yml
- backend/src/core/config.ts
- backend/src/email/routes/email-campaign.routes.ts
Closes #541
Add deployment to separate environment for MOM
- Test that emails can be sent from mom.postman.gov.sg
- Check that the status of these email messages are updated
- Corresponding email messages with the same id in prod postman must not be updated with status
```
CREATE FUNCTION disallow_sms_telegram_campaigns()
RETURNS trigger AS
$func$
BEGIN
IF (NEW."type" = 'SMS' or NEW."type"='TELEGRAM') THEN
RAISE EXCEPTION 'SMS and TELEGRAM campaigns are not allowed in this environment';
END IF;
RETURN NEW;
END
$func$  LANGUAGE plpgsql;
CREATE TRIGGER disallow_type_before_insert_campaigns
BEFORE INSERT ON "campaigns"
FOR EACH ROW EXECUTE PROCEDURE disallow_sms_telegram_campaigns();
```
> feat: support separate environment for MOM

- backend/src/core/services/credential.service.ts
- backend/src/telegram/middlewares/telegram.middleware.ts
Storing a bot token repeatedly in staging/production causes the webhook URL to keep changing - difficult to debug. 
Closes #594. 
This PR:
- Tags new bot token secrets with a `environment` tag set to `staging` or `production`
- Relies on IAM policies to restrict access 
- Displays generic error message to users
Deploy this to staging to test: 
1. Create a new Telegram bot, store on staging
2. Check that `environment` is set to `staging` in the stored secret on Secrets Manager
3. Change the `environment` value to something else
4. Delete the credential in Postman and try storing again
- You should get "Error storing credentials" on the frontend
- In CloudWatch, there should be an entry like: 
```
error - User: arn:<beanstalk instance role> is not authorized to perform: …
```
> chore: Restrict Telegram bot token access

- backend/__tests__/phone-number.service.test.ts
- backend/src/core/services/phone-number.service.ts
- backend/src/telegram/services/telegram.service.ts
- worker/src/core/services/phone-number.service.ts
`libphonenumber` [regex for Singapore number](https://github.com/google/libphonenumber/blob/60c5863a4f0082448f42e4ecc49915003bb5f1e5/resources/PhoneNumberMetadata.xml#L24998) is out-of-date and treats numbers starting with `802` as invalid numbers ([link to tester](http://libphonenumber.appspot.com/phonenumberparser?number=80212345&country=SG)). This results in SMS/Telegram messages not being able to be sent to these numbers as they fail validation. 
Broadly, we want to support the following scenarios: 
- Local numbers - with `+65`, without `+65` and without `+` (e.g. `91234567`, `+6591234567`, `6591234567`)
- Foreign numbers - with `+` and without `+` (e.g. `+14128018888`, `14128018888`)
**Bug Fixes**:
- Use a custom regex to validate Singapore numbers ([regex tester for proposed …
> fix: Use custom validation for Singapore numbers

- backend/src/core/interfaces/campaign.interface.ts
- backend/src/core/services/stats.service.ts
- frontend/src/classes/Campaign.ts
- frontend/src/components/common/export-recipients/ExportRecipients.module.scss
- frontend/src/components/common/export-recipients/ExportRecipients.tsx
- frontend/src/components/common/progress-details/ProgressDetails.module.scss
- frontend/src/components/common/progress-details/ProgressDetails.tsx
- frontend/src/components/dashboard/campaigns/Campaigns.tsx
- frontend/src/services/campaign.service.ts
Export button is stuck in loading status after campaign has been sent out, until page is refreshed.
Closes #623 
After campaign status became `Status.Sent`, `ExportRecipients` component stopped checking for the export status. To ensure that the export status is updated after campaign has been sent, poll the export status until it returns a finalised status.
> Poll export status to prevent being stuck in loading status

- frontend/src/components/common/confirm-modal/ConfirmModal.module.scss
- frontend/src/components/common/confirm-modal/ConfirmModal.tsx
- frontend/src/components/dashboard/create/Create.tsx
- frontend/src/components/dashboard/create/email/EmailCreate.tsx
- frontend/src/components/dashboard/create/email/EmailTemplate.tsx
- frontend/src/components/dashboard/create/email/ProtectedEmailRecipients.tsx
- frontend/src/components/dashboard/create/save-draft-modal/SaveDraftModal.tsx
- frontend/src/components/dashboard/create/save-draft-modal/index.ts
- frontend/src/components/dashboard/create/sms/SMSCreate.tsx
- frontend/src/components/dashboard/create/sms/SMSTemplate.tsx
- frontend/src/components/dashboard/create/telegram/TelegramCreate.tsx
- frontend/src/components/dashboard/create/telegram/TelegramTemplate.tsx
Clicking the "Finish this later" button does not save the campaign, causing the user to lose their template draft.
Closes #622.
- Add a ref to hold a callback that is executed when the finish later button is clicked
- Allow child components to set the ref
- If errors occur when executing the callback, navigation back to `/campaigns` is aborted
1. Create a new campaign, populate the subject and body
2. Click "Finish this later"
- Should make a network call to save the template
- Should navigate back to campaigns dashboard
3. Select the same campaign, the template draft should be there
- Draft saving is only done when the current campaign state complies with backend validation rules - is this ok? 
- Email / Protected email: `subject` and `body` not null, `body` contains `{{ protectedlink …
> fix: Save template draft when choosing to finish later

- serverless/log-twilio-callback/package-lock.json
- serverless/log-twilio-callback/package.json
- serverless/log-twilio-callback/src/index.ts
I replaced bcryptjs with bcrypt, because the last update to bcryptjs was 4 years ago - it no longer looks actively maintained. Furthermore, it's purportedly slower than bcrypt. 
From [bcryptjs](https://www.npmjs.com/package/bcryptjs):
> While bcrypt.js is compatible to the C++ bcrypt binding, it is written in pure JavaScript and thus slower (about 30%), effectively reducing the number of iterations that can be processed in an equal time span.
bcryptjs is currently used in frontend as well, but that can't be helped since it has to be compatible with browers.
> chore(deps): replace bcryptjs with bcrypt@^5.0.0

- .travis.yml
Travis builds for the serverless functions were taking pretty long as the pre-deploy build process was being repeated for every function.
Split the builds into separate jobs
> refactor: split serverless builds on travis

- README.md
Without `detect-secrets` installed, no commits can be made and husky will just throw a generic error.
> chore: update docs to include installation of detect-secrets

- serverless/log-twilio-callback/src/index.ts
User reported discrepancy between twilio logs and Postman's logs. Turns out we weren't updating the error_code column correctly.
Update the correct column
- Locally: Post an event to your lambda running locally
Before
After
- End to end : I've built it on the staging lambda, and sent a message with the id '300643'. Twilio still reports the message as 'Sent', not 'Failed' (it's expected to fail because that number doesn't exist). When it returns the failed callback, the message status should change from 'SUCCESS' to 'ERROR'.
> fix: wrong column name in twilio callback

- backend/src/core/middlewares/auth.middleware.ts
- backend/src/core/services/auth.service.ts
- backend/src/core/utils/morgan.ts
- backend/src/core/utils/request.ts
Closes #670
**Features**:
Updated email copy as per #670
Simplify the logic to retrieve client ip address in [utils/morgan](https://github.com/opengovsg/postmangovsg/compare/develop...xming13:feature/ip-in-otp-email?expand=1#diff-11db5c924dfc4cc48b1707ce8134b79aL4). 
CF-Connecting-IP will always have one IP according to https://support.cloudflare.com/hc/en-us/articles/200170986-How-does-Cloudflare-handle-HTTP-Request-headers-
>To restore original visitor IP addresses at your origin web server, Cloudflare recommends your logs or applications look at CF-Connecting-IP or True-Client-IP instead of X-Forwarded-For since CF-Connecting-IP and True-Client-IP have a consistent format containing only one IP. 
**BEFORE**:
**AFTER**:
Note: There is no valid ip address in this …
> feat: add originating IP address for OTP email

- worker/package-lock.json
- worker/package.json
- worker/src/core/loaders/message-worker/index.ts
Addresses #501
The following query computes time taken for email messages to be sent. 
```sql
-- Compute ratio of time taken to expected time. The closer it is to 1, the better.
select *,  time_taken/expected_time as ratio from (
-- Expected time taken (based on number of messages / send rate)
select a.campaign_id, num_messages, extract(epoch from time_taken) as time_taken, (num_messages::float/job_queue.send_rate) as expected_time, job_queue.updated_at from (
-- Actual Time taken for num_messages to be sent
select campaign_id, count(*) as num_messages, max(delivered_at)-min(sent_at) as time_taken  from email_messages, campaigns where email_messages.campaign_id = campaigns.id  and sent_at is not null group by campaign_id
) a, 
job_queue where job_queue.campaign_id = a.campaign_id and …
```
> Speed up worker

- backend/src/sms/services/twilio-client.class.ts
- worker/src/sms/services/twilio-client.class.ts
Closes #672 
This parameter is undocumented in Twilio, but recommended by Twilio Support to get past the validation issue
> chore: force sms for numbers starting with +6580 to be delivered

- frontend/src/components/common/pagination/Pagination.tsx
- frontend/src/components/common/progress-details/ProgressDetails.tsx
Closes #687 
**Bug Fixes**:
- `pageCount` wasn't rounded up to an integer
- Removed unused `useState` and `useEffect` imports that were raising a warning
- Have <= 10 campaigns 
- Check that both arrows for pagination component are disabled
> fix: Disable campaign pagination arrow when there is only a single page

- worker/package-lock.json
- worker/package.json
- worker/src/core/loaders/message-worker/index.ts
- worker/src/core/resources/sql/set-job-to-sent.sql
- worker/src/email/resources/sql/get-messages-to-send-email.sql
- worker/src/sms/resources/sql/get-messages-to-send-sms.sql
- worker/src/telegram/resources/sql/get-messages-telegram.sql
Fixing https://github.com/opengovsg/postmangovsg/pull/608
`SENT` state was prematurely set when messages were being retrieved faster than the network calls were resolving. 
This caused the logger to log messages early, resulting in a condition where the messages were actually sent, but not updated to the ops table (because the messages had already been transferred back from ops table to the messages table)
Only set the state to `SENT` when all the promises have resolved / the failsafe is breached.
The entire purpose of the initial design was to prevent the app from having to hold all the messages in memory (ie, make one getMessages call for all the messages, and send them out at the specified rate). This prevents OOM, and since it only dequeues messages as needed,, we would lose fewer …
> Speed up worker part 2

- backend/src/email/services/email-template.service.ts
- backend/src/email/services/email.service.ts
- backend/src/sms/services/sms-template.service.ts
- backend/src/telegram/services/telegram-template.service.ts
Recipient email addresses are not converted to lowercase before saving them to the db. Some invalid email addresses are not caught by the blacklist as there is discrepancy in matching to the similar uppercase/mixed-case recipients in the `email_blacklist` table.
Closes #678 
- Convert recipients to lowercase before saving them to `email_messages`
`UPDATE email_blacklist SET recipient= LOWER(recipient);`
- Tested locally
- To be run on prod when approved
- Removed unused functions in channel template services
> Convert recipient email addresses to lowercase before saving to DB

- backend/src/email/services/email.service.ts
- backend/src/sms/services/sms.service.ts
- backend/src/telegram/services/telegram.service.ts
Noticed that many emails with leading/trailing spaces were being marked with the error code "Recipient is incorrectly formatted"
Trim the recipients before saving
> chore: trim recipients before saving

- backend/.env-example
- backend/src/core/config.ts
- backend/src/sms/middlewares/index.ts
- backend/src/sms/middlewares/sms-callback.middleware.ts
- backend/src/sms/routes/sms-callback.routes.ts
- backend/src/sms/services/index.ts
- backend/src/sms/services/sms-callback.service.ts
- worker/.env-example
- worker/src/sms/services/twilio-client.class.ts
How to test?
```bash
npm run dev # spins up server on localhost:4000
ngrok http 4000 # creates a tunnel
```
Then set the webhook and twilio credentials in your worker env vars
```
TWILIO_API_SECRET=123
TWILIO_MESSAGING_SERVICE_SID=MG123
TWILIO_API_KEY=SK123
TWILIO_ACCOUNT_SID=AC123
TWILIO_CALLBACK_SECRET='abcde' # same as backend
BACKEND_URL=https://98d448999539.ngrok.io/v1/callback/sms
```
Send a message - the status of the sms message should be success/error. 
This is an example of a request sent for a successfully delivered message from Twilio. 
```bash
curl -L -k -X POST  --header "Content-Type:application/x-www-form-urlencoded; charset=utf-8" -d "To=%2B6580000000&AccountSid=AC123&ApiVersion=2010-04-01&MessageStatus=delivered&SmsSid=SM123&MessagingServiceSid=MG123&From=postman&MessageS …
```
> refactor(callback): sms

- backend/package-lock.json
- frontend/package-lock.json
- frontend/package.json
- serverless/telegram-handler/package-lock.json
- worker/package-lock.json
Address node-fetch vulnerability (https://github.com/advisories/GHSA-w7rc-rwvf-8q5r) and other vulnerabilities by running npm audit and npm audit fix in each directory
> Fix vulnerabilities using npm audit fix

- backend/src/core/interfaces/campaign.interface.ts
- backend/src/core/services/campaign.service.ts
- backend/src/core/services/stats.service.ts
- backend/src/email/middlewares/email-stats.middleware.ts
- backend/src/email/routes/email-campaign.routes.ts
- backend/src/email/services/email-stats.service.ts
- backend/src/sms/middlewares/sms-stats.middleware.ts
- backend/src/sms/routes/sms-campaign.routes.ts
- backend/src/sms/services/sms-stats.service.ts
- backend/src/telegram/middlewares/telegram-stats.middleware.ts
- backend/src/telegram/routes/telegram-campaign.routes.ts
- backend/src/telegram/services/telegram-stats.service.ts
- frontend/src/classes/Campaign.ts
- frontend/src/components/common/export-recipients/ExportRecipients.tsx
- frontend/src/components/common/progress-details/ProgressDetails.tsx
- frontend/src/components/dashboard/campaigns/Campaigns.tsx
- frontend/src/components/dashboard/create/email/EmailDetail.tsx
- frontend/src/components/dashboard/create/sms/SMSDetail.tsx
- frontend/src/components/dashboard/create/telegram/TelegramDetail.tsx
- frontend/src/services/campaign.service.ts
Add successfully sent messages in the exported recipient list.
Closes #489 
**Features**:
- Include messages with "SUCCESS" status in `GET /export` endpoint
- Show export button on frontend even if there are no failed recipients
- Added loading spinner for "Delivery report" Button while exporting
**Bug fixes**
- Standardised the copywriting on the campaign details page for all channels. Telegram was different previously.
Decided not to implement backend generation/streaming of the responses to the frontend as the added complexity was not worth it given the following reasons:
- Typical number of recipients for our campaigns are < 1000
- Even in the worst case (200k recipients), memory usage in the browser maxes out at ~130MB
- Shifting the CSV generation to the backend is …
> feat: Include successfully sent messages in export

- .secrets.baseline
- backend/.env-example
- backend/src/core/interfaces/campaign.interface.ts
- backend/src/core/services/stats.service.ts
- frontend/src/classes/Campaign.ts
- frontend/src/components/dashboard/create/email/EmailDetail.tsx
- frontend/src/components/dashboard/create/sms/SMSDetail.tsx
- frontend/src/components/dashboard/create/telegram/TelegramDetail.tsx
It would be informative to users who have queued campaigns to know what is the queued status of their campaign and how long they it would take for their campaign to start sending out.
Backend changes to return metrics relevant to #658 
- Extend the existing `/stats` endpoint to also return campaign queue status if campaign's job is in `READY` status
- Get the position of the job in the queue
- Compute an approximate time taken for preceding jobs to complete
> Compute queue position and wait time for queued campaigns

- backend/src/core/errors/s3.errors.ts
- backend/src/core/errors/template.errors.ts
- backend/src/core/services/auth.service.ts
- backend/src/core/services/parse-csv.service.ts
- backend/src/core/services/protected.service.ts
- backend/src/core/services/stats.service.ts
- backend/src/email/middlewares/email-template.middleware.ts
- backend/src/sms/middlewares/sms-template.middleware.ts
- backend/src/telegram/middlewares/telegram-template.middleware.ts
- frontend/src/classes/Campaign.ts
- frontend/src/classes/EmailCampaign.ts
- frontend/src/classes/SMSCampaign.ts
- frontend/src/classes/TelegramCampaign.ts
- frontend/src/components/common/export-recipients/ExportRecipients.tsx
- frontend/src/components/common/progress-details/ProgressDetails.tsx
- frontend/src/components/dashboard/campaigns/Campaigns.tsx
- frontend/src/components/dashboard/create/email/EmailDetail.tsx
- frontend/src/components/dashboard/create/sms/SMSDetail.tsx
- frontend/src/components/dashboard/create/telegram/TelegramDetail.tsx
- frontend/src/locales/en/messages.po
- frontend/src/services/campaign.service.ts
Improve both API error and message delivery errors wording to be more user-friendly. Changes were made with reference to [this spreadsheet](https://docs.google.com/spreadsheets/d/1z2hHa8uSuw1SVbgG29bfx3hCBQabRhLZ8o3nF1Jzwqk/edit#gid=1269298248).
Closes #336 
Updated following error messages:
- Missing recipient column
- Expired OTP
- Missing keywords in recipient list
- Missing campaign template
- Invalid characters in template keyword
- No rows found in recipient list
- Mismatch in number of fields in the recipient list
- Invalid message A keywords
Updated following email delivery errors:
- Soft bounce
- Hard bounce
- Blacklisted email
- Complaint
- Incorrectly formatted email address
Updated following SMS delivery errors:
- Unreachable phone number
- Incorrectly …
> chore: Improve error messages

- amplify.yml
Existing CSP headers do not allow connection to Google Analytics. 
Closes #742 
**Features**:
- Add `https://www.google-analytics.com` to `connect-src`
- Deploy onto staging and verify that there is not longer an error for Google Analytics
**Why was GA still working previously?** 
Google analytics [supports three different transportation mechanism](https://developers.google.com/analytics/devguides/collection/analyticsjs/sending-hits#specifying_different_transport_mechanisms) (image, xhr and beacon). Since we allowed `https://www.google-analytics.com` in the `image-src` directive, data is still being sent back to GA. GA automatically picks the optimal transport to use. Adding GA to `connect-src` will allow GA to use `beacon` and `xhr` mode when it deems suitable. 
**Why is there still a …
> chore: Add Google Analytics to connect-src CSP headers

- .travis.yml
- backend/Dockerfile
- backend/before-deploy.sh
- backend/docker-entrypoint.sh
We want to centralize our AWS related secrets in AWS Secrets Manager (SM). 
Needed a way to fetch the secrets from SM in Elastic Beanstalk.
Initially we wanted to fetch the secrets at the app level (#666), but we decided that it is added too much complexity. 
Instead, we will fetch the secrets & export them as environment variables in Docker, after the container has started. 
We replaced the `npm start` cmd with a bash script `docker-entrypoint.sh`.
In order to fetch the secrets from SM and export them as environment variables, we have to install `aws-cli` & `jq` on the image. 
**Features**:
- Installed aws-cli & jq on the docker image
- Added a travis before-deploy script to replace the secret id according to the travis branch
- Added a script to be used as a entry point
- Script fetches …
> feat: Fetching secrets in Docker, from AWS Secrets Manager

- frontend/src/components/common/preview-block/PreviewBlock.tsx
Preview block was escaping the message body. This results in the raw HTML code being shown instead of rendering the HTML. Users will not be able to see how their rendered message body will look like until they send a test message.
**Bug Fixes**:
- Remove escaping of message body for PreviewBlock. Escaping is still preserved for other fields (From, Subject, Reply To).
**BEFORE**:
**AFTER**:
- Create a new email campaign with the following template and choose `Postman.gov.sg <donotreply@mail.postman.gov.sg>` as the From email
```
<b>bold</b>, bold
<i>italic</i>, italic
<u>underline</u>, underline
strikethrough, strikethrough, strikethrough
<b>bold <i>italic bold italic bold strikethrough <u>underline italic bold</u></i> bold</b>
<a href="https://www.google.com/">Google</a>
```
- Check that …
> fix: Preview component not rendering HTML for message body

- serverless/database-backup/src/backup.ts
Backup retries on the same day fail due to a conflict in backup folder name.
- Add time to backup folder name. New folder name follows the following format `YYYY-MM-DD_HH-mm-ss`
> chore: Include time in backup folder name

- .travis.yml
- serverless/eb-env-update/.env-example
- serverless/eb-env-update/.eslintrc.js
- serverless/eb-env-update/.prettierrc.js
- serverless/eb-env-update/package-lock.json
- serverless/eb-env-update/package.json
- serverless/eb-env-update/src/config.ts
- serverless/eb-env-update/src/index.ts
- serverless/eb-env-update/tsconfig.json
When environment variables for the elastic beanstalk environment are updated in Secrets' Manager, the developer may forget to redeploy the environment.
**EDIT: Reverted to option 1 because keewei saw that the configuration using rolling deployments with rolling update type would enable the containers to be restarted in a rolling fashion.**
Option 1. Restart app server
Originally I wanted to go with this as it was super fast. But restarting the app server appeared to cause downtime as all of the containers would be restarted at once, instead of in a rolling fashion.
Option 2. Pretend to update an env var
This implementation updates the elastic beanstalk environment with the request id of the lambda invocation, to trigger a redeploy. There is now no time savings from using secrets manager …
> feat: lambda that updates environment when secrets manager is updated

- backend/src/telegram/services/telegram-template.service.ts
When the telegram template is updated to include keywords that are not found in the previously uploaded file, the uploaded file should be removed.
Closes #818 
If the telegram template contains extra keywords, remove all records in the `telegram_messages` table and remove the message status count in `statistic` table.
1. Create telegram campaign
2. Create template
3. Upload a file
4. Update the template to include keywords which are absent in uploaded file
5. Check that the uploaded file is removed
> Remove uploaded file when Telegram template is updated

- frontend/src/components/common/progress-details/ProgressDetails.tsx
- frontend/src/components/common/step-header/StepHeader.module.scss
- frontend/src/components/common/step-header/StepHeader.tsx
- frontend/src/components/dashboard/settings/api-key/ApiKey.tsx
- frontend/src/components/dashboard/settings/credentials/Credentials.module.scss
- frontend/src/components/dashboard/settings/credentials/Credentials.tsx
Designers feedback that the previous UI fixes introduced wrong styles for `StepHeader` and the titles in the Settings page.
**Bug Fixes**:
- Use `h3` for `StepHeader`
- Use `h3` for credentials pages
**Before**
**After**
> style: Fix section title typography styles

- amplify.yml
- backend/src/sms/middlewares/sms.middleware.ts
- backend/src/sms/routes/sms-campaign.routes.ts
- backend/src/telegram/middlewares/telegram.middleware.ts
- backend/src/telegram/routes/telegram-campaign.routes.ts
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/common/dropdown/Dropdown.module.scss
- frontend/src/components/common/dropdown/Dropdown.tsx
- frontend/src/components/dashboard/create/sms/SMSCredentials.tsx
- frontend/src/components/dashboard/create/telegram/TelegramCredentials.tsx
- frontend/src/components/dashboard/demo/completed-demo-modal/CompletedDemoModal.module.scss
- frontend/src/components/dashboard/demo/completed-demo-modal/CompletedDemoModal.tsx
- frontend/src/components/dashboard/demo/create-demo-modal/CreateDemoModal.tsx
- frontend/src/components/dashboard/demo/demo-video-modal/DemoVideoModal.module.scss
- frontend/src/components/dashboard/demo/demo-video-modal/DemoVideoModal.tsx
- frontend/src/components/dashboard/demo/demo-video-modal/index.ts
- frontend/src/components/dashboard/settings/add-credential-modal/AddCredentialModal.tsx
- frontend/src/components/dashboard/settings/custom-from-address/CustomFromAddress.tsx
- frontend/src/components/landing/Landing.tsx
- frontend/src/config.ts
- frontend/src/locales/en/messages.po
- frontend/src/styles/app.scss
Updates needed for demo mode
Closes #820
- Add a demo video modal, accessible when users click on "Watch video"
- Prevent use of non-demo credentials in demo campaigns
- Move getting of stats on landing page inside useEffect to get rid of memory leak complaint
- Posting to /new-credentials is not allowed for demo campaigns
- Demo campaigns can use only demo credentials
- Non demo campaigns cannot use demo credentials
- Created a new **public** bucket for the video
- Added csp headers to allow videos originating from that bucket
**New dependencies**
- `react-player` : component for playing video
> feat: add demo video modal for demo mode, and ui updates

- frontend/src/components/dashboard/create/telegram/TelegramCredentials.tsx
Unable to save credential from insert credentials step for Telegram channel.
Closes #837
Include label in args for `validateNewCredentials` function call in `TelegramCredentials` component.
> Fix saving telegram credential from create campaign page

- frontend/src/components/dashboard/create/email/EmailCredentials.tsx
- frontend/src/components/dashboard/create/email/EmailRecipients.tsx
- frontend/src/components/dashboard/create/email/EmailSend.tsx
- frontend/src/components/dashboard/create/email/EmailTemplate.tsx
- frontend/src/components/dashboard/create/sms/SMSCredentials.tsx
- frontend/src/components/dashboard/create/sms/SMSRecipients.tsx
- frontend/src/components/dashboard/create/sms/SMSSend.tsx
- frontend/src/components/dashboard/create/sms/SMSTemplate.tsx
- frontend/src/components/dashboard/create/telegram/TelegramCredentials.tsx
- frontend/src/components/dashboard/create/telegram/TelegramRecipients.tsx
- frontend/src/components/dashboard/create/telegram/TelegramSend.tsx
- frontend/src/components/dashboard/create/telegram/TelegramTemplate.tsx
- frontend/src/contexts/campaign.context.tsx
Previously completed steps in progress pane were disabled. 
Closes #838
Campaign progress was not being updated when campaign state was updated. The progress pane steps render enabled/disabled state based on the campaign progress property.
**Bug Fixes**:
- Create a function to handle updates to the campaign state in the campaign context provider
- Call the campaign `setProgress` function to update the progress value for the campaign state
- Implement `useCallback` for `updateCampaign` function to prevent re-render due to function being re-initialised for every render (**Looking into if this is the best way to do this**)
1. Create a new sms campaign
2. Save a template, upload a file and click next
3. Now you should be at the insert credentials step
4. Previous step 'Upload recipients' is …
> Fix: campaign progress not updated when campaign properties were updated

- .travis.yml
Lockfiles do not get properly inspected at PRs, so it might be trivial to sneak something
past the PR that we may not want
use lockfile-lint to inspect lockfiles
> build(ci): use lockfile-lint to inspect lockfiles

- backend/src/email/routes/email-campaign.routes.ts
- backend/src/sms/routes/sms-campaign.routes.ts
- backend/src/telegram/routes/telegram-campaign.routes.ts
- docs/api-usage.md
- frontend/src/components/dashboard/create/telegram/TelegramCredentials.tsx
- frontend/src/services/upload.service.ts
Part 1 of #802 
- Update `/upload` and `/complete` endpoint to enforce use of MD5 checksums and ETag
- Add redirects for `/upload-v2` and `/complete-v2`
- Update API Usage docs
**Testing through UI** 
- Create and send campaigns for each channel type (SMS, Telegram, Email and Protected Email).
- Ensure that upload and processing of CSV does not introduce any regressions
**API testing**
- Follow the steps documented in `api-usage.md`
- Ensure that campaign can be created and sent as expected.
> chore: Deprecate upload and complete endpoint

- backend/src/sms/routes/sms-campaign.routes.ts
- backend/src/telegram/routes/telegram-campaign.routes.ts
- frontend/src/services/sms.service.ts
- frontend/src/services/telegram.service.ts
Part 1 of #805
- Update `/new-credentials` endpoint to accept optional `label` body parameter
- Redirect `/new-credentials/v2` to `/new-credentials` for SMS and Telegram
- Update frontend to use the updated `/new-credentials` endpoint
> Deprecate new-credentials endpoint

- backend/src/email/services/email-template.service.ts
- backend/src/sms/services/sms-template.service.ts
- backend/src/telegram/services/telegram-template.service.ts
Saving a message template with only invalid HTML tags results in an empty template being saved to the database.
Closes #792
Check that for empty message templates and that message template is not empty after it has been sanitised.
- Frontend: Trim whitespaces to check for empty message template to disable next button
- postman-templating: Add new function in template client to strip all html tags from input
**Bug Fixes**:
- Strip all tags and leading whitespace from raw template and check that message is not empty
- Do same check on frontend for protected email template before processing csv
- If message template is empty, throw a `TemplateError` with the error message `Message template is empty!`
- Check that sanitised message template is not empty before upserting into …
> Fix: Check if sanitised template is empty before upserting template

- frontend/src/components/dashboard/campaigns/Campaigns.tsx
- frontend/src/components/dashboard/create/Create.module.scss
- frontend/src/components/dashboard/create/sms/SMSCredentials.tsx
- frontend/src/components/dashboard/create/telegram/TelegramCredentials.tsx
- frontend/src/styles/_mixins.scss
Fix a few UI issues highlighted for demo campaign creation.
Closes #821
- Do not display demo bar in empty dashboard page
- Other minor css fixes
- Check that demo bar is not displayed when dashboard is empty
- In Telegram demo campaign credentials screen. check that bot link is in bold and changes to red when pressed (mouse down state)
> UI fixes for demo campaign creation flow

- backend/package-lock.json
- frontend/package-lock.json
- frontend/src/components/common/protected-preview/ProtectedPreview.module.scss
- modules/postman-templating/package-lock.json
- modules/postman-templating/package.json
- modules/postman-templating/src/template-client.ts
- modules/postman-templating/test/template-client.test.ts
- worker/package-lock.json
Closes #857 
**Features**:
- Query and remove all `:empty` tags, except for `img`, `br` and `hr`. 
- Updated table styles to standardise column sizes
Branch is currently hosted at https://emptylines.postman.gov.sg. Apart from running the unit tests, you may also test out the following scenarios. 
Use the following recipient list for the tests:
```
recipient,password,value1
test@test.com,1111,
```
**Nested tags**
Create protected email campaign with the following template. Make sure to check remove empty lines option.
```
<b><i>{{value1}}</i></b>{{value1}}
<b><i>{{value1}}</i></b>{{value1}}
<b><i>{{value1}}</i></b>{{value1}}
<b><i>{{value1}}</i></b>{{value1}}
hello
```
First four rows should be collapsed to 1 `<br />`. 
**Empty table rows**
Create protected email campaign …
> fix: Remove empty rows with tags

- backend/src/email/middlewares/email-template.middleware.ts
- backend/src/email/routes/email-campaign.routes.ts
- frontend/src/components/dashboard/create/email/EmailTemplate.tsx
Closes #854 
**Features**:
- Set logged in user email address as reply to if not provided
- Create a new email campaign
- Leave reply to as empty and save template
- Check that the reply to field is set as the logged in user's email in the database
> feat: Make reply-to address compulsory

- frontend/src/components/common/action-button/ActionButton.module.scss
- frontend/src/components/common/confirm-modal/ConfirmModal.module.scss
- frontend/src/components/common/export-recipients/ExportRecipients.module.scss
- frontend/src/components/common/nav-bar/NavBar.module.scss
- frontend/src/components/common/pagination/Pagination.module.scss
- frontend/src/components/common/progress-details/ProgressDetails.module.scss
- frontend/src/components/common/send-rate/SendRate.module.scss
- frontend/src/components/common/side-nav/SideNav.module.scss
- frontend/src/components/dashboard/campaigns/Campaigns.module.scss
- frontend/src/components/dashboard/campaigns/Campaigns.tsx
- frontend/src/components/dashboard/create/create-modal/CreateModal.module.scss
- frontend/src/components/dashboard/create/duplicate-campaign-modal/DuplicateCampaignModal.module.scss
- frontend/src/components/dashboard/demo/completed-demo-modal/CompletedDemoModal.module.scss
- frontend/src/components/dashboard/demo/create-demo-modal/CreateDemoModal.module.scss
- frontend/src/components/dashboard/settings/credentials/Credentials.module.scss
- frontend/src/components/dashboard/settings/custom-from-address/CustomFromAddress.module.scss
- frontend/src/styles/base/_buttons.scss
- frontend/src/styles/base/_icons.scss
Icon sizes were not standardised across the button icons and other isolated icons.
Closes #859 
- Introduce css mixin for large icons (only two sizes of icons exist as of now - default and large)
- Standardise icon sizes by using relevant mixins
> Standardise icon sizes

- serverless/verify-backup/.gitignore
- serverless/verify-backup/README.md
- serverless/verify-backup/package-lock.json
- serverless/verify-backup/package.json
- serverless/verify-backup/scripts/verify-backup.sh
- serverless/verify-backup/src/config.ts
- serverless/verify-backup/src/decrypt-dump.ts
- serverless/verify-backup/src/index.ts
- serverless/verify-backup/src/server.ts
`verify-backup.sh` had hardcoded values for restore database name and database user. This made it hard to use this as a generic backup restore script without having to modify the script. 
- Use [PostgreSQL environment variables](https://www.postgresql.org/docs/11/libpq-envars.html) instead of `su - postgres` to assume user to run commands.
- Made `verify-backup.sh` executable
- Add flag to toggle Sentry notification
- Prettier source files (eslint prettier were missing previously)
- Run `verify-backup.sh` script locally and specify values for `PGUSER` and `PGDATABASE`. Detailed instructions in `README.md`.
- Deploy to staging and check in logs that verification is working as expected. Use `deploy.sh` and credentials in 1Password.
New scripts:
- Following the instructions …
> chore: Parameterised database restore script

- frontend/src/components/common/primary-button/PrimaryButton.tsx
- frontend/src/components/common/text-button/TextButton.module.scss
- frontend/src/components/common/text-input-with-button/TextInputWithButton.tsx
- frontend/src/components/custom-hooks/use-is-mounted.tsx
- frontend/src/components/dashboard/create/email/EmailRecipients.tsx
- frontend/src/components/dashboard/create/email/EmailTemplate.tsx
- frontend/src/components/dashboard/create/email/EmailValidationInput.tsx
- frontend/src/components/dashboard/create/sms/SMSCreate.tsx
- frontend/src/components/dashboard/create/sms/SMSRecipients.tsx
- frontend/src/components/dashboard/create/sms/SMSTemplate.tsx
- frontend/src/components/dashboard/create/sms/SMSValidationInput.tsx
- frontend/src/components/dashboard/create/telegram/TelegramCreate.tsx
- frontend/src/components/dashboard/create/telegram/TelegramRecipients.tsx
- frontend/src/components/dashboard/create/telegram/TelegramTemplate.tsx
- frontend/src/components/dashboard/create/telegram/TelegramValidationInput.tsx
- frontend/src/components/dashboard/settings/api-key/ApiKey.tsx
- frontend/src/components/landing/Landing.tsx
- frontend/src/components/login/login-input/LoginInput.tsx
**Prevent setting state after component is dismounted**
There are many instances where `useEffect` sets components state after running asynchronous queries. When the component is dismounted before these execute finish, they result in react trying to update the state of an unmounted component. This throws a warning that this may indicate a potential memory leak in the app.
Closes #846 
Closes #858 
Ran through different user flows to check for warnings, let me know if there are some which have not been addressed!
**Bug Fixes**:
- When handling finish later - save draft callbacks, remove use of `handleSaveTemplate()` which has redundant setState calls and instead use `saveTemplate` to directly call endpoint
- clear timers set in `useEffect` hooks for `ApiKey` and `LoginInput` component
- In …
> Prevent setting state after component is dismounted

- docs/api-usage.md
Closes #865 
- Update the api usage docs to include check on file processing status
- Instructions on how to use the `/upload/status` endpoint and handling the response data on success and failure
> Chore: update api-usage docs to include file processing status

- frontend/src/components/dashboard/create/Create.tsx
- frontend/src/components/dashboard/create/email/EmailTemplate.tsx
- frontend/src/components/dashboard/create/sms/SMSTemplate.tsx
- frontend/src/components/dashboard/create/telegram/TelegramTemplate.tsx
After a user enters an invalid template and clicks 'Finish Later' button on Create template screen, the 'Finish Later' modal will open. When clicking 'Save draft', this will then display an error together with the 'Edit Draft' button. When clicking on the 'Edit Draft' button, the page routes to the dashboard view. This is an incorrect behaviour.
Closes #871 
**Bug Fixes**:
https://github.com/opengovsg/postmangovsg/blob/347ebfa58894a162b79dfbb380d92c57f7138546/frontend/src/components/dashboard/create/Create.tsx#L38-L44
Previously, we did not `return finishLaterContextHandler() `, hence the page was routed to the dashboard regardless of the outcome of the SaveDraft modal. By returning the handler, when `finishLaterContent` is defined, i.e. it will open SaveDraft modal when clicked, any page …
> Fix: edit draft returns user to main dashboard instead of template page

- frontend/src/components/dashboard/campaigns/Campaigns.tsx
- frontend/src/components/dashboard/create/duplicate-campaign-modal/DuplicateCampaignModal.tsx
- frontend/src/services/ga.service.ts
Closes #881 
- Added the following GA events:
- `OPEN_DUPLICATE_MODAL` - Sent when user open duplication modal from the campaigns table
- `COMPLETE_DUPLICATE`  - Sent when user complete a campaign duplication
- Include campaign type as label for events
> chore: Add GA events for campaign duplication

- serverless/verify-backup/.env-example
- serverless/verify-backup/Dockerfile
- serverless/verify-backup/scripts/run.sh
- serverless/verify-backup/scripts/verify-backup.sh
A cloud scheduler job is scheduled to trigger the verify-backup service after database backups are completed every night. However the cloud scheduler job may fail to run, and the backup verification will fail silently. To prevent this, we need to setup a Cronitor job to monitor the verification job.
Closes #896 
- Add cronitor calls in the docker entrypoint script `run.sh` and `verify-backup.sh`
- Cronitor job `postmangovsg-staging-verify-backup` for staging at https://cronitor.io/dashboard?search=isPIpa
- Possible to test by modifying the alert trigger schedule, and cronitor should trigger a slack message when verify-backup job is not run 
- `CRONITOR_CODE ` : identifier string for cronitor integration
> Integrate cronitor for verify-backup

- backend/src/core/logger.ts
- backend/src/core/services/parse-csv.service.ts
There are a few instances in the code where we write the whole error object in the `catch` block to logs. An error object that contains an abnormally large amount of data, e.g. very long stack traces or sequelize error trace, could cause the server to go out of memory when writing the logs to cloudwatch. This would cause the server to restart, causing a temporary loss in service. 
After combing through the logs to identify such instances, my initial solution was to limit all functions with sequelize queries to output error logs with only `error.message`. However I realised this may not be a solid solution, as described below.
**Potential solutions**:
- Limit all functions with sequelize queries to output error logs with only `error.message`. This is not ideal as:
1. The functions with …
> Truncate log messages to prevent large logs causing memory issues

- frontend/src/components/dashboard/create/telegram/TelegramRecipients.tsx
Telegram next button was disabled after uploading recipients
**Bug Fixes**:
- Fix conditions for disabling TelegramRecipients next button
**BEFORE**:
**AFTER**:
- Create Telegram campaign and upload recipients
- When recipients is uploaded, the next button should be enabled
> fix: Disable Telegram next button when CSV is processing

- serverless/database-backup/package-lock.json
- serverless/database-backup/package.json
Updating dependencies suggested by Snyk for backup lambda.
**Upgraded dependencies**:
| Library | From | To |
| :------ | :---: | :---: |
| `pg` | 8.3.3 | 8.5.1 |
| `@google-cloud/storage` | 5.3.0 | 5.5.0 |
| `yargs` | 16.0.3 | 16.1.1 |
| `aws-sdk` | 2.749.0 | 2.801.0 |
| `@sentry/node` | 5.22.3 | 5.27.6 |
- Deploy and trigger backup lambda on staging
> chore: Update dependencies for database backup lambda

- backend/src/telegram/middlewares/telegram-callback.middleware.ts
- backend/src/telegram/utils/callback/handlers/contact.ts
When an error occurs within `handleUpdate`, an error message is sent back to the user through Telegram to notify him/her. However, when this error occurs, our callback handler endpoint does not return a `200` response to the Telegram API. This causes the Telegram API to repeatedly retry the webhook. 
This results in the user being spammed with the same error message. 
**Bug Fixes**:
- When an error occurs, log error and return 200 to the Telegram API to prevent retries
- Include `contact` and `from` in logs for debugging 
- Setup and verify a bot on Postman
- Send a contact that is not your own contact
- Check in logs that `200` is returned by the callback endpoint
- Check that error message is only sent once
> fix(telegram): return 200 to skip Telegram API retries

- docker-compose.yml
Closes #882 
**Bug Fixes**:
- Pin localstack to `0.11.6`. This is a temporary fix first so that `npm run dev:localstack` works. Will be taking a deeper look into what is causing the incompatibility. However, given that some features (custom from email) cannot be replicated with localstack, we might eventually deprecate it entirely.
> chore(localstack): pin localstack version to 0.11.6

- frontend/public/robots.txt
Crawlers may be overly aggressive and parse bundle.js for possible links.
This results in the crawler trying to request paths from Postman that do not
actually exist
None of the JavaScript source files will have links that crawlers can
follow, so prevent them from crawling them in the first place
> chore(robots): guide NLB crawler

- backend/src/core/routes/settings.routes.ts
- docs/creating-announcements.md
- frontend/src/components/common/text-button/TextButton.module.scss
- frontend/src/components/dashboard/campaigns/Campaigns.tsx
- frontend/src/components/dashboard/campaigns/announcement-modal/AnnouncementModal.module.scss
- frontend/src/components/dashboard/campaigns/announcement-modal/AnnouncementModal.tsx
- frontend/src/components/dashboard/campaigns/announcement-modal/AnnouncementModalOptions.module.scss
- frontend/src/components/dashboard/campaigns/announcement-modal/AnnouncementModalOptions.tsx
- frontend/src/components/dashboard/campaigns/announcement-modal/GraphicAnnouncementModal.module.scss
- frontend/src/components/dashboard/campaigns/announcement-modal/GraphicAnnouncementModal.tsx
- frontend/src/components/dashboard/campaigns/announcement-modal/VideoAnnouncementModal.module.scss
- frontend/src/components/dashboard/campaigns/announcement-modal/VideoAnnouncementModal.tsx
- frontend/src/config.ts
- frontend/src/locales/en/messages.po
This addresses issue #934. Namely,
1. SHA-256 version hashes are now being used instead of manual semantic versioning.
2. Videos can now be displayed (using the ReactPlayer component).
3. A secondary button can now be displayed.
4. The title will now be displayed at the upper left corner in the case of video content.
Closes #934.
**BEFORE**:
See issue #934.
**AFTER**:
Screenshots of the updated UI on 3 different form factors (iPad Pro, iPhone 6, Pixel 2 XL): https://drive.google.com/drive/folders/1S5rvXi16geWbjo1jUdbwppMblFTd17ty?usp=sharing
**Regarding version hashes:**
Before testing, ensure that `REACT_APP_ANNOUNCEMENT_ACTIVE="true"` is set in `.env`.
Tests:
- After closing the announcement modal, the …
> Update the announcement modal

- backend/src/email/routes/email-campaign.routes.ts
- backend/src/sms/routes/sms-campaign.routes.ts
- backend/src/telegram/routes/telegram-campaign.routes.ts
Continuation of the update of `/new-credentials`, `/upload/start` and `/upload/complete` routes. 
Closes #802 
Closes #805 
- Removed `/new-credentials/v2`
- Removed `/upload/start-v2`
- Removed `/upload/complete-v2`
- For each channel type:
- Check that upload can be started and completed
- Check that new credentials can be saved while creating a SMS/Telegram campaign
> chore: remove v2 endpoints for upload and new-credentials

- backend/package-lock.json
- backend/package.json
- frontend/package-lock.json
- frontend/package.json
- modules/postman-templating/package-lock.json
- modules/postman-templating/package.json
- serverless/unsubscribe-digest/package-lock.json
- serverless/unsubscribe-digest/package.json
- worker/package-lock.json
- worker/package.json
- `lodash` : upgrade from 4.17.20 to 4.17.21 
- `mustache`: upgrade from 4.0.1 to 4.1.0
- `@types/node`: upgrade from 14.14.10 to 14.14.22
- `@types/lodash`: upgrade from 4.14.165 to 4.14.168
- `@types/mustache`: upgrade from 4.0.1 to 4.1.1
> chore: upgrade dependencies recommended by snyk

- frontend/src/components/common/modal/Modal.module.scss
- frontend/src/components/common/progress-details/ProgressDetails.tsx
- frontend/src/components/common/text-area/TextArea.module.scss
- frontend/src/components/dashboard/create/create-modal/CreateModal.module.scss
- frontend/src/components/dashboard/create/create-modal/CreateModal.tsx
- frontend/src/components/dashboard/demo/create-demo-modal/CreateDemoModal.module.scss
- frontend/src/components/dashboard/demo/create-demo-modal/CreateDemoModal.tsx
- frontend/src/components/dashboard/demo/demo-video-modal/DemoVideoModal.module.scss
- frontend/src/components/dashboard/demo/demo-video-modal/DemoVideoModal.tsx
Addresses various miscellaneous UI issues.
Addresses issues #875, #876, #877, #911, #945.
For #875:
- For the TextArea component:
- Border width should become 1.5px on hover
- Border color should become #2C2CDC on hover
For #876:
- For the DemoVideoModal and CreateDemoModal components:
- In desktop mode, margin between the secondary TextButton and the PrimaryButton components should be $spacing-7 (3rem).
- In mobile mode, the secondary TextButton should above the PrimaryButton, and the both of them should be aligned horizontally
For #877:
- For the CreateModal and CreateDemoModal components:
- The actively selected campaign type button should not have any hover state
- The actively selected campaign type button should not do anything on click
For #911:
- For the ProgressDetails component: …
> Fix some P3 UI issues

- backend/src/core/routes/settings.routes.ts
The affected API endpoint uses `channelType` as a parameter, not `campaignId`.
**Tests**
Go to the `/docs` path and check that the Swagger doc for `/settings/{channelType}/credentials` shows `channelType` instead of `campaignId` for its parameter.
> backend/routes/settings: Fix API doc for retrieving credentials

- frontend/src/components/dashboard/Dashboard.tsx
Info banner is only visible on landing and the login page. Logged in users might not see the banner.
Closes #1018 
**Features**:
- Add info banner to the dashboard
- Set `REACT_APP_INFO_BANNER`
- Start/re-deploy frontend
- Banner should be visible on the dashboard
> feat: add info banner to dashboard

- serverless/verify-backup/scripts/deploy.sh
The verify backup production service failed today with the following memory exceeded error.
Memory utilisation metrics during failure
Previously the memory allocation was 4Gi and the cpu allocation was 1 core, however for 1 core, raising the memory to 6Gi was not supported. 
The cloud run deploy cli threw the following error: `For 1.0 CPU, memory must be between 0 and 4Gi inclusive.`
Hence I tested with 2 cpu cores, 4Gi and 6Gi memory. 
With 4Gi memory allocation, the memory utilisation was hitting above 90% hence I set the final memory allocation to 6Gi to have some buffer.
- Increased cpu cores from 1 to 2
- Increased memory from 4Gi to 6Gi
**Observation after a week**
The verify backup service has been running smoothly. The memory utilisation is below 60% currently. …
> Increase memory and cpu for verify backup service

- backend/package-lock.json
- backend/package.json
- serverless/redaction-digest/package-lock.json
- serverless/redaction-digest/package.json
- serverless/unsubscribe-digest/package-lock.json
- serverless/unsubscribe-digest/package.json
- worker/package-lock.json
- worker/package.json
The changelogs don't reveal any breaking changes affecting our usage.
**Worker**
|Dep|Old|New|
---|---|---
|`twilio`|3.42.2|3.55.1|
|`pg`|8.2.1|8.5.1|
|`sequelize`|5.21.5|5.22.3|
|`libphonenumber-js`|1.7.55|1.9.9|
New dependency: `@types/express` as it's a peer dependency of `twilio`
**Backend**
|Dep|Old|New|
---|---|---
|`twilio`|3.42.2|3.55.1|
|`pg`|8.2.1|8.5.1|
|`sequelize`|5.21.5|5.22.3|
|`libphonenumber-js`|1.7.55|1.9.9|
**Unsubscribe digest**
|Dep|Old|New|
---|---|---
|`sequelize`|5.21.11|5.22.3|
**Redaction digest**
|Dep|Old|New|
---|---|---
|`sequelize`|5.21.11|5.22.3|
> Update snyk-recommended dependencies

- frontend/src/components/common/rich-text-editor/RichTextEditor.tsx
Pasting in table cells were not handled correctly previously as the default paste handler inserts a new block. 
**Features**:
- Insert text when pasting within a table cell instead of creating a new block
**Inserting text in table cell**
- Create a new email campaign
- Create a table
- Copy and paste text within a single cell
- Text should be pasted
**Replacing text in table cell**
- Create a new email campaign
- Create a table and enter some text within the cell
- Select text within the cell and paste text over selection
- Text should replaced by pasted text
**Multiple cell selected**
- Create a new email campaign
- Create a table with multiple cells
- Select multiple cells and paste text 
- Text should only be pasted in the first cell
> fix(rich-text): allow paste within table cells

- frontend/src/components/landing/banner/Banner.module.scss
- frontend/src/components/protected/Protected.module.scss
- frontend/src/components/protected/Protected.tsx
- frontend/src/components/unsubscribe/Unsubscribe.module.scss
- frontend/src/components/unsubscribe/Unsubscribe.tsx
Closes issue #1038
The Singapore government banner is not displayed on the protected message page. Recipients may have legitimacy concerns when landing on this page.
Closes #1038
**Features**:
- Display the banner on the aforementioned page.
**BEFORE**:
**AFTER**:
1. Deploy the change.
2. Open a protected email page and the unsubscribe email page.
3. The Singapore government banner should be displayed at the top of the page.
> feat(frontend): display govt banner on protected and unsubscribe pages

- frontend/src/components/common/rich-text-editor/RichTextEditor.tsx
- frontend/src/components/common/rich-text-editor/utils/Converter.ts
Address two issues:
1. Line breaks not preserved within table cells
2. Not able to insert line break without starting a new paragraph
Closes #1044 
**Bug Fixes**:
- Replaced `\n` with `<br />` when converting to HTML so that line breaks are preserved
- Allow insertion of soft new line without starting a new paragraph when shift + enter is pressed 
**Line breaks in table**
- Create table and enter text with line breaks within
- Send test message and campaign
- Line breaks should be preserved in the table cell
**Insert line break within paragraph**
- Insert a line of text and insert new line with `Shift + Enter`
- Line break should be entered without a new paragraph created
- Repeat and test for each type of block types (`Title`, `Subtitle`, `Header`)
> fix(rich-text): line breaks not preserved and line breaks within blocks

- frontend/src/components/dashboard/campaigns/Campaigns.tsx
- frontend/src/components/dashboard/demo/create-demo-modal/CreateDemoModal.module.scss
- frontend/src/components/dashboard/demo/create-demo-modal/CreateDemoModal.tsx
> Currently, users are able to duplicate demo campaigns if they have remaining campaigns left.
> 
> **Expected behaviour**
> Users should not be able to duplicate demo campaigns at all as we want them to see the "Create demo campaign" modal every time they want to create a demo campaign, so that they can see the demo campaign instructions, how many campaigns they have left for the selected channel, and also the button to the video walkthrough.
Closes #869 
**AFTER**:
- Click on duplicate for SMS and Telegram demo campaigns
- Observe that the selected channel buttons are correct 
- Ensure that a demo campaign is created with the correct campaign name when clicking on `Duplicate demo campaign`
> Improve UX for duplicating demo campaigns

- frontend/src/components/common/rich-text-editor/RichTextEditor.module.scss
- frontend/src/components/common/rich-text-editor/decorators/LinkDecorator.tsx
- frontend/src/styles/app.scss
When linking long links in the rich text editor, the link popover will overflow the textarea and introduced horizontal scroll to the textarea.
Closes #978 
- Use [ReactDOM createPortal](https://reactjs.org/docs/portals.html) to attach the tooltip as a child of html body tag
I chose to attach the popover element to the html body tag instead of the top level rich text editor div as
1. relative and absolute positioning from the text block to popover does not work anymore (since they are not parent-child anymore)
2. We have to calculate the position of the text block relative to the top level rich text editor div in order to set the position of the popover div
3. Hence I felt it was more straightforward to calculate the position of the text block relative to the browser …
> Render rich text link popover in top level html

- frontend/src/components/common/protected-preview/ProtectedPreview.module.scss
Links were of a different font size compared to the normal text in protected preview.
**Bug Fixes**:
- Explicitly apply same font size for links in protected preview
**Before**
**After**
- Create and send protected email with link
- Ensure that font size is the same for both Message B preview and the protected message page
> style: fix font size for links in protected email preview

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/dashboard/create/Create.tsx
- frontend/src/components/dashboard/create/email/EmailCredentials.tsx
- frontend/src/components/dashboard/create/email/EmailRecipients.tsx
- frontend/src/components/dashboard/create/email/EmailSend.tsx
- frontend/src/components/dashboard/create/email/EmailTemplate.tsx
- frontend/src/components/dashboard/create/email/ProtectedEmailRecipients.tsx
- frontend/src/components/dashboard/create/sms/SMSCredentials.tsx
- frontend/src/components/dashboard/create/sms/SMSRecipients.tsx
- frontend/src/components/dashboard/create/sms/SMSSend.tsx
- frontend/src/components/dashboard/create/sms/SMSTemplate.tsx
- frontend/src/components/dashboard/create/telegram/TelegramCredentials.tsx
- frontend/src/components/dashboard/create/telegram/TelegramRecipients.tsx
- frontend/src/components/dashboard/create/telegram/TelegramSend.tsx
- frontend/src/components/dashboard/create/telegram/TelegramTemplate.tsx
- frontend/src/components/protected/Protected.tsx
- frontend/src/components/unsubscribe/Unsubscribe.tsx
We want to install `msw` is a useful dependency for mocking API endpoints during tests. However, `msw` requires TypeScript v4+ while we currently only use v3.9.7.
Reference: https://github.com/mswjs/msw/issues/491
- Upgrade the `typescript` dependency from v3.9.7 to v4.2.3
- Fix a minor compilation error resulting from the upgrade
There are no visual changes.
These tests have been verified locally, but not on the Amplify staging endpoint yet.
1. Compile the app. There should be no errors.
2. Deploy the app on staging.
3. Conduct smoke tests.
4. The app should look and function exactly like before.
Smoke tests:
- Creating and sending email campaign
- Creating and sending SMS campaign
- Creating and sending Telegram campaign
- Creating and sending protected email campaign …
> chore(frontend): upgrade typescript to v4.2.3

- backend/package-lock.json
- backend/package.json
- frontend/package-lock.json
- modules/postman-templating/package-lock.json
- serverless/database-backup/package-lock.json
- serverless/database-backup/package.json
- serverless/redaction-digest/package-lock.json
- serverless/redaction-digest/package.json
- serverless/unsubscribe-digest/package-lock.json
- serverless/unsubscribe-digest/package.json
- serverless/verify-backup/package-lock.json
- serverless/verify-backup/package.json
- worker/package-lock.json
- worker/package.json
| Dependency | From | To |
| :------------ | :-----| :-- |
| y18n | 4.0.0 | 4.0.1 |
| nodemailer | - | 6.5.0 |
| @google-cloud/storage | 5.8.0 | 5.8.1 |
| @google-cloud/secrets-manager | 3.2.0 | 3.5.0 |
- `express-validator`
> chore: upgrade dependencies

- .travis.yml
- serverless/eb-env-update/src/index.ts
We previously refactored the callback lambdas back into the backend server because the lambdas were difficult to test and I was trying to reconsolidate the code.
But the large number of callbacks during a campaign has caused the backend server to become unstable.
This PR deploys the backend server code to separate environments, and changes the restart app lambda so that when env vars are changed, both environments will be restarted.
callback-staging.postman.gov.sg (DONE) or callback.postman.gov.sg
> chore: add callback server

- frontend/src/components/dashboard/campaigns/Campaigns.tsx
- frontend/src/components/dashboard/create/sms/SMSRecipients.tsx
- frontend/src/components/dashboard/create/telegram/TelegramRecipients.tsx
During tests, React logs errors like so:
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
in Campaigns (created by Context.Consumer)
```
This is because some components are calling `setState` or its derivatives even when they are unmounted.
- Check if the components are still mounted before calling `setState`
There are no visual changes.
These tests have been verified locally but not on the staging branch on Amplify.
**The demo and announcement modal should be unchanged**
1. Load the campaigns dashboard.
2. The demo banner, number of demo SMS campaigns, and number of demo Telegram campaigns …
> fix: avoid calling setState when components are unmounted

- frontend/src/components/common/progress-details/ProgressDetails.tsx
- frontend/src/components/dashboard/campaigns/Campaigns.tsx
During tests, there are instances when periodic updates causes errors
due to calling `setState` when the component is unmounted.
Reason:
By default, the Moment component sets a timer on a 60s interval to
update the time shown.
Our time displays are all static so we don't need this feature. Hence, disable it.
This should also slightly improve efficiency since app will do less work.
There are no visual changes.
These tests have been verified on a local dev machine.
**Assert that there are no visual changes:**
1. Deploy the frontend on Amplify.
2. The time display on the Dashboard and on the ProgressDetails pages should appear the same as before.
**Assert that the Dashboard integration tests run without console errors:**
1. Run the Dashboard integration tests in #1110 
2. The tests should …
> fix: disable periodic updates for react-moment components

- backend/src/core/interfaces/campaign.interface.ts
- backend/src/core/services/campaign.service.ts
- backend/src/core/services/upload.service.ts
- backend/src/email/middlewares/email-template.middleware.ts
- backend/src/sms/middlewares/sms-template.middleware.ts
- backend/src/telegram/middlewares/telegram-template.middleware.ts
- frontend/src/components/common/csv-upload/CsvUpload.tsx
- frontend/src/components/common/url-upload/UrlUpload.tsx
- frontend/src/components/custom-hooks/use-upload-recipients.tsx
- frontend/src/components/dashboard/create/email/EmailRecipients.tsx
- frontend/src/components/dashboard/create/sms/SMSRecipients.tsx
- frontend/src/components/dashboard/create/telegram/TelegramRecipients.tsx
- frontend/src/services/upload.service.ts
If an upload has an error during the processing of a vault link, the error is shown on the CSV tab on refresh as we did not persist the bucket name until the upload has been finalised. 
**Features**:
- Introduce `temp_is_vault_link` to track the type of last upload before it finalises
- Clear transient errors (e.g. invalid Vault URL) on selection of a new recipient list type
**Invalid Vault URL**
- Upload an invalid Vault URL.
- An error should be shown
- Switch to CSV as the recipient list type
- The error block should not be shown
**Invalid Vault recipient list**
- Upload a valid Vault URL that references an invalid recipient list (e.g. missing column)
- Error should be shown once processing is interrupted
- Switch to CSV as the recipient list type
- Error should not be shown
**Error …
> feat: store `temp_is_vault_link` before recipient list upload finalises

- backend/Dockerfile
- worker/Dockerfile
A recent change (not sure what) started causing `pip install awscli` to
fail without the python2-dev package. This causes backend and worker
builds on Travis to fail.
Travis build log: https://travis-ci.com/github/opengovsg/postmangovsg/jobs/498665286
- Upgrade to `python3` and remove `py-pip`
- Install `python3-dev` on the backend and worker Docker instances
There are no visual changes.
1. Deploy the change.
2. Ensure that the `backend` and `worker` builds and deployments on Travis, AWS EBS, and AWS ECS succeed.
There are no deploy notes.
There is a prebuilt binary, but it depends on glibc. Our Docker image (Alpine) only includes musl libc, so we can't use the binary as is.
Options:
1. Install glibc ((https://github.com/aws/aws-cli/issues/4685#issuecomment-700923581)) …
> fix(docker/awscli): upgrade to python3 and install python3-dev

- frontend/src/components/common/title-bar/TitleBar.module.scss
- frontend/src/components/dashboard/campaigns/Campaigns.module.scss
- frontend/src/components/dashboard/campaigns/Campaigns.tsx
- frontend/src/components/dashboard/create/duplicate-campaign-modal/DuplicateCampaignModal.tsx
This is a minor design issue I noticed during testing:
A particularly long campaign name causes the dashboard table to overflow its container. This doesn't look very good.
- Only prepend `Copy of` to campaign names which don't already have it (explanation in commit 6a3db9a)
**Bug Fixes**:
- Prevent the dashboard table from overflowing its container
**BEFORE**:
<details>
<summary>Before screenshots</summary>
</details>
**AFTER**:
<details>
<summary>After screenshots</summary>
</details>
**Duplicating a duplicated campaign should not prepend `Copy of` to the campaign's name**
1. Try duplicating a campaign which already has `Copy of` at the start of its name.
2. Assert that the campaign duplication modal does not prepend yet another `Copy of` to the new campaign's name. …
> fix: prevent campaign names from causing dashboard rows to overflow

- backend/src/sms/services/sms-callback.service.ts
Some SMS messages delivery statuses logged contained both the error code and a `SUCCESS` status. This will be confusing to users who see this status in their delivery report and does not provide a conclusive delivery status of the message.
Closes #1126 
**Bug Fixes**:
SMS messages can be delivered in multiple segments when they exceed the character limit of one SMS. Hence each segment has separate deliverability and results in multiple callbacks. In the case where the first segment of the message failed to deliver but the next segment is successful, there will be a situation where the delivery status is overridden to `SUCCESS` but the `errorCode` still remains.
- Update a successful delivery status of a message only if there does not exist a previous Error status 
- Call the …
> Update successful delivery status for sms only if error does not exist

- amplify.yml
- frontend/src/config.ts
- frontend/src/setupTests.ts
- frontend/src/test-utils/api/index.ts
We were experiencing flaky tests as described in issue #1161.
2 issues:
1. Some tests were failing with an error saying that the test exceeded the timeout of 5000ms.
2. The integration tests were written under the assumption that `REACT_APP_ANNOUNCEMENT_ACTIVE != "true"`. However, if it is set to `true`, the integration tests will break due to missing API endpoints and the tests not accounting for the need to dismiss the announcement modal.
Closes #1161
- Increase the timeout of each test to 20s. 10s works fine locally on a MBP 16", but given that CI servers are likely slower, 2x the timeout to be safe.
- Add a dummy API mock for `/settings/announcement-version`
- Disable announcements for tests to enforce the assumption that `REACT_APP_ANNOUNCEMENT_ACTIVE=false`. This is fine because …
> fix(frontend): fix test flakiness

- backend/package-lock.json
- backend/package.json
- frontend/package-lock.json
- frontend/package.json
- package-lock.json
- package.json
- worker/package-lock.json
- worker/package.json
**Features**:
- Allow activation of SNS as a fallback for SMS
- Support whitelisting of domains through a new `agencies` table
- Upgrade worker and backend Docker instances to use Python 3
- Add frontend tests for critical workflows
- Only prepend "Copy of" when a campaign name doesn't already have it
- Upgrade dependencies
**Bug Fixes**:
- Fix parsing of SendGrid email callbacks and disable custom from for SendGrid emails
- Prevent dashboard rows and campaign titles from overflowing
- Update message delivery statuses only if error does not exist
Test frontend tests: #1086
Test campaign title overflow fixes: #1147
Test `agencies` table: #1141
Test SNS fallback: #1019
Test SendGrid fallback: #1026
Test message delivery statuses: #1150
**Frontend tests**
**Campaign title …
> [develop] v1.23.0

- backend/Dockerfile
- backend/tsconfig.json
Deployments for backends were failing after merging #940 because:
1. `tsconfig.build.json` was not copied into the image during Docker build
2. `rootDir` was changed in `backend/tsconfig.json`, this results in a different build directory structure being created. `npm start` fails because `server.js` now resides in `build/src/server.js`.
**Bug Fixes**:
- Copied `tsconfig.build.json` into the Docker image
- Reverted `rootDir` to `./src`. Also reverted `baseUrl` for consistency.
- Deploy this branch and observe that the Elastic Beanstalk deploy succeeds on AWS console
> fix(backend): docker build and tsc output directory structure

- backend/src/telegram/utils/callback/handlers/contact.ts
- backend/src/telegram/utils/callback/handlers/tests/contact.test.ts
Closes issue #1143
**Bug Fixes**:
- Try updating either phone number or telegram ID. If no update occurs, insert a new row.
These tests have been verified on staging.
**Users should be able to update telegram ID for an existing phone number**
1. Change your `telegram_id` to a different number in the `telegram_subscribers` table.
2. Run the `/updatenumber` command on the Telegram bot
3. The bot should say `Your phone number and Telegram ID have been updated.` and `telegram_id` should be updated in the `telegram_subscribers` table.
**Users should be able to update phone number for an existing telegram ID**
1. Change your `phone_number` to a different number in the `telegram_subscribers` table.
2. Run the `/updatenumber` command on the Telegram bot
3.  The bot should say `Your phone number …
> fix: fix error when updating Telegram ID for an existing phone number

- .travis.yml
Closes #1052 
- Create Docker hub account and login in Travis
- Ensure that build and deploy succeed for workers
- `DOCKER_USERNAME` : Docker Hub username
- `DOCKER_PASSWORD` : Docker Hub access token since we enabled 2FA logins
> chore: add docker hub login before worker deploy

- backend/src/test-utils/setup.ts
- serverless/verify-backup/scripts/deploy.sh
- serverless/verify-backup/scripts/run.sh
- serverless/verify-backup/scripts/verify-backup.sh
The google cloud run service for verifying backups has been exceeding 90% of memory utilisation in the past few days.This was alerted to us by the monitoring alarm.
Closes #1176
Investigation on cloud run service memory utilisation - https://docs.google.com/document/d/1BLi_DvhpIhSnC78bhN7kcDYTr056RQ_IKIJwqCQ14OU/edit
- Delete downloaded files and decrypted files after the verify backup is done
- Start and stop postgres service during the request instead of leaving the postgres service running
- Increase memory allocation from 6Gi to 8Gi
This version has been deployed to cloud run production service.
> Improvements to decrease memory usage in verify backup service

- backend/jest.config.js
- backend/src/__mocks__/aws-sdk.ts
- backend/src/__mocks__/telegraf.ts
- backend/src/core/services/credential.service.ts
- backend/src/sms/routes/tests/sms-campaign.routes.test.ts
- backend/src/sms/routes/tests/sms-settings.routes.test.ts
- backend/src/telegram/routes/tests/telegram-campaign.routes.test.ts
- backend/src/telegram/routes/tests/telegram-settings.routes.test.ts
- backend/src/telegram/services/telegram-client.class.ts
- backend/tsconfig.json
Closes [#1167]
- Implements manual mocks for `aws-sdk`, `telegraf`
- Note: Twilio hasn't been mocked because it's not needed here - the SMS tests were mocked at the SMSService level so I don't need to populate SMSTemplates and test the message hydration flow
- `/credentials` and `/new-credentials` endpoint for Telegram and SMS
- `/settings/telegram/credentials` and `/settings/sms/credentials`
> Backend tests for Credentials (Telegram/Twilio)

- .travis.yml
Database backups were timing out.
**Bug fixes**
- Increase timeout to 15 minutes (900s). This is a temporary fix, time required for backup would decrease once I get back to implementing the full redaction from database in #779 
- Run backup lambda on staging and ensure that it works as expected
> chore(backup): increase timeout

- backend/tsconfig.build.json
- backend/tsconfig.json
Closes #1222 
- Clean up `tsconfig.json` and `tsconfig.build.json` to skip building tests and mocks.
- Run `npm run build`
- Check that in build folder, mocks and tests are not built
- Alternatively you can run `npx tsx --showConfig tsconfig.build.json` and check that the files section does not contain any test/mocks.
> build(backend): exclude tests and mocks

- backend/package-lock.json
- backend/package.json
- frontend/package-lock.json
- frontend/package.json
- package-lock.json
- package.json
- shared/package-lock.json
- shared/package.json
- worker/package-lock.json
- worker/package.json
- worker/src/core/loaders/message-worker/email.class.ts
Due to refactoring in #1242 within the `sendMessages` method in `email.class`, email service workers will die if it encounters an invalid email due to an unhandled `throw`
Moved email validation code into a try/catch block
> hotfix: Workers dying due to uncaught invalid email error

- backend/tsconfig.build.json
- backend/tsconfig.json
- frontend/tsconfig.json
- shared/package.json
- worker/tsconfig.json
- Other modules were not correctly referring to the build tsconfig under project references. 
- `tsc --build --clean` command was not referring to the right build tsconfig
- Reference build tsconfig in other modules
- Reference build tsconfig in clean command
- Run `npm run dev` consecutively, error should not occur as the clean command now clears the right file
> fix(shared): clean build and reference build config in other modules

- backend/package-lock.json
- backend/package.json
- backend/src/database/migrations/20210701054329-add-email-error-subtype.js
error_sub_type in #1062 was not created via a migration,
Add migration file
**New scripts**
- Do not run migration. Add the name of this migration file into `sequelize_meta`.
```sql
INSERT INTO sequelize_meta ("name") VALUES('20210701054329-add-email-error-subtype.js');
```
- Verify with `sequelize-cli db:migrate:status` that the new migration is up
**New dev dependencies**
- `sequelize-cli`
> chore: backfill error_sub_type

- shared/src/theme/email-theme.mustache
Text in preheader (a hidden div containing first 200 chars of the body) in the email template gets shown when a user in Outlook clicks the "reply" button
Closes #1251
Add outlook specific styles that hide the preheader text
1. Send email to Outlook (2007-2016) client
2. Reply to email
3. Open reply in another client - preheader text should no longer be shown
> Fix outlook preheader styles

- backend/src/core/utils/from-address.ts
- backend/src/email/routes/tests/email-campaign.routes.test.ts
Sender name with periods need to be quoted. A bug in the older versions of `validator` we were depending on did not enforce this. I am choosing to put in this fix for now to maintain backward compatibility. A better fix but more extensive fix would be to separately store sender name and sender email address, thus giving more flexibility in the formatting for the `from` string.
**Bug Fixes**:
- Manually quote sender name before validation
- Create a new campaign with period in the sender name. E.g. `Postman.gov.sg`. The template should be saved without an error thrown.
> fix(backend): escape sender name before validation

- backend/src/core/models/user/tests/user.test.ts
- backend/src/core/models/user/user.ts
**Note:** Not critical, won't occur in prod once `agencies` table has been populated. See below for details.
Fix for Sequelize Foreign Key error when there is a:
- new user signing up
- with unrecognised Domain (not in domains table)
- AND agencies table does not include default agency (based on name set in env var)
Problem is caused within the `BeforeCreate` hook
1. Creation of the `Domain` is not done in the same transaction as the rest of the hook, including `findOrCreate` for the defaultAgency
2. When defaultAgency does not exist, the agency is created **but not commited**, but returns a value to app layer
3. Because no transaction is specified for the domain creation (with a fkey on the default agency id), by default, sequelize attempts to immediately commit the change
4. However, …
> fix: move domain creation into same transaction

- frontend/src/components/common/email-preview-block/EmailPreviewBlock.module.scss
Fix link previews not having the correct styles
Closes [#1289]
- Used `color: revert` to reset color for a tags
- Added manual overriding `color: blue; text-decoration: underline;` to ensure backwards compat
NA
> fix: reset link styles in html email preview

- frontend/src/components/common/close-button/CloseButton.module.scss
- frontend/src/components/common/close-button/CloseButton.tsx
- frontend/src/components/common/detail-block/DetailBlock.module.scss
- frontend/src/components/common/error-block/ErrorBlock.module.scss
- frontend/src/components/common/info-block/InfoBlock.module.scss
- frontend/src/components/common/warning-block/WarningBlock.module.scss
- frontend/src/components/dashboard/create/Create.module.scss
- frontend/src/components/dashboard/create/email/EmailRecipients.tsx
- frontend/src/components/dashboard/create/sms/SMSRecipients.tsx
- frontend/src/components/dashboard/create/telegram/TelegramRecipients.tsx
- frontend/src/styles/_mixins.scss
- frontend/src/styles/base/_colours.scss
Closes [#1267]
Frontend changes only, see screenshots
**BEFORE**:
**AFTER**:
**BEFORE**
**AFTER**
Changed from italics to underlined blue text so it's more clear
**BEFORE**
**AFTER**
(edited to use Box Icons, changed default color to `inherit`)
**BEFORE**
**AFTER**
> feat(frontend): update minor design system styles

- frontend/src/components/landing/Landing.module.scss
Text wrapping for "messages sent" is off for certain screen sizes (tablet).
**Bug Fixes**:
- Apply margin on the container instead for the message count.
**BEFORE**:
**AFTER**:
- Replace the count to a large number (chrome inspector) and observe that the text wrapping looks normal when in tablet sized screen width
> fix(frontend): text wrapping for messages sent on tablet

- backend/src/core/middlewares/protected.middleware.ts
- backend/src/email/routes/tests/email-campaign.routes.test.ts
Currently, an invalid protected template triggers a `500 Internal Server Error`. This result in false alerts in our monitoring system. Given that this is a result of bad user input, a more appropriate HTTP status code will be `400 Bad Request`.
**Bug Fixes**:
- Return `400 Bad Request` when protected template is invalid (e.g. does not contain `{{protectedlink}}`).
- Attempt to save an invalid protected email template. Note that the status code returned is `400` in Chrome console.
> fix(backend): return `400 Bad Request` on invalid protected template

- frontend/src/classes/EmailCampaign.ts
Currently, the delivery report gives a `null` value under the error column when the status is `READ`. This confuses users as to whether the status is successful.
**Bug Fixes**:
- Provide empty error value if status is `READ`
- Send email campaign and open email. Exported delivery report should show that status is `READ` and error column is emtpy.
> fix: remove error message for read status

- worker/deploy.sh
Closes #1049 
- Set shell script to exit on error and print out command that failed
- Run `ecs-deploy` in parallel to speed up deploy slightly
- Ensure that build and deploy succeed for workers
- Observe that deploys for sender and logger runs in parallel
> chore(worker): parallel ecs deploys and exit deploy script on error

- backend/src/database/migrations/20210831172021-add-index-to-email_messages.js
- backend/src/database/migrations/20210831172027-add-index-to-sms_messages.js
- backend/src/database/migrations/20210831172033-add-index-to-telegram_messages.js
Queries on the messages tables were getting expensive, in particular, for email callbacks. 
The following screenshot shows our performance insights. The select statement used to determine whether to halt a campaign took up most of the time. 
Keewei moved this query to the read replica. To reduce further CPU use, we decided to add indexes on campaign table to each messages table.
Before
After
```
cd backend
npm run build
cd build/database
export DB_URI=.... #tunnel to the remote db
PGSSLMODE=no-verify npx sequelize-cli db:migrate --config config.js
```
Output
```
Using environment "production".
== 20210831172021-add-index-to-email_messages: migrating =======
Executing (default): CREATE INDEX CONCURRENTLY "email_messages_campaign_id" ON "email_messages" ("campaign_id")
== …
```
> fix: add migrations for indices on campaign_id in the messages tables

- .travis.yml
As the database size gets larger, backups were timing out. Since AWS Lambda scales the compute available based on the amount of allocated memory, increasing the memory should make the backup run faster.
- Increase memory for backup lambda
- Deploy backup lambda to staging and ensure that it can run correctly
> fix: increase backup lambda memory permanently

- backend/src/core/loaders/sequelize.loader.ts
- worker/src/core/loaders/message-worker/index.ts
When Aurora Postgres fails over the writer instance, connections are terminated unexpectly.
Add a retry config to sequelize so that failed connections can be retried.
> Add sequelize retry

- serverless/database-backup/examples/event-rds-backup-complete.js
- serverless/database-backup/src/utils/event.ts
After migrating to aurora, 
- the event subscription for running the backup lambda should be changed to:
- the backup complete event code for aurora cluster is `RDS-EVENT-0169` (https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/USER_Events.Messages.html)
Update the event subscription and event code.
> chore: update rds backup event

- .github/workflows/deploy-eb.yml
When deploying to elastic beanstalk with a multiline commit message, the application version description may exceed 200 characters
Set the description to a truncated version of the first line only
> fix: truncate first line of commit for eb

- serverless/eb-env-update/README.md
- serverless/eb-env-update/src/index.ts
The update lambda stopped working when Cloudwatch Events was converted to EventBridge.
1. The CloudTrail event was changed, such that the secret id contains the arn of the secret instead of just the secret name. Random characters are also appended at the end of the secret
2. Our lambda code has to account for the random secrets
1. Update event rule
2. Update lambda code to match excluding the random secret
```
{
"source": ["aws.secretsmanager"],
"detail-type": ["AWS API Call via CloudTrail"],
"detail": {
"eventSource": ["secretsmanager.amazonaws.com"],
"eventName": ["PutSecretValue"],
"requestParameters": {
"secretId": [
{
"prefix": "arn:aws:secretsmanager:<REGION>:<ACCOUNT_ID>:secret:<SECRET_NAME>"
}
]
}
}
}
```
> fix: event for PutSecretValue appends random chars to secret id

- backend/package-lock.json
- frontend/package-lock.json
- frontend/package.json
- package-lock.json
- package.json
- serverless/database-backup/package-lock.json
- serverless/database-backup/package.json
- serverless/eb-env-update/package-lock.json
- serverless/redaction-digest/package-lock.json
- serverless/unsubscribe-digest/package-lock.json
- serverless/verify-backup/package-lock.json
- shared: ✅
- backend: 
- minor audit fix ✅
- pending major breaking upgrade from eslint
- frontend:
- minor audit fix ✅
- pending major breaking upgrades for react-scripts to 5 
- pending node-sass fix but it is going to be replace with `sass` in #1370 
- serverless: ✅
> build(npm-audit): fix audit warnings

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/dashboard/create/common/BodyTemplate/BodyTemplate.tsx
- frontend/src/components/dashboard/create/common/tests/BodyTemplate.test.tsx
Admin users do not have a good sense of how much each SMS will cost. One user had a shock when their bill was significantly higher than expected because they were using either Chinese or Tamil. As a result, the SMS was encoded using UCS-2 instead of GSM-7, and the number of message segments increased significantly.
We can introduce a short SMS segment and cost estimate as such (content TBD - will discuss with Sam and Lisa before turning this into a PR). The cost per message segment was obtained from [Twilio's pricing page](https://www.twilio.com/sms/pricing/sg) and is accurate as of 5 Feb 2022.
**BEFORE**:
**AFTER**:
_Refer to Solution_
_What tests should be run to confirm functionality?_
[TBD - will work on test suite after the UI is confirmed]
- …
> feat: sms cost calculator

- .secrets.baseline
- backend/package-lock.json
- backend/package.json
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/dashboard/create/common/BodyTemplate/BodyTemplate.tsx
- frontend/src/components/dashboard/create/common/tests/BodyTemplate.test.tsx
- package-lock.json
- package.json
- serverless/database-backup/package-lock.json
- serverless/database-backup/package.json
- serverless/eb-env-update/README.md
- serverless/eb-env-update/package-lock.json
- serverless/eb-env-update/src/index.ts
- serverless/redaction-digest/package-lock.json
- serverless/unsubscribe-digest/package-lock.json
- serverless/verify-backup/package-lock.json
- worker/package-lock.json
- worker/package.json
- SMS cost calculator
- npm audit fixes
- update secrets baseline
Refer to https://github.com/opengovsg/postmangovsg/pull/1362
- `sms-segments-calculator` : Library to calculate number of SMS segments and SMS encoding
> Release 1.30.0

- .github/mergify.yml
Closes https://github.com/opengovsg/postmangovsg/issues/1385.
Mergify has already been added to the GitHub organization.
> build(mergify): merge non-major dependabot upgrades

- .github/workflows/ci.yml
- .github/workflows/deploy-eb.yml
- .github/workflows/deploy-worker.yml
- .github/workflows/deploy.serverless.database-backup.yml
- .github/workflows/deploy.serverless.eb-env-update.yml
- .github/workflows/deploy.serverless.redaction-digest.yml
- .github/workflows/deploy.serverless.unsubscribe-digest.yml
This PR modifies the GitHub actions workflow files to deploy `staging` branch to the `staging` environment. 
Closes https://github.com/opengovsg/postmangovsg/issues/1371
> ci: decouple develop branch from staging env

- worker/package-lock.json
- worker/package.json
The PR upgrades most of the vulnerable dependencies in the `worker` subfolder. Done using `npm audit fix`, i.e. minor and patch version upgrades only.
> build: deps upgrade worker folder

- frontend/src/components/common/info-banner/InfoBanner.module.scss
- frontend/src/components/common/info-banner/InfoBanner.tsx
- frontend/src/components/dashboard/Dashboard.tsx
- frontend/src/components/landing/Landing.tsx
- frontend/src/components/landing/banner/Banner.tsx
- frontend/src/components/login/Login.tsx
- frontend/src/config.ts
resolves #1454
Changes:
- info banner fixed on top
https://user-images.githubusercontent.com/12974927/161680637-4349141f-ca50-4edd-8220-4d2d015b2f78.mov
- 3 different color mode for info banner `primary`, `warning`, and `danger` for different kinda messages
" src="https://user-images.githubusercontent.com/12974927/161680689-ee2ba887-659b-4f46-86b9-325594bdd0ca.png">
- simplify info banner to take info from env directly since that's the only it's being used rn
> feat(frontend): make info banner fixed and colorful

- frontend/src/components/landing/Landing.tsx
- frontend/src/types/index.d.ts
Closes https://github.com/opengovsg/postmangovsg/issues/1509
This error has been clogging up the Sentry alerts and #postman-alert on Slack, which might lead to other, more significant errors to be missed. 
Traced the error to the most recent release and looked through PRs that might've caused the error: 
There is only one recent change to the frontend https://github.com/opengovsg/postmangovsg/commit/24f0252e4457720d3b4ff6bec3179a4fbf63db26
Replicated the error on local. 
Instead of using no-non-null-assertion operator, `infoBannerRef.current.style.top` is set conditionally only when `infoBannerRef.current` exists.
Also did miscellaneous refactoring on `Landing.tsx`
> fix TypeError by removing no-non-null-assertion operator in Landing.tsx

- README.md
- backend/.env-example
1. The `mailOptions` point is definitely something that should be noted in the README to facilitate setup.
2. The additional variables I added are based on the `backend/.env` file that @stanleynguyen shared with me (removed the variables in the file where there are already sensible defaults)
3. I'm not very sure whether the `DB_URI` and `DB_READ_REPLICA_UR` changes are only necessary because I'm using Docker, but I had to do this for `npm run dev` to work:
BEFORE:
```
DB_URI="postgres://localhost:5432/postmangovsg_dev"
DB_READ_REPLICA_URI="postgres://localhost:5432/postmangovsg_dev"
```
AFTER:
```
DB_URI="postgres://postgres:postgres@localhost:5432/postmangovsg_dev"
DB_READ_REPLICA_URI="postgres://postgres:postgres@localhost:5432/postmangovsg_dev"
```
> fix: backend/.env-example

- backend/src/core/config.ts
- backend/src/core/services/job.service.ts
- backend/src/email/routes/email-campaign.routes.ts
- deprecating custom send rate for email campaigns
- fix campaign rate to default mail rate at max capacity of our SES system
Fixes https://github.com/opengovsg/postmangovsg/issues/1422
> feat(backend): update send email campaign to only take up 1 worker

- scripts/send-sms-using-sns/README.md
- scripts/send-sms-using-sns/examples/postman_sms_sample.csv
- scripts/send-sms-using-sns/examples/postman_sms_sample_template.txt
- scripts/send-sms-using-sns/index.js
- scripts/send-sms-using-sns/package-lock.json
- scripts/send-sms-using-sns/package.json
This PR adds a backup script to send SMSes via Amazon SNS on a local machine in the event that Twilio goes down.
Closes https://github.com/opengovsg/postmangovsg/issues/1453
Deployment checklist:
> feat: backup send SMS script

- .github/workflows/ci.yml
- .secrets.baseline
- README.md
- package-lock.json
- package.json
Apparently our npm secretlint couldn't catch some of the secrets resulting [this incident](https://github.com/opengovsg/postmangovsg/pull/1538#issuecomment-1138388150).
We tried with the same secret on 3 different alternatives (details included below) and arrived at `detect-secrets`.
Also added some further explanation, versioning pinning, and actionables using `detect-secrets`
> build(detect-secrets): replace secretlint with detect-secrets

- .github/pull_request_template.md
- .github/workflows/ci.yml
- .github/workflows/cypress.yml
- .github/workflows/db-migration.yml
- .github/workflows/deploy-eb.yml
- .github/workflows/deploy-frontend.yml
- .github/workflows/deploy-worker.yml
- .github/workflows/deploy.serverless.database-backup.yml
- .github/workflows/deploy.serverless.eb-env-update.yml
- .github/workflows/deploy.serverless.redaction-digest.yml
- .github/workflows/deploy.serverless.unsubscribe-digest.yml
- .secrets.baseline
- amplify.yml
- backend/package-lock.json
- backend/package.json
- frontend/package-lock.json
- frontend/package.json
- package-lock.json
- package.json
- shared/package-lock.json
- shared/package.json
- worker/package-lock.json
- worker/package.json
We're current having a very tedious deployment process of:
- updating each sub-package's version
- creating a release branch
- create a release tag
- PR and merge the release branch into master (to trigger deploy to prod)
- PR and merge back release branch (with the release commit) to `develop`
Closes #1426 
**TLDR;** New prod deployment process will be a one-step process of [creating a new release](https://github.com/opengovsg/postmangovsg/releases/new) on Github
**More deets**:
- Consolidating the git history for all deployment artefacts to use a single branch `master`.
- `master` will be set to the main branch and `develop` will be removed. All PRs will now target to `master` (Prod deployments won't be triggered on push to `master` anymore)
- To create deployment artefact and trigger …
> ci(deployment): simplify deployment workflow

- .github/workflows/ci.yml
- .github/workflows/deploy-eb.yml
- .github/workflows/deploy-frontend.yml
- .github/workflows/deploy-worker.yml
- .github/workflows/deploy.serverless.database-backup.yml
- .github/workflows/deploy.serverless.eb-env-update.yml
- .github/workflows/deploy.serverless.redaction-digest.yml
- .github/workflows/deploy.serverless.unsubscribe-digest.yml
- .secrets.baseline
Currently multiple deployments can be started at the same time and renders latest deployments failed because infrastructures might be in an `update` state
Set max concurrency for deploy workflows to 1
N/A
> ci(deploy): restrict deployment concurrency to max 1 at a time

- shared/src/theme/email-theme.mustache
Unsub link was not clickable for yahoo mail recipients.
This is because `Mustache.render()` encodes the unsub link when filling in the footer template:
> `please click <a href="{{unsubLink}}">here</a> `
Yahoo mail can't decode the link properly and hence has it greyed out.
Closes [#1645]
Surround the variable with triple brackets so that Mustache does not encode the link.
> `please click <a href="{{{unsubLink}}}">here</a> `
Note: this does not break anything.
Encoding of the link is unnecessary, the embedded Postman link in the footer was not encoded.
> `Powered by <a href="https://postman.gov.sg">Postman</a>`
N/A
> fix: do not encode unsub link

- frontend/src/components/common/rich-text-editor/RichTextEditor.tsx
- frontend/src/components/common/rich-text-editor/utils/Converter.ts
Add indent on tab
Closes #1650 
insert `\t` on tab, converts to 4 white spaces in html.
tab on list items is treated differently to enable nested list
N/A
> feat: indent(4 spaces) on tab

- shared/src/utils/crypto.ts
We expected the [crypto.timingSafeEqual(a,b)](https://nodejs.org/api/crypto.html#cryptotimingsafeequala-b) method to only return a boolean - however, we discovered post-hoc that it also throws an error if the two params are not the same length.
> An error is thrown if a and b have different byte lengths.
This hotfix accounts for that behavior by wrapping the method in a try/catch handler.
> hotfix(sms-callback-auth): catch errors from timingSafeEuqual and eval as not equal

- backend/package-lock.json
- backend/package.json
- backend/src/core/services/job.service.ts
- backend/src/email/utils/callback/query.ts
- backend/src/sms/services/sms-callback.service.ts
Closes https://github.com/opengovsg/postmangovsg/pull/1631
- need to upgrade because there is a security issue (see https://github.com/sequelize/sequelize/issues/14519)
- preliminary assessment: this security issue doesn't affect us since we don't use the replacement
- [sequelize v6.19](https://github.com/sequelize/sequelize/releases/tag/v6.19.0 ) has made typing of `WhereOptions` more stringent, necessitating some fixes
> chore: upgrade sequelize to 6.21.2

- backend/src/email/services/custom-domain.service.ts
- shared/src/utils/from-address.ts
Context: we are trying to add an agency whose domain has been previously verified (but not the exact email address), so that they can send out using a custom domain using this email address
However, the current email verification process verifies the exact email with AWS SES, leading the verification process to fail. This is overly narrow — if the domain has been verified, the verification process should succeed.
Modify the `verifyEmailWithAWS` method to check the domain of the email, and not just the email itself. 
N/A
> fix: email verification can succeed if domain is verified

- frontend/src/components/common/rich-text-editor/RichTextEditor.module.scss
- frontend/src/components/common/rich-text-editor/RichTextEditor.tsx
Bug fixes
Bug 1: list bullet appears on top of preview, preview failed to be hidden before characters are typed
Bug 2: list bullet can't be deleted on backspace if it is the first block
Bug 3: alignment of cursor and preview is off when text-alignment is selected
Bug 1 --> hide preview when block type is not normal text
Bug 2 --> manually handle backspace on empty list bullet on the very top of the content
Bug 3 --> hide preview when text-alignment is not left, changed css style to `display:block` for cursor to align vertically with preview (prevent screen from jumping)
NIL
> fix: editor preview styles

- backend/Dockerfile
- serverless/verify-backup/Dockerfile
- worker/Dockerfile
Upgrade to node16 from node12 in docker images as node 12 is no longer on LTS.
Use public.ecr.aws/docker/library/node:16-alpine
N/A
> chore: upgrade docker to node 16

- cypress.config.js
- cypress/e2e/email.cy.js
- cypress/e2e/email_encrypted.cy.js
- cypress/e2e/sms.cy.js
Cypress test was flaky, can't find DOM elements sometimes
Allow cypress to retry the tests and only fail if all 3 attempts fail.
Note: assertions don't help as methods are alr retrying by default
Cypress test does not check the report generated
load the tracking pixel in gmail to mark email as read
download the report and check for READ status
for sms test, check for SUCCESS status 
This increases the time taken for cypress test to run as we need to wait for the report to be generated.
NIL
> fix: cypress to check report

- backend/src/core/models/unsubscriber.ts
- backend/src/core/services/unsubscriber.service.ts
Currently re-unsubscribe will result in unique constraint error in sql as `findAndCreate` will try to insert again.
Switch to upsert
N/A
> fix(unsub): fix db constraint error because of soft delete

- README.md
- backend/.sequelizerc
Tested commands; works as intended
Another benefit of this PR is, while testing migrations, there is no need to run `npm run build` in order to run the migration with the latest changes.
Actually the `npx sequelize-cli model:generate --name XXX` command is quite useless:
- it generates a `.js` file that is quite different from how the rest of the data models are written. 
- but at least it helps to create a reasonably named migration file (though still need to manually edit the migration file, which is more of a hassle compared to my experience with TypeORM)
One problem I encountered is that, sometimes when I run a migration, if the migration relies on a model that doesn't exist, I need to run `npm run build` before the migration can tun properly.
I feel like this PR is only putting …
> refactor: fix issue with new migration ending up in build folder

- backend/.eslintrc.js
- frontend/.eslintrc.js
- shared/.eslintrc.js
- worker/.eslintrc.js
Noticed this error while on VSCode
This PR makes the error go away. See [here](https://bobbyhadz.com/blog/typescript-parsing-error-cannot-read-file).
> fix: parsing error cannot read tsconfig.json

- customHttp.yml
- frontend/src/locales/en/messages.po
- `for.sg` file links are not showing up in preview
- whitelist `file.for.sg` links 
Tested, works on staging
> feat: whitelist for.sg as allowedImageSources

- backend/package-lock.json
upgrade vm2 version because of vulnerability
> chore: upgrade to vm2@3.9.11 because of security vulnerability

- customHttp.yml
- frontend/src/locales/en/messages.po
Identical to https://github.com/opengovsg/postmangovsg/pull/1776, just for `for.edu.sg` as well
> feat: whitelist for.edu.sg as allowedImageSources

- backend/src/database/migrations/20221005070028-email-messages-transactional-make-from-nullable.js
- backend/src/email/middlewares/email-transactional.middleware.ts
- backend/src/email/models/email-message-transactional.ts
https://sentry.io/organizations/open-government-products-re/issues/3643069534/?project=5272357&referrer=slack
Make the field nullable as it should be
> fix(backend): fix nonnullable from name error in txn email saving

- frontend/src/components/common/nav-bar/NavBar.tsx
Add `Contact Us` link to the navbar
> feat: add contact us link to navbar

- backend/src/core/models/campaign.ts
- backend/src/database/migrations/20210422073013-create-campaigns.js
- backend/src/database/migrations/20210422073931-create-sms-messages.js
- backend/src/database/migrations/20210422081912-create-email-messages.js
- backend/src/database/migrations/20210422082154-create-telegram-messages.js
- backend/src/database/migrations/20210422083045-create-sms-ops.js
- backend/src/database/migrations/20210422083254-create-telegram-ops.js
- backend/src/database/migrations/20210422083258-create-email-ops.js
- backend/src/database/migrations/20220915123536-create-email-messages-transactional.js
- backend/src/database/migrations/20221009141317-change-json-to-jsonb-everywhere.js
- backend/src/email/models/email-message-transactional.ts
- backend/src/email/models/email-message.ts
- backend/src/email/models/email-op.ts
- backend/src/sms/models/sms-message.ts
- backend/src/sms/models/sms-op.ts
- backend/src/telegram/models/telegram-message.ts
- backend/src/telegram/models/telegram-op.ts
I was more exploring why the metadata is stored so weirdly, `{"{\"hash\": \"ebc2628a3fa93f210d783ce645edcaf1\", \"fileName\": \"zx.csv\", \"fileSize\": 31}"}`
But I have since concluded that it doesn't matter since both Sequelize and PostgreSQL recognise and can manipulate the data nicely. As such, this PR is not strictly necessary, but might be good-to-have nonetheless.
This PR converts `attachments_metadata` from `json[]` to `jsonb[]`. 
Some advantages of `jsonb` (basically better processing) from [here](https://stackoverflow.com/questions/22654170/explanation-of-jsonb-introduced-by-postgresql)
E.g. to find all emails with 2 attachments:
```SQL
SELECT *
FROM email_messages_transactional
WHERE array_length(attachments_metadata, 1) = 2;
```
Tested on staging (CI …
> feat: use jsonb instead of json throughout codebase

- backend/src/core/models/user/user.ts
- backend/src/core/services/auth.service.ts
- backend/src/core/services/credential.service.ts
- backend/src/database/migrations/20220914082001-add-format-user-on-insert.js
- backend/src/database/migrations/20221012054742-remove-api-key-column-from-user-table.js
What this PR does:
- Change backend code to write to `api_key_hash` instead of `api_key`
- Drop previously created trigger that syncs `api_key` and `api_key_hash`
- Drop `format_user_on_insert` function and trigger
**Deployment notes**:
1. Deploy backend code 
2. Ensure backend is fully deployed before running db migration
See [here](https://github.com/opengovsg/postmangovsg/pull/1832#pullrequestreview-1136705832) for context
> refactor: api key hash part 2

- backend/src/core/loaders/express.loader.ts
[Ticket](https://www.notion.so/opengov/Combine-log-statements-and-include-cookie-API-key-user-info-82c71a7b32884cdd83e4c9778169f841)
Instead of blacklisting, we will just redact the value of `authorization` header
> feat(backend): show presence of authorization header in request log instead of blacklisting

- backend/src/core/config.ts
- backend/src/core/services/mail.service.ts
- backend/src/database/migrations/20221005075027-add-error-sub-type-to-transactional-email.js
- backend/src/email/interfaces/callback.interface.ts
- backend/src/email/models/email-message-transactional.ts
- backend/src/email/services/email-transactional.service.ts
- backend/src/email/services/email.service.ts
- backend/src/email/utils/callback/parsers/ses.ts
- shared/src/clients/mail-client.class/index.ts
Enable and handle callbacks for status update of transactional emails
Implement transactional callbacks handling on the same endpoint as campaign-sent
- Add `mailConfigurationSet` as a backend env var. 
- For context, we use different AWS SES regions for campaigns (prod: N. Virignia, staging: Frankfurt) and for transactional emails (prod: Sydney, staging: Frankfurt) but they are all named `postman-email-open`.
- We are not distinguishing between the production and staging ones and are using a single env var on the backend (for transactional emails) and a single env var [on the worker](https://github.com/opengovsg/postmangovsg/blob/915f7152a58085d0ba82be61d250e0754897153d/worker/src/core/config.ts#L205) (for campaign emails) to refer to both config sets. This works because they're all …
> feat(backend): handle status callbacks for transactional emails

- backend/src/core/loaders/security-headers.loader.ts
- customHttp.yml
- cypress/e2e/email.cy.js
- cypress/e2e/email_encrypted.cy.js
- cypress/e2e/sms.cy.js
- frontend/src/components/common/confirm-modal/ConfirmModal.tsx
- frontend/src/components/common/feedback-modal/FeedbackModal.module.scss
- frontend/src/components/common/feedback-modal/FeedbackModal.tsx
- frontend/src/components/common/feedback-modal/index.ts
- frontend/src/components/dashboard/create/email/EmailSend.tsx
- frontend/src/components/dashboard/create/sms/SMSSend.tsx
- frontend/src/components/dashboard/create/telegram/TelegramSend.tsx
- frontend/src/components/dashboard/create/util.ts
To enable users to submit feedback via embedded formsg link
- Create new FeedbackModal component to allow more modular use in case any other component needs to embed feedback form in other areas, with url as props
- Built feedbackmodal directly into ConfirmModal instead of the 3 separate campaign triggers, so that the modal logic only needs to be written once
- Control the feedbackmodal behavior with props from confirm modal to reduce dependancy.
> feat(frontend): introduce feedback modal after sending campaign

- backend/src/email/services/email-transactional.service.ts
- backend/src/email/utils/callback/parsers/ses.ts
Use `warn` so it won't clutter up our error logs
We choose to do this (instead of simply disabling these events on AWS) because these events could be helpful if we ever want to get more info that is not shown in our database. (@stanleynguyen is this correct?)
> fix: use logger.warn instead of logger.error for unhandled events

- shared/src/theme/email-theme.mustache
[Ticket](https://www.notion.so/opengov/Postman-footer-not-rendering-properly-on-SGMail-6bb4b499f2e34f67b954e614e63b1682)
- Fundamentally, Microsoft Outlook renders email HTML differently, so hacky workarounds in our mustache template are needed. 
- Proximately, this issue was introduced by [this PR](https://github.com/opengovsg/postmangovsg/pull/1743), specifically this change:
To see the HTML of the email, forward the email to Gmail, click "Show original", change `view=om` to `view=lg`. Now you can save it as a `.html`. [Source](https://webapps.stackexchange.com/a/117154)
Changes made:
- The first change is to add a missing closing `</div>` tag. This was picked up by my IDE though ostensibly it didn't make any difference.
- The second change is to add `height="24"` to the OGP logo …
> fix: logo rendering in footer on SGMail

- frontend/src/components/common/text-input-with-button/TextInputWithButton.module.scss
- frontend/src/components/protected/Protected.tsx
[Ticket](https://www.notion.so/opengov/Bug-on-password-protect-page-491d1060ac2e475f8aa5664a70eac23f)
- Setting font of input field to `16px` explicitly which is the same as the default value (i.e. not affecting anything) to prevent iOS from zooming in
- Scroll to top after protected content is loaded
- Reset zoom to 1 after protected content is loaded
- N/A
> fix(frontend): fix auto-scrolling of protected page

- .secrets.baseline
- backend/src/core/constants.ts
- backend/src/core/middlewares/auth.middleware.ts
- backend/src/core/routes/auth.routes.ts
- backend/src/core/routes/campaign.routes.ts
- backend/src/core/routes/index.ts
- backend/src/core/routes/list.routes.ts
- backend/src/core/routes/protected.routes.ts
- backend/src/core/routes/settings.routes.ts
- backend/src/core/routes/stats.routes.ts
- backend/src/core/routes/unsubscriber.routes.ts
- backend/src/email/routes/email-callback.routes.ts
- backend/src/email/routes/email-campaign.routes.ts
- backend/src/email/routes/email-settings.routes.ts
- backend/src/sms/routes/sms-callback.routes.ts
- backend/src/sms/routes/sms-campaign.routes.ts
- backend/src/sms/routes/sms-settings.routes.ts
- backend/src/telegram/routes/telegram-callback.routes.ts
- backend/src/telegram/routes/telegram-campaign.routes.ts
- backend/src/telegram/routes/telegram-settings.routes.ts
[Ticket](https://www.notion.so/opengov/Revise-cookie-API-authentication-1fcff2fca43d425a9e735350f5734e0e)
- Make auth middleware modular
- Restrict non-API-exposed endpoints to be cookie-only
- Remove non-API-exposed from our published swagger doc
- N/A
> refactor(backend): revise authentication for endpoints

- backend/src/core/constants.ts
- backend/src/core/middlewares/campaign.middleware.ts
- backend/src/core/routes/campaign.routes.ts
- backend/src/core/routes/tests/campaign.routes.test.ts
- backend/src/core/services/campaign.service.ts
- backend/src/email/interfaces/email.interface.ts
- backend/src/email/middlewares/email-transactional.middleware.ts
- backend/src/email/routes/email-settings.routes.ts
- backend/src/email/routes/email-transactional.routes.ts
- backend/src/email/routes/tests/email-transactional.routes.test.ts
- backend/src/email/services/email-transactional.service.ts
- backend/src/sms/routes/sms-transactional.routes.ts
[Ticket](https://www.notion.so/opengov/Implement-list-transactional-messages-endpoint-610554e007ef4e84ad23bd1a30ceb9a1)
The general strategy I have adopted is to:
- Apply validation at the routes level using `celebrate`
- Convert the validated query params into type-safe arguments in the middleware layer
- Pass these arguments to `EmailTransactionalService`, which uses sequelize to retrieve the requested data
**Implementation Notes:**
- For extensibility, instead of passing in `created_at` directly, I have transformed it into a `TimestampFilter` that could be extended to filter by other timestamps
- I considered whether to build `sortBy` in such a way that allow for concurrent sorts in the future, but seeing as that is not in spec and it's unclear whether our API users need it (compared …
> feat: list email messages endpoint

- backend/src/core/loaders/express.loader.ts
- backend/src/core/middlewares/campaign.middleware.ts
- backend/src/core/models/campaign.ts
- backend/src/core/routes/campaign.routes.ts
- backend/src/core/services/campaign.service.ts
- backend/src/database/migrations/20221208074426-add-should-campaign-should-bcc.js
- backend/src/email/services/email.service.ts
- frontend/src/classes/EmailCampaign.ts
- frontend/src/components/dashboard/campaigns/Campaigns.tsx
- frontend/src/components/dashboard/create/email/EmailRecipients.tsx
- frontend/src/components/dashboard/create/email/EmailTemplate.tsx
- frontend/src/components/dashboard/create/sms/SMSRecipients.tsx
- frontend/src/services/campaign.service.ts
- shared/src/clients/mail-client.class/index.ts
- shared/src/clients/mail-client.class/interfaces.ts
- worker/src/core/loaders/message-worker/email.class.ts
Closes [Ticket](https://www.notion.so/opengov/BCC-on-Postman-852b225df35a42b2bb034eaf38efd2c6)
Implement it duh
**Some extra notes**: This PR was implemented with future "bcc to anyone" possibility in mind, hence going through the hoop of putting `bcc` inside the params. However, we haven't handled bounces and other notifications that are related to the bcc instead of the main email properly yet but for now since it's only `bcc`-ed to the main user email, we can perhaps live with this
> feat: bcc campaign messages to author

- backend/src/email/utils/callback/parsers/ses.ts
[Ticket](https://www.notion.so/opengov/Discuss-account-suppression-list-and-blacklist-cd1e0863ceda46c288a1dcd4df4bd708)
Exclude `not-spam` complaints from blacklist
- N/A
> fix(backend): exclude not-spam complainer from blacklist

- backend/src/core/services/file-extensions.service.ts
- docs/supported-file-types.md
the library file-type we use currently does not accept cfb file types because these file types are old formats of Microsoft (.doc, .xls, .ppt) can be weaponized and exploited for malicious usecases. more on this [here](https://www.decalage.info/en/book/export/html/55).
the team decided to disallow cfb file types for 2 reasons:
keeping our system more secure by avoiding highly exploitable file types
aligning our practices with go.gov.sg which we intend to transit over our attachments in the longer run
list of cfb file types that we will not support:
.doc - Microsoft Word 97-2003 Document
.xls - Microsoft Excel 97-2003 Document
.ppt - Microsoft PowerPoint97-2003 Document
> docs(api): removed .doc, .ppt, .xls from attachment file types supported

- backend/src/sms/routes/sms-campaign.routes.ts
- backend/src/telegram/routes/telegram-campaign.routes.ts
Slight problem with Joi validator that caused Scheduled Sending to fail on SMS and Telegram Campaigns
Allow scheduledTiming as an optional field
> feat(backend): minor validation to pass scheduledTiming field

- frontend/src/locales/en/messages.po
We are releasing Schedule Send on 27 Dec 2022 and this will be communicated to our users via our announcement modal on postman.gov.sg
pending items
> announcement: schedule send (draft)

- backend/openapi.yaml
- backend/src/email/middlewares/email-transactional.middleware.ts
- backend/src/email/routes/tests/email-transactional.routes.test.ts
Miscellaneous refactoring while working on transactional SMS saving:
- Save one db roundtrip
- Remove unnecessary err handling
- Move db call up to make `acceptedAt` time more accurate
- Update schema in `openapi.yml` file: fix formatting + add explanation for enums
- Use `reply_to` instead of `replyTo` in returned JSON
> refactor: email transactional middleware

- backend/openapi.yaml
- backend/src/core/models/initialize-models.ts
- backend/src/core/services/credential.service.ts
- backend/src/database/migrations/20221214101846-create-sms-message-transactional.js
- backend/src/sms/middlewares/sms-transactional.middleware.ts
- backend/src/sms/middlewares/sms.middleware.ts
- backend/src/sms/models/index.ts
- backend/src/sms/models/sms-message-transactional.ts
- backend/src/sms/routes/sms-campaign.routes.ts
- backend/src/sms/routes/sms-settings.routes.ts
- backend/src/sms/routes/sms-transactional.routes.ts
- backend/src/sms/routes/tests/sms-transactional.routes.test.ts
- backend/src/sms/services/sms-transactional.service.ts
[Ticket](https://www.notion.so/opengov/fd466213f133486d85e4117f1ded521d?v=052d3609255c4dfcb2cf173aae7f7c5d&p=5114247758dd4f08997924f32e9f99c3&pm=s)
[RFC](https://www.notion.so/opengov/2022-12-13-RFC-for-Saving-SMSes-Sent-via-API-1eefc5346aae48d996786ae04ad57437)
Reviewers, please read the RFC + review the implementation.
Remaining tasks are:
Deployment notes:
> feat: save transactional sms

- backend/openapi.yaml
The OpenAPI spec yaml for Postman fails validation by openapi-generator:
```
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
| Error count: 9, Warning count: 0
Errors: 
-attribute components.schemas.SMSCampaign.items is not of type `object`
-paths.'/campaign/{campaignId}/email/retry'. Declared path parameter campaignId needs to be defined as a path parameter in path or operation level
-paths.'/campaign/{campaignId}/telegram/retry'. Declared path parameter campaignId needs to be defined as a path parameter in path or operation level
-paths.'/campaign/{campaignId}/telegram/stop'. Declared path parameter campaignId needs to be …
```
> fix(openapi): correct validation errors

- backend/src/core/loaders/swagger.loader.ts
The OpenAPI spec is not readily served by api.postman.gov.sg. Consumers may retrieve it via GitHub, but this results in generated code with GitHub and not Postman as base URL. In some cases, this is hard-coded and cannot be easily changed.
Serve the spec as a JSON at `/v1/swagger.json`, to allow consumption by code generators and similar utilities
> feat(openapi): expose spec at `/v1/swagger.json`

- .gitignore
- backend/src/core/services/file-attachment.service.ts
- backend/src/email/routes/tests/email-transactional.routes.test.ts
- backend/src/email/services/email-transactional.service.ts
- shared/src/clients/mail-client.class/interfaces.ts
- shared/src/templating/xss-options.ts
[Ticket](https://www.notion.so/opengov/Content-ID-images-3624a41d30224e569db710c71b2b0c2e)
Support [CID images](https://sendgrid.com/blog/embedding-images-emails-facts/)
- Figure out + document :
- Relax xss filtering rules are to allow CID img tags to be passed through
- Include a `cid` field for **all** attachments uploaded based on its index (0, 1, 2, 3...) and passing it to [Nodemailer](https://nodemailer.com/message/attachments/). 
^In theory, this causes a change to the email's content-disposition, per [Nodemailer's API documentation](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ba7447ad38c4f69cf4f8d23fc4660fb2e3303700/types/nodemailer/lib/mailer/index.d.ts#L40-L58):
> using `cid` sets the default `contentDisposition` to 'inline' and moves the attachment into a …
> feat: content-id image support

- backend/src/core/loaders/express.loader.ts
- backend/src/core/middlewares/file-attachment.middleware.ts
- backend/src/core/utils/attachment.ts
We previously modified the code to redact attachment data in the log to ensure our logs will be reasonably sized. However, the modification assumes that the `req.body.attachments` field will be an array, which is not the case.
Have created an utility function `ensureAttachmentsFieldIsArray` to use in both part of the codebase that does what it says.
> fix: attachment array bug

- backend/openapi.yaml
- backend/src/email/middlewares/email.middleware.ts
- backend/src/email/routes/email-transactional.routes.ts
- backend/src/email/routes/tests/email-campaign.routes.test.ts
- backend/src/email/routes/tests/email-transactional.routes.test.ts
We are getting a lot of potential users on our transactional email API who are (understandably) filling up the `from` field wrongly. (See latest on #postman-alerts channel)
Closes https://github.com/opengovsg/postmangovsg/issues/1837 too
- Give them a more informative error message. 
- Check against `email-from-address` table first before allowing sending
This PR introduces one more database call in the code path of our transactional email API. Actually, the set of users in the `email-from-address` table is quite small and we can put a cache in front of it if we want to optimise in the future.
> feat: better error message for unverified custom from address

- backend/src/database/migrations/20230125083046-convert-tx-sms-body-datatype.js
- backend/src/sms/models/sms-message-transactional.ts
Previously, `DataType.String` defaults to 255 chars, which may be too short.
Related:
- https://stackoverflow.com/questions/4848964/difference-between-text-and-varchar-character-varying
- https://dba.stackexchange.com/questions/189876/size-limit-of-character-varying-postgresql
Use `DataType.Text` instead
Backend code unchanged
> fix: use DataType.Text for sms transactional body

- .github/workflows/cypress.yml
- .github/workflows/deploy-eb.yml
- .github/workflows/deploy-frontend.yml
- .github/workflows/deploy-worker.yml
- .github/workflows/non-serverless-deploy.yml
- .secrets.baseline
[Ticket](https://www.notion.so/opengov/Postman-CI-CD-E2E-Rolling-Back-Was-Canary-RFC-ee42f3356a264cdf8832649bb988b569)
As stated in the ticket's comment.
To be followed up with another PR for notifying on Slack on build successes & failures
> build(actions): revert application version upon e2e failure

- .secrets.baseline
- backend/src/core/config.ts
- backend/src/core/middlewares/auth.middleware.ts
- backend/src/core/models/user/user.ts
- backend/src/core/services/auth.service.ts
- backend/src/database/migrations/20230215073856-create-rate-limit-column-in-users-table.js
- backend/src/email/middlewares/email-transactional.middleware.ts
- backend/src/email/routes/tests/email-transactional.routes.test.ts
See [ticket](https://www.notion.so/opengov/Rate-limit-for-tx-email-API-b6f4eb2a755d45e3a91fa557d6ac87c9?pvs=4) 
Todos:
> feat: user-specific rate limit for tx email API

- backend/src/email/middlewares/email-transactional.middleware.ts
- backend/src/email/routes/email-transactional.routes.ts
- backend/src/email/routes/tests/email-transactional.routes.test.ts
- Previously, rate-limited emails are sent to database. This is a problem as we scale up as it means even rate-limited emails are causing db writes. This issue is thankfully flagged by @stanleynguyen prior to our upcoming big deployment.
- Move rate-limit up, so that it precedes writing to database
- Remove tests that checks that rate-limited emails have been written to db
N/A just deploy only
> feat: rate limited emails should not be saved to db

- .github/workflows/non-serverless-deploy.yml
- Currently, Cypress test is flaky and, combined with the reversion after failure, is causing dev issues
- We also discovered the Cypress test coverage is less than we expected (something to fix soon)
- We will be temporarily disabling the Cypress test until we fix the flakiness. We should have a subsequent PR to fix the coverage issue too.
> fix: remove cypress test temporarily

- backend/src/database/migrations/20230301104113-recreate-log-job-email-fn.js
Campaigns were stuck because the `log_job_email` function is looking for the `message_id` column, which was removed in an [earlier PR](https://github.com/opengovsg/postmangovsg/pull/1880). 
Fixed by creating a new `log_job_email` that does not look for the `message_id`.
> fix: `log_job_email` fn

- backend/src/core/services/auth.service.ts
- backend/src/email/services/email.service.ts
- shared/src/clients/mail-client.class/index.ts
Task:
https://www.notion.so/opengov/Ensure-AWS-SES-message_id-are-logged-with-table-primary-key-ID-03254019c59f4a6d92af62a11043c6fc
- Message AWS SES ID written to CloudWatch Logs alongside "native" message ID (i.e. DB table primary key value).
- Tested in staging (both campaign and tx).
- [Wrote guide on how to resolve AWS SES ID from native message ID.](https://www.notion.so/opengov/Resolving-AWS-SES-ID-from-Native-Message-ID-c6d47be3edcf433daf1bc8cd66b69c05)
- Confirmed both log groups have sufficient retention (currently infinite).
> chore: log channel provider message id to aid debugging

- backend/src/core/services/auth.service.ts
resolves [ticket](https://www.notion.so/opengov/Update-API-authentication-middleware-to-use-api_keys-table-874cbd2343c34aad85fe20883e205eef?pvs=4)
included
- rewrote logic flow to move all sad path above
- find the key from api key table, then find in user that has that api key
> feat: use api key table api records instead

- backend/package-lock.json
- backend/package.json
- serverless/redaction-digest/package-lock.json
- serverless/redaction-digest/package.json
- serverless/redaction-digest/src/index.ts
- serverless/redaction-digest/src/redaction.ts
- serverless/unsubscribe-digest/package-lock.json
- serverless/unsubscribe-digest/package.json
- worker/package-lock.json
- worker/package.json
Upgrading dependencies based on Snyk security warnings
To-dos:
- Per [this PR](https://github.com/opengovsg/postmangovsg/pull/1952#issuecomment-1459615158):
- End-to-end tests will automatically run tx email API 
- Cypress tests will no longer run automatically
If all goes well, then merge this in
> build(deps): upgrade snyk security vuln

- .github/workflows/non-serverless-deploy.yml
- backend/src/core/interfaces/settings.interface.ts
- backend/src/core/middlewares/settings.middleware.ts
- backend/src/core/services/api-key.service.ts
- backend/src/core/services/auth.service.ts
- backend/src/core/services/credential.service.ts
As per [ticket](https://www.notion.so/opengov/Update-GET-settings-endpoint-to-use-api_keys-bf0496d0131442378542aa7b8afd83fc?pvs=4)
1. The primary logic of updating existing GET settings endpoint to return the has_api_key flag based on data from api_keys table instead of users table
2. Refactoring of previous change [here](https://github.com/opengovsg/postmangovsg/pull/1953) to use a general service method instead of writing it directly into function, to accommodate future changes with the conditions in case of API key deactivation / expiry
> feat: update get settings endpoint

- backend/src/core/middlewares/api-key.middleware.ts
- backend/src/core/routes/api-key.routes.ts
- backend/src/core/routes/tests/api-key.routes.test.ts
- backend/src/core/services/api-key.service.ts
As per [ticket](https://www.notion.so/opengov/List-API-keys-endpoint-af0d9d82748b4c38bdd4f3fca5a5bf64?pvs=4)
Included in this PR:
- Building on previous PR after middleware and services are initiated
- Creating a new endpoint with api key routing to decouple from user settings
- Implement API Key list endpoint, sorted by created date DESC, only accessible by cookie
- Test cases for this use case
> feat: added endpoint to get api key list

- backend/src/core/models/user/api-key.ts
- backend/src/core/routes/tests/api-key.routes.test.ts
- backend/src/database/migrations/20230322044351-append-delete-at-api-key.js
As per [slack discussion](https://opengovproducts.slack.com/archives/C049QPXT27M/p1679459330284049?thread_ts=1679389658.985529&cid=C049QPXT27M)
- Migration file to add deleteAt column
- Paranoid: true on api_keys model 
- Updating of existing test cases to test soft delete
Deployment Checklist
> feat: support soft delete for api key

- amplify.yml
AML2 image (default image of amplify) doesn't have the underlying required glibc version to run node 18
- Remove repo-wide requirement to use node 18 (i.e. removing .nvmrc in root)
- Force use node v16 in amplify
> fix(amplify): use node version 16

- .secrets.baseline
- backend/src/core/config.ts
- backend/src/database/seeders/20210422101939-add-default-credentials.js
- backend/src/telegram/middlewares/telegram.middleware.ts
- backend/src/telegram/routes/tests/telegram-campaign.routes.test.ts
- backend/src/telegram/routes/tests/telegram-settings.routes.test.ts
- backend/src/telegram/services/telegram-callback.service.ts
- backend/src/test-utils/test-env.ts
- worker/src/core/config.ts
Under the latest optimization #1968 , `NODE_ENV` is defaulted to `production` so that we only install production node_modules and also signal to node engines to carry out [optimizations](https://nodejs.dev/en/learn/nodejs-the-difference-between-development-and-production/) (and we want to have this in staging as well for env parity).
However, some of our application code relies on this `ENV` for business logic.
Switching to use `APP_ENV` instead of `NODE_ENV`
**Note**: We don't switch these for serverless functions (e.g. redaction-digest, and unsubscribe-digest) as env vars these are set manually through GHA and the performance improvement is probably insignificant
_Any tasks that need to be done on the environment before releasing of this PR (e.g. Setting environment variables, running …
> refactor(config): use APP_ENV instead of NODE_ENV

- worker/src/core/services/notification.service.ts
As per [ticket](https://www.notion.so/opengov/Fix-notification-email-copy-on-Schedule-Send-91b3894f61904c88a77ef550f113f516?pvs=4)
Simple fix to remove the `scheduled` word off the e-mail.
> hotfix: remove the word scheduled

- backend/src/core/middlewares/campaign.middleware.ts
- backend/src/core/middlewares/job.middleware.ts
- backend/src/core/services/job.service.ts
A recently reported bug in [thread](https://opengovproducts.slack.com/archives/CT8D1FESY/p1680242246348529), that affects specifically two types of campaigns.
1. Scheduled campaigns
2. Campaigns sent out that are queued due to high load
After queueing the jobs, if the user decides to abandon the campaign and deletes the entire campaign, the relevant job_queues were not cleaned up as expected.
- When deleting campaigns, also delete any relevant job_queue entities tied to it
- Rename cancelScheduledCampaigns to cancelJobQueues to make it more intuitive
> hotfix: also delete queued jobs when deleting campaign

- backend/src/core/services/campaign.service.ts
- frontend/src/classes/Campaign.ts
[Ticket](https://www.notion.so/opengov/Campaign-list-table-showing-incorrect-status-for-SCHEDULED-campaigns-250dba9218d34b19adce13877a30e894?pvs=4) and [Ticket](https://www.notion.so/opengov/Fix-Scheduled-Sending-Sent-At-UI-b9f543197e9c4bf0b955405d2e065d35?pvs=4)
- return missing `visible_at` from backend for listing campaign
- recalculate `sentAt` on the frontend based on whether campaign is a scheduled one
> fix(frontend): correct sentAt ts and status for scheduled campaigns

- backend/src/core/middlewares/api-key.middleware.ts
- backend/src/core/routes/api-key.routes.ts
- backend/src/core/routes/index.ts
- backend/src/core/routes/tests/api-key.routes.test.ts
- backend/src/core/services/api-key.service.ts
- backend/src/core/services/credential.service.ts
[Ticket](https://www.notion.so/opengov/Generate-API-key-endpoint-39e2e9a06c7f44e083599e06fc4c8abe?pvs=4)
Implement the endpoint.
> feat(backend): add endpoint to generate new api key

- .github/workflows/non-serverless-deploy.yml
- e2e/tests/email-transactional.test.ts
Test txm emails don't arrive fast enough at our test mailbox smh, rendering our test time-out
Considering that we might have an async model for sending out txn emails (i.e. non-guaranteed delivery latency), let's remove the check for email to stabilise our test case
> test(e2e): remove email check from txn email test

- frontend/src/components/dashboard/create/email/EmailDetail.tsx
- frontend/src/components/dashboard/create/sms/SMSDetail.tsx
- frontend/src/components/dashboard/create/telegram/TelegramDetail.tsx
[Ticket](https://www.notion.so/opengov/Incorrect-waitTime-estimation-for-scheduled-campaign-89b5ff2d44bd4f7bb3433c81601d2588?pvs=4)
This solution simply moves the check for schedule sending up top, as scheduled messages do not directly 'join the sending queue', so the wait time logic is not applicable to scheduled campaigns. 
Another uglier solution considered was to change the wait time conditional to `campaign.status !== Status.Scheduled && stats.waitTime && stats.waitTime > 0`.
> hotfix: priotise showing reschedule header for scheduled campaigns

- backend/.platform/nginx/conf.d/client_max_body_size.conf
- backend/openapi.yaml
- backend/src/core/config.ts
- backend/src/core/middlewares/file-attachment.middleware.ts
- backend/src/email/routes/email-transactional.routes.ts
- backend/src/email/routes/tests/email-transactional.routes.test.ts
[Ticket](https://www.notion.so/opengov/Coordinate-change-in-attachment-number-and-attachment-size-13ba040a5f5942b38f8219867e96a6bc)
In this PR:
- Increase number of attachments to 10 (from 5)
- Set a global file attachment limit to 10MB
- Increase Beanstalk's nginx `client_max_body_size` to 11MB (this makes sense since max body size is 1MB + 10MB of attachments → in practice, unlikely to hit this precise limit, user will see our custom error message instead)
> feat: new attachment limits setup

- .github/workflows/ci.yml
- .github/workflows/deploy-eb.yml
- .github/workflows/deploy-frontend.yml
- .github/workflows/deploy-worker.yml
- .github/workflows/deploy.serverless.eb-env-update.yml
- .github/workflows/non-serverless-deploy.yml
Get rid of warnings in GitHub Actions. 
For more info on changes made:
- `setup-node`, `einaregilsson/beanstalk-deploy` and `configure-aws-credential`: [here](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12)
- [`set-output`](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
Did not update:
- Lambda functions because they will be refactored away
- `db-migration.yml` workflow (not sure about the status, doesn't seem to be in use) @stanleynguyen 
- Warnings from ECS task definitions
- If I understand the setup properly, our GitHub Actions are pulling the task definitions from ECS and then using to deploy the new image
- However, in doing so, it is actually pulling fields …
> build(ci): update deprecated GitHub Actions dependencies

- frontend/src/components/common/export-recipients/ExportRecipients.tsx
- shared/src/theme/email-theme.mustache
The standard "A Singapore Government Agency Website" banner at the top of usual Govt websites has Government with a capital G. 
Changed "government" to "Government" for consistency. Looks more legitimate too. 
Nil
> change 'government' to 'Government' in email template

- backend/src/core/errors/transactional.errors.ts
- backend/src/sms/middlewares/sms-transactional.middleware.ts
- backend/src/sms/routes/tests/sms-transactional.routes.test.ts
- shared/src/clients/twilio-client.class/errors.ts
- shared/src/clients/twilio-client.class/index.ts
[Incident on Sentry](https://open-government-products-re.sentry.io/issues/4032341530/)
Fix: throw 429 error when rate limit is hit
> fix: handle RateLimitError on tx SMS endpoint properly

- backend/src/core/loaders/swagger.loader.ts
I want to expose the `openapi.yaml` file directly so that I can read it directly from the GitBook guide and expose the API methods.
See screenshot for more info:
Currently, the domain is wrong
Serve the file statically by adding another loader in Express
UPDATE: not sure why, GitBook is able to [pick this up](https://raw.githubusercontent.com/opengovsg/postmangovsg/master/backend/openapi.yaml), but [not this](https://api-staging.postman.gov.sg/openapi.yaml). Going to open a customer support ticket with GitBook
UPDATE 2: turns out to be a CORS issue, have fixed with the second commit.
> docs: serve openapi.yaml statically

- backend/openapi.yaml
- backend/src/core/loaders/express.loader.ts
- backend/src/core/services/auth.service.ts
- backend/src/core/services/upload.service.ts
- backend/src/email/routes/tests/email-transactional.routes.test.ts
- frontend/src/services/validate-csv.service.ts
- Typos 
- Removing errors that are named wrongly
Related [context](https://opengovproducts.slack.com/archives/C049QPXT27M/p1678160932860389) 
**Background**
- Before we implemented the `body-parser` properly, an API request that is too large will result in a 500 error.
- After that is implemented, the same request would result in a 400 error. 
- However, we have decided to retain the 10x multiplier so that the error message is informative:
Error message with 10x multiplier (so that Joi validation kicks in):
Error message without 10x multiplier:
> refactor: errors, unnecessary code, typos etc.

- backend/src/database/migrations/20230512043333-fix-insert-jobs-scheduled-timezone.js
Our `Send Now` feature is not working in local with the campaign always being marked as scheduled for a later time, however, this feature is working fine in our prod.
It is because : Currently, our `insert_jobs` function is casting the received string value for `scheduled_time` to `timestamp`, which doesn't account in timezone information in the string and hence defaulting to UTC time => This results in it working in our prod as our prod application's locale is UTC while not working in local as local application's local is not UTC
Update the `insert_jobs` db function
> fix(backend): account for timezone in insert_jobs function

- frontend/src/components/dashboard/create/util.ts
Replace form link with a go.gov.sg link so that updating forms is easier in the future.
> Update feedback form URL

- backend/src/core/config.ts
- backend/src/core/services/phonebook.service.ts
- shared/package-lock.json
- shared/package.json
- shared/src/clients/phonebook-client.class/index.ts
- worker/src/core/config.ts
in this release: 
- Introduce a new client service to connect with phonebook and make it reusable between worker & backend. 
- changes that are not invoked at the moment, simply to break down further PRs
- kill switch on worker side to make sure we can halt any phonebook related functionality even after job has been queued.
To note:
- There are some older configs used by phonebook v1. They will be removed once we have deprecated the older functionalities that reference these configs
- The older configs are duplicates of newer ones, but now we keep the naming consistent and renamed them to be more intuitive. 
- There is no kill switch in backend as we can control the display on the client side.
Before deployment
> feat: Introducing phonebook service to modularize worker & backend usage

- amplify.yml
- frontend/src/services/attachment.service.ts
We need to have a way to use a custom image server URL if needed
Add an extra env var for frontend with fallback on BACKEND_URL
> fix(frontend): allow overriding of image server url

- backend/src/core/config.ts
- backend/src/core/middlewares/file-attachment.middleware.ts
- backend/src/email/routes/email-transactional.routes.ts
- backend/src/email/routes/tests/email-transactional.routes.test.ts
takeaway from today's meeting with customer:
- they might need to send >10 attachments
- from our perspective, costs are based on total file size of attachments; as such, as long as cumulative file size applies, we can remove "2MB per file" and "10 attachments max" limit]
to-do:
^@stanleynguyen dk whether there is value in making these part of the e2e tests...
> feat: remove attachment per file size and max number limit

- backend/src/core/services/file-attachment.service.ts
- backend/src/email/routes/tests/email-transactional.routes.test.ts
- backend/src/email/services/email-transactional.service.ts
- shared/src/templating/template-client.ts
[issue](https://opengovproducts.slack.com/archives/CT8D1FESY/p1688463934513269)
Including `cid` field in attachments that are not meant to be content-id images has negatively impacted how such emails are rendered on iOS's Mail app. This code change is intended to mitigate this problem
Deployment notes: N/A
> feat: insert `cid` field in attachments conditionally

- backend/src/database/migrations/20230705102914-index-sms-transactional-message-id-column.js
- backend/src/sms/models/sms-message-transactional.ts
[Issue](https://opengovproducts.slack.com/archives/C015VQQ3HMG/p1688552733333679?thread_ts=1688542528.385169&cid=C015VQQ3HMG)
Solution: create index concurrently
Deployment notes:
> fix: index message_id column of transactional SMS

- backend/src/core/services/auth.service.ts
- e2e/global-setup.ts
- e2e/gmail-check.ts
3.2.0 Add Email OTP to email subject line - P1
Closes [SGC-153](https://linear.app/ogp/issue/SGC-153/320-add-email-otp-to-email-subject-line-p1)
Please refer to commit.
N/A
> feat(backend): include OTP in OTP email subject

- backend/src/email/middlewares/email-transactional.middleware.ts
- backend/src/email/routes/email-transactional.routes.ts
- backend/src/email/routes/tests/email-transactional.routes.test.ts
- backend/src/email/services/email-transactional.service.ts
[Ticket](https://opengovproducts.slack.com/archives/CT8D1FESY/p1689148321589049)
Deployment notes: N/A
Usage notes: if there is spacing in the tag (e.g. `hello world`), the query parameter should replace it with `%20` instead. E.g. `/transactional/email?tag=hello%world`
> feat: increase list email to 1000 and search by tag

- sst/packages/core/src/util/email.ts
- sst/stacks/MyStack.ts
sending to blacklisted recipient (e.g. officer has left service) should not throw error
> fix: handle blacklisted recipient in SST

- backend/src/database/migrations/20230803032719-add-user-clicked-at-to-govsg-verification.js
- backend/src/govsg/models/govsg-verification.ts
- backend/src/govsg/services/govsg-callback.service.ts
In this PR, we add a `user_clicked_at` column to the `govsg_verification` table. Doing so gives us an additional metric to track on our Grafana dashboard. 
Each time our whatsapp webhook receives a button click event, it will update the `user_clicked_at` value for the correct entry in the `govsg_verification` table.
> refactor: add userClickedAt column to govsg_verification

- backend/src/govsg/services/govsg-callback.service.ts
This PR serves as a potential fix to our webhook taking up to several minutes to receive a `delivered` message status update.
Being too easy with returning HTTP 400 can lead to a snowball of retries from Meta's end, slowing down our own resources.
> refactor: make webhook server return 200 instead of 400

- backend/src/govsg/middlewares/govsg-verification.middleware.ts
- backend/src/govsg/routes/govsg-campaign.routes.ts
- frontend/src/components/dashboard/create/govsg/GovsgMessages.tsx
Postman users need a way to search through Govsg messages by recipient name or recipient mobile number.
Closes [SGC-174](https://linear.app/ogp/issue/SGC-174/implement-search-by-recipient-name-or-mobile-number)
- Allow the `listMessages` middleware that sits behind `/messages` (full path: `/campaign/${campaignId}/govsg/messages`) to accept a search query parameter.
- Run the search.
- If the search term contains only 1 to 10 digits, search by mobile number. Else, search by recipient name.
- I should explore if I can hand this over to the ORM through the use of an OR operation.
We should pull `recipient_name` out into its own column in `govsg_messages` since we are searching by this field. I will checkout this branch and create the necessary migration there.
> feat: allow searching Govsg messages by recipient name or mobile number

- backend/src/govsg/middlewares/govsg-callback.middleware.ts
- shared/src/clients/whatsapp-client.class/errors.ts
- remove unused UnexpectedWebhookError
- make `isAuthenticated` middleware function in `GovsgCallbackMiddleware` return HTTP 200
> chore: remove unused UnexpectedWebhookError and disable webhook retry for errors that don't need it

- backend/package-lock.json
- backend/package.json
- backend/src/govsg/models/govsg-template-access.ts
- backend/src/scripts/whitelisting/constants.ts
- backend/src/scripts/whitelisting/get_all_templates.ts
- backend/src/scripts/whitelisting/get_template_access.ts
- backend/src/scripts/whitelisting/update_whitelist.ts
- backend/src/scripts/whitelisting/whitelist_users.ts
In this PR, I add new whitelisting scripts to facilitate having different groups for WhatsApp templates. 
Closes [SGC-180](https://linear.app/ogp/issue/SGC-180/wa-templates-will-be-grouped-into-3-categories)
Instead of handling the implementation for grouping templates at the DB level, we've decided that we can do it from the whitelisting scripts. Doing this gives us the added benefit of not having to change any of the query parameters/data model in the system. 
I've added 4 new whitelisting scripts. A detailed description of each script can be found in their respective files. 
1. `get_template_access.ts`
2. `get_all_templates.ts`
3. `update_whitelist.ts`
4. `whitelist_users.ts`
**New dev dependencies**:
- `@json2csv/plainjs` : used to create csv files
**No further deployment steps need …
> feat: add whitelisting scripts

- frontend/src/components/common/LoadingSpinner/LoadingSpinner.module.scss
- frontend/src/components/common/LoadingSpinner/LoadingSpinner.tsx
- frontend/src/components/dashboard/create/govsg/GovsgMessages.tsx
Before this PR, there would be an initial flicker from `renderNoMatch()` -> `renderGovsgMessage()` because we had no loading spinner for this component.
Now, we have it.
Closes [SGC-184](https://linear.app/ogp/issue/SGC-184/fix-flicker-between-empty-dashboard-and-list-of-messages)
Note: For now, it is ok to rapidly switch from `renderNoMatch()` -> `renderGovsgMessage()` during search. This is because we don't want the search bar to become a `LoadingSpinner` on key down.
> fix: remove initial flicker when showing Gov.sg messages

- backend/src/govsg/services/govsg.service.ts
- frontend/src/components/dashboard/create/govsg/GovsgRecipients.tsx
If we allow each recipient in a campaign to receive multiple messages as a result of multi-lingual capabilities, there will be increased complexity in ensuring all such messages have the same OTP.
As such, we want to ensure each campaign contains unique recipients only. Each recipient can only receive 1 message in whichever language specified for the recipient.
Closes [SGC-181](https://linear.app/ogp/issue/SGC-181/de-dupe-recipient-column-in-postman-for-govsg-channel-only)
- Update `GovsgService.uploadCompleteOnChunk` to additionally check for duplicate recipients and throw an error if so.
- Update the warning message in the frontend so that users are informed that `We do not allow duplicate recipients in Gov.sg campaigns`.
> feat: Dedupe recipients for Gov.sg campaigns

- backend/src/govsg/services/govsg-callback.service.ts
Reverts opengovsg/postmangovsg#2144
The "delivered" status update webhook requests have been "missing" since last Thursday/Friday, leading to absence of officer verification message(s).
This commit was found to have caused the issue. It is currently unknown why but I propose to revert this first.
Impact of reverting: We'll see Sentry errors on this type error, but it's acceptable for now.
> Revert "fix: TypeError: Cannot read properties of undefined (reading 'userId')"

- frontend/src/components/common/CampaignHeaderTabs/CampaignHeaderTabs.module.scss
- frontend/src/components/common/CampaignHeaderTabs/CampaignHeaderTabs.tsx
When hovering over tabs in CampaignHeaderTabs, the cursor was not set, so it becomes unclear if the tabs are clickable.
Closes [SGC-187](https://linear.app/ogp/issue/SGC-187/use-cursor-pointer-for-report-messages-tabs)
CSS
> style: set cursor to pointer when hovering over tabs in CampaignHeaderTabs

- backend/src/govsg/middlewares/govsg-template.middleware.ts
- backend/src/govsg/services/govsg-template.service.ts
- backend/src/govsg/services/govsg.service.ts
- frontend/src/components/dashboard/create/govsg/GovsgRecipients.tsx
- Merge #2155 first. Remember to switch base to `master`.
- Only users with access to the GOVSGV feature can enjoy this feature.
Enable multi-lingual templates for bulk send too.
Closes [SGC-189](https://linear.app/ogp/issue/SGC-189/support-multi-lingual-messages-in-bulk-send)
> feat: enable multi-lingual support for bulk send

- frontend/src/components/common/ChipGroup/LanguageChipGroup.tsx
- frontend/src/components/dashboard/create/govsg/GovsgPickTemplate.tsx
- frontend/src/components/dashboard/create/govsg/GovsgSingleRecipient.tsx
Before this PR, we either show 0 or 4 language chips and radio options.
We should show them based on the actual languages supported by the template.
Closes [SGC-188](https://linear.app/ogp/issue/SGC-188/show-only-language-chips-which-the-template-has)
> feat: smart lang chips

- backend/src/govsg/services/govsg.service.ts
- frontend/src/components/dashboard/create/govsg/GovsgPickTemplate.tsx
- frontend/src/components/dashboard/create/govsg/GovsgSingleRecipient.tsx
- frontend/src/components/dashboard/create/govsg/RadioChoice.tsx
This length check was originally needed because we show either 0 or 4 lang chips. Now, we check the `languages` array to know what to render.
The values passed around have changed a bit due to this refactor. This commit handles the aftermath that was previously undetected.
With the current set of PRs, coming back to an existing Draft campaign and selecting the language will lead to a crash because I did not make `getCampaignDetails` return `code` instead of `language_code`.
`rest.checked && children` alone is not enough to say there is at least 1 child in the array. This is because `[]` is truthy. Added a length check. Kudos to @KishenKumarrrrr for catching this.
> fix: bug fixes for multi-lingual feature

- backend/src/govsg/middlewares/govsg-verification.middleware.ts
- backend/src/govsg/utils/recipient.ts
The Resend button uses client 2 all the time.
Closes [SGC-191](https://linear.app/ogp/issue/SGC-191/resend-causes-two-govsg-threads-in-prod)
Remove whitespaces and prepend +countrycode to phone numbers when using the `getApiClientId` query.
Don't merge today. Merge on Friday.
> fix: fetch correct client

- backend/src/govsg/middlewares/govsg-verification.middleware.ts
- frontend/src/components/dashboard/create/govsg/GovsgSingleRecipient.tsx
- frontend/src/services/govsg.service.ts
Two problems:
In bulk send, the param field name for language code is `language`. Refer to the sample csv file. But in single send, the param field name for language code is `languageCode`.
Not ideal because the govsg messages frontend table will show `language` for bulk send and `languageCode` for single send. Plus, in the db, `params` has both snake case (e.g. `officer_name` ) and camel case (e.g. `languageCode`) field names.
This PR standardises the param field name for language code to just `language`.
Why:
- Leaving the code as-is would give a poor UX. I put in a small amount of time to see if I could expand the height of the table row but I have not been successful yet.
- Poor UX: Table row is too squeezy for showing the language, see screenshot
- Original screen does not have this. …
> refactor: rename and hide language param

- frontend/src/components/common/sample-csv/SampleCsv.tsx
- frontend/src/components/dashboard/create/govsg/GovsgRecipients.tsx
Closes [SGC-197](https://linear.app/ogp/issue/SGC-197/set-default-language-in-bulk-send-csv-to-english)
Create an optional `defaultParams` prop for `SampleCsv`.
> feat: allow user-specified default params in sample csv

- backend/src/govsg/middlewares/govsg-verification.middleware.ts
We want to hide the passcode from the govt officer until the MOP clicks/taps the `Create passcode` button.
Closes [SGC-192](https://linear.app/ogp/issue/SGC-192/hide-passcode-from-officer-until-user-clicks-create-passcode)
> feat: hide passcode until MOP clicks

- frontend/src/components/common/action-button/ResendButton.tsx
- frontend/src/components/dashboard/create/govsg/GovsgMessages.tsx
We want to disable to Resend button when the pre-call notification message has not reached the recipient's phone. We also add a tooltip to explain why the button was disabled.
Closes [SGC-194](https://linear.app/ogp/issue/SGC-194/disable-resend-button-when-msg-not-delivered-with-tooltip-explaining)
> feat: disable resend until delivered

- backend/src/core/services/stats.service.ts
When a `Gov.sg` whatsapp campaign is sent, the total messages displayed on the `Report` tab will always be 0. 
Closes [SGC-172](https://linear.app/ogp/issue/SGC-172/fix-0-instead-of-1-messages-sent)
WhatsApp messages make use of a `delivered` column in the DB that was excluded from the `getNumRecipients` function. I have ensured that the `delivered` variable gets used in the calculation.
**BEFORE**:
**AFTER**:
N/A
> fix: statistics table bug for govsg

- frontend/src/components/dashboard/create/govsg/GovsgMessages.tsx
We should debounce search so that we don't over-search (e.g. user might still be typing).
For everything else i.e. first render, handle page change, we don't debounce because there is no change to search input.
> feat: debounce search govsg messages

- backend/src/govsg/services/govsg-callback.service.ts
When we encounter a problem with the WhatsApp webhook, it can be difficult to debug because we do not always log the request parameters. 
I made sure that the logs for the `govsg-callback` service either include the request body or the `messageId` of the request.
N/A
> refactor(govsg-callback.service.ts): improve logging in file

- backend/src/email/utils/callback/parsers/ses.ts
We switched to using only events from SNS instead of native events from SES. There's a discrepancy which is the prior one uses `eventType` field name while the latter uses `notiticationType`
Use both fields to determine the notification type in blacklisting
- N/A
> fix(backend): account message.eventType for blacklisting emails

- backend/src/govsg/middlewares/govsg-verification.middleware.ts
- backend/src/govsg/services/govsg.service.ts
- frontend/src/components/common/action-button/ResendButton.tsx
- frontend/src/components/dashboard/create/govsg/GovsgMessages.tsx
- frontend/src/styles/app.scss
We should run passcode functionality and show passcode only if the message template is a pre-call template.
Closes [SGC-213](https://linear.app/ogp/issue/SGC-213/add-missed-call-and-house-visit-templates)
> (PR 2) fix: create passcode only if using precall template

- backend/src/govsg/middlewares/govsg-verification.middleware.ts
- backend/src/govsg/routes/govsg-campaign.routes.ts
- backend/src/govsg/services/govsg-callback.service.ts
- backend/src/govsg/services/govsg-verification-service.ts
- backend/src/govsg/services/govsg.service.ts
- frontend/src/components/common/action-button/ResendButton.tsx
- frontend/src/components/dashboard/create/govsg/GovsgMessages.tsx
- frontend/src/components/dashboard/create/govsg/GovsgRecipients.tsx
- frontend/src/components/dashboard/create/govsg/GovsgSingleRecipient.tsx
Closes [SGC-215](https://linear.app/ogp/issue/SGC-215/remove-officer-verification-button)
https://drive.google.com/drive/folders/1JkFGh_SSYBMIm9F_YtXxdCCBxiCDl7xp?usp=sharing
- cursor not set to pointer when hovering over Click to reveal passcode. Will address this in a separate PR.
- The template name should not mention `OTP` at all. Should be something along the lines of "with officer verification". Will rename when populating templates to production.
> (PR 4) feat: replace passcode button with passcode in first message

- backend/src/govsg/middlewares/govsg-verification.middleware.ts
- backend/src/govsg/routes/govsg-campaign.routes.ts
- backend/src/govsg/services/govsg-callback.service.ts
- frontend/src/components/common/StyledText/PasscodeBadge.module.scss
- frontend/src/components/common/StyledText/PasscodeBadge.tsx
- frontend/src/components/dashboard/create/govsg/GovsgMessages.tsx
We want to track officer's usage of passcode. We do this by prompting them to Click to reveal passcode.
Closes [SGC-214](https://linear.app/ogp/issue/SGC-214/make-passcode-click-to-reveal-and-log-click-events)
And [SGC-215](https://linear.app/ogp/issue/SGC-215/remove-officer-verification-button) (see #2189)
- Leveraging the `details` HTML element ([docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details))
cursor not set to pointer when hovering over Click to reveal. This will be done in a separate PR.
> (PR 3) feat: implement click to reveal passcode

- frontend/src/components/dashboard/create/govsg/GovsgPickTemplate.tsx
This is all my idea. But please let me know if this isn't the way.
> refactor: sort template order in frontend

- frontend/src/components/common/StyledText/PasscodeBadge.tsx
- frontend/src/components/dashboard/create/govsg/GovsgMessages.tsx
- (BUG) The passcode badge component is being reused i.e. reveal first row = first rows in subsequent pages are also revealed already.
Add `key` attribute to the `details` element in `PasscodeBadge` ([docs](https://legacy.reactjs.org/docs/lists-and-keys.html#keys)).
> fix: add key attribute to details element

- backend/src/govsg/services/govsg.service.ts
We want to reject invalid language values, instead of falling back to English.
Closes [SGC-221](https://linear.app/ogp/issue/SGC-221/reject-misspelt-language)
This PR is backward-compatible.
If the language column is entirely absent (like how it is supposed to be right now), we fall back to English.
On the other hand, if a language is specified, then it has to be valid.
> feat: reject invalid language

- worker/src/core/config.ts
- worker/src/core/loaders/message-worker/index.ts
Alert on GovSG campaign with errored messages
Check if there're errored messages for a campaign at the finalize step in logger worker
> feat(worker): implement alert for campaign with errors

- backend/src/govsg/middlewares/govsg-verification.middleware.ts
Because the first click to passcode reveal updates the db, the order of records might change.
I've observed instances where I revealed the passcode of one record in page 1, and it got moved to page 2.
> fix: do not reorder after passcode reveal

- frontend/src/components/common/StyledText/PasscodeBadge.module.scss
> style: make Click to reveal more prominent

- frontend/src/components/dashboard/create/govsg/GovsgRecipients.tsx
- frontend/src/components/dashboard/create/govsg/GovsgSingleRecipient.tsx
When user moves from the "Pick a template" to "Upload recipients tab", the window scroll is preserved.
This is especially bad UX when "Pick a template" and "One recipient" is selected, because the "One recipient" tab is long, so it starts at the very bottom, and hence the user has to scroll all the way to the top to start the form. 
1. View after completing "Pick a template" tab, then user will click "Next"
2. View after user clicks "Next" - he looks at the bottom of the page since window scroll is preserved. Intuitively, the tab should start at the top.
> feat: scroll to top on recipient step for better UX

- backend/src/core/services/credential.service.ts
- backend/src/database/migrations/20230906063204-add-partial-index-to-user-credentials.js
- backend/src/sms/middlewares/sms.middleware.ts
This PR is a follow up to https://github.com/opengovsg/postmangovsg/pull/2212
This PR addresses two problems:
1. The DB allows duplicate values for the `cred_name` column in the `user_credentials` table. Even though we don't expect the `uuid` values to collide, in the event that they do, we will run into the "hash collision" problem again. 
2. When new credentials are added, we perform an `upsert` to AWS Secrets Manager. The original purpose of this was to save space in Secrets Manager but the implementation is incorrect. In the event that a set of credentials already exist, we do not want to update the existing value. 
The following solutions are provided for the 2 problems above:
1. We add a partial index that ensures that all values of `cred_name` are unique if the value of …
> feat: add partial index to user credentials table

- backend/src/govsg/middlewares/govsg-verification.middleware.ts
We previously fixed normalising recipient before querying flamingo for which WA client id to use.
But, resend failed because recipient in templateMessageToSend is not normalised.
> fix: use normalised recipient in templateMessageToSend

- backend/src/email/services/email-transactional.service.ts
- backend/src/email/utils/callback/parsers/ses.ts
- backend/src/email/utils/callback/query.ts
Email messages might have the wrong delivery status reflected due to a bug on Postman. This bug came about because upon receiving a delivery notification, we did not check whether or not the notification was related to our main recipient of the email before updating the DB table. This resulted in a race condition where delivery notifications to the main recipient and the BCCed individuals would result in the wrong status being displayed in the postman UI and report. 
An example scenario is given below:
1) A record is created in the `email_messages` table with `messageID = 1`
1) Email to the main recipient hard bounced. AWS SES replies with a `Bounce` status. The `status=Hard Bounce` is reflected in the DB for `messageID = 1`
2) AWS SES replies with a `Delivery` status when the BCCed …
> fix: email bcc bug

- backend/src/govsg/services/govsg-callback.service.ts
We've been throwing type errors due to `contacts` being `undefined`.
This observation contradicts [Meta's docs](https://developers.facebook.com/docs/whatsapp/on-premises/reference/contacts/) but this is not the first observed contradiction.
Also, the same information that we want is available in the form of `body.messages[0].from` already.
As such, we simply read `body.messages[0].from` instead of `contacts`.
> fix: get waid from messages instead of contacts

- backend/src/email/utils/callback/parsers/ses.ts
There is a bug in postman where when callbacks are processed, we blacklist the recipient of the email instead of the emails in the `bouncedRecipients` field of the `Bounce` object.  [AWS docs](https://docs.aws.amazon.com/ses/latest/dg/event-publishing-retrieving-sns-contents.html)
Due to the introduction of the `CC` and `BCC` feature, this method of blacklisting emails is incorrect. (e.g if an email to a `CCed` user bounces, the recipient is blacklisted instead)
I modified the way we retrieve blacklisted users to make of the `bouncedRecipients` field.
N/A
> fix: blacklisting bug

- backend/src/govsg/middlewares/govsg-verification.middleware.ts
- backend/src/govsg/routes/govsg-campaign.routes.ts
- frontend/src/components/common/StyledText/PasscodeBadge.module.scss
- frontend/src/components/common/StyledText/PasscodeBadge.tsx
- frontend/src/components/dashboard/create/govsg/GovsgMessages.tsx
As requested by Paul and users
- Removing the `user_clicked_at` column
> feat: remove click to reveal

- backend/src/core/config.ts
We no longer need the `SGID_VALID_DOMAINS` env var so we can remove it.
> refactor: remove .env value

- backend/Dockerfile
- backend/src/core/config.ts
- backend/src/core/services/mail.service.ts
- backend/src/email/middlewares/email-transactional.middleware.ts
- backend/src/email/routes/email-transactional.routes.ts
- backend/src/email/routes/tests/email-transactional.routes.test.ts
- backend/src/email/services/email-transactional.service.ts
- shared/src/clients/mail-client.class/index.ts
- worker/Dockerfile
AWS SES includes a 1x1 tracking pixel to detect whether or not a user has opened/read an email.  GSIBs block this tracking pixel which causes it to appear as a little red X at the bottom of emails. This makes the emails appear suspicious.
In this PR, I add a feature to enable transactional email users to turn off this tracking feature via a new `disable_tracking` flag. This would prevent this issue from popping up. 
The events that are tracked by SES is determined by the configuration set that SES uses when sending out the email. This configuration set is determined by the value of the `X-SES-CONFIGURATION-SET` header. Configuration sets are defined via the AWS console. 
I've added an additional configuration set (`postman-email-no-tracking`) to `ap-southeast-2` that does not include …
> feat: disable tracking in transactional email

- backend/src/core/middlewares/auth.middleware.ts
- backend/src/core/services/auth.service.ts
Since Feb 8 2024, the `POST /login/sgid` endpoint is called twice whenever a user attempts to log in via a GSIB device. One of the API calls is made without `req.session.sgid` set and thus fails in the BE and results in a HTTP 500 being returned. 
However, this HTTP 500 does not affect the user's ability to log in and is not reflected in the network tab of the developer console as well. Thus, the impact of this issue is low. Instead of returning a HTTP 500, we are choosing to downgrade the error to a HTTP 400 instead to reflect the seriousness of the issue. 
Our current hypothesis is that this second call is made by SIS instead of our FE due to `*.postman.gov.sg` being whitelisted on SGProxy but the SGID URL having to go through SIS. The emergence of this issue also nicely corresponds to …
> refactor: bad sgid session returns 400 instead of 500

- amplify.yml
Attachments broke when I performed the DNS migration to the legacy site. I think this is because we are injecting an ENV var at build time in amplify. This PR should fix it 🙏
> fix: email attachments

- backend/src/email/routes/email-transactional.routes.ts
In this PR, I modify the validation for the transactional email endpoint such that it rejects emails that contain UTF8 characters with a HTTP 400. In the current implementation, we allow for emails with UTF8 characters. However, these email addresses are ultimately rejected by AWS SES which result in a HTTP 500 being thrown from the transactional email endpoint. Since AWS SES currently does not support UTF8 characters in the local part of emails and there are no workarounds, the only option we have is to gracefully reject these email addresses.
> fix: reject utf8 emails in transactional endpoint

- backend/src/database/migrations/20241101014358-email-messages-aggregation-index.js
- backend/src/database/migrations/20241101015340-remove-email-messages-campaign_id_indx.js
This PR is part of my solution for the aggregation problem. The current explain plan hints at some inefficiencies where we are filtering through many rows in order to derive the result we need. My hypothesis is that this would perform significantly better if we add a proper index to allow efficient filtering of `status` and `error_code`. In this PR, I add the relevant index for this.
> feat: add migration files for index

- backend/package-lock.json
- backend/package.json
- shared/src/tracing.ts
This PR is a continuation of #2282 . The purpose of turning on profiling is for us to collect some concrete data on what the exact bottleneck is during callbacks so we don't succumb to premature optimisation. 
There is a risk that turning this feature on in production would be detrimental to the application performance. As such, I am only doing so for 20% of all our servers.
> feat: add profiler

- .github/workflows/e2e.yml
Github actions is deprecating `actions/upload-artifact@v3`. In this PR I ensure that we use `v4`.
> chore: update github actions/upload-artifact to v4

- backend/src/email/utils/callback/parsers/ses.ts
- shared/src/tracing.ts
This PR is a continuation of #2283. The profile from the latest callback spike indicates that the logging statement in the callback flow is introducing a significant bottleneck to our processing. This could be explained by the log statement that attempts to log out the entire record that is returned to us by SNS. 
In this PR, I avoid logging out the entire record in an attempt to remove the above-mentioned bottleneck. Additionally, I also set `dbmPropagationMode: 'full'` in our tracers so that we can retrieve explain plans of the SQL statements we are executing in the future. Based on the traces, the DB query is the next potential bottleneck in the execution and generating data on its performance will allow us to optimise in the future.
> chore: remove record log and turn on dbm propagation

- backend/src/email/middlewares/email-callback.middleware.ts
- backend/src/email/routes/email-callback.routes.ts
- backend/src/email/services/email-callback.service.ts
- backend/src/email/services/email-transactional.service.ts
- backend/src/email/utils/callback/parsers/ses.ts
This PR is a continuation of #2285. After previously removing the logging of the entire record objects, the ELB 502s during callback spikes continued to occur. While trying to debug the issue further, we realised that the existing traces in DD did not contain sufficient information.
In this PR, I manually add custom spans to the callback endpoint that we are interested in so that we can hopefully better understand where the bottlenecks in this endpoint lie.
💡 The newly created spans are still a little wonky. My guess is that this is due to the implementation of this endpoint where there are many overlapping asynchronous operations being executed at the same time.
> feat: custom spans

- backend/src/database/migrations/20240812063204-add-user-id-index-to-email-messages-transactional.js
In this PR, I add a `user_id` indx to `email_messages_transactional`. Currently, the list messages endpoint is performing a sequential scan that regularly takes > 30s. This is causing client calls to timeout. Thus, by adding this index, we hope to improve the performance of this endpoint.
> feat: add user_id indx to email_messages_transactional
