opengovsg/postmangovsg

- backend/src/email/middlewares/email-template.middleware.ts
- backend/src/email/middlewares/email.middleware.ts
- backend/src/email/routes/email-campaign.routes.ts
- backend/src/sms/routes/sms-campaign.routes.ts
- frontend/src/components/dashboard/create/email/EmailCredentials.tsx
- frontend/src/components/dashboard/create/email/EmailRecipients.tsx
- Limit who the VAPT testers can send messages to
- Limit their send rate
- Limit number of messages in a campaign
> VAPT: Configuring limits for testers

- .travis.yml
- serverless/log-twilio-callback/package-lock.json
- serverless/log-twilio-callback/package.json
- serverless/log-twilio-callback/src/config.ts
- serverless/log-twilio-callback/src/index.ts
- serverless/log-twilio-callback/src/sequelize-loader.ts
- worker/src/core/config.ts
- worker/src/sms/services/twilio-client.class.ts
Make minor adjustments before release
- Use environment specific variables in travis
- Use sequelize prepared statements
- Use convict for managing config, to be consistent with the rest
> chore: update feature/twilio-callback

- amplify.yml
CSP headers that would allow Google Analytics to load and be called were missing
Add missing headers
> chore: add csp headers for ga

- backend/src/core/services/s3-client.class.ts
> [develop] fix: catch s3 error

- backend/package-lock.json
- backend/package.json
- backend/src/email/middlewares/email.middleware.ts
- backend/src/sms/middlewares/sms.middleware.ts
- frontend/package-lock.json
- frontend/package.json
- package-lock.json
- package.json
- worker/package-lock.json
- worker/package.json
An [IDOR](https://cheatsheetseries.owasp.org/cheatsheets/Insecure_Direct_Object_Reference_Prevention_Cheat_Sheet.html) security vulnerability has been discovered where users are able to make API calls by masquerading as other users. 
**Bug Fixes**:
There was a missing `await` in our `isEmailCampaignOwnedByUser` middleware. Awaiting the function call fixes this.
> Release v1.5.1

- frontend/src/components/common/file-input/FileInput.module.scss
- frontend/src/components/common/progress-pane/ProgressPane.module.scss
- frontend/src/components/dashboard/campaigns/Campaigns.tsx
- frontend/src/components/dashboard/create/Create.module.scss
- frontend/src/components/dashboard/create/email/EmailTemplate.module.scss
- frontend/src/components/dashboard/create/email/EmailTemplate.tsx
- frontend/src/components/dashboard/create/sms/SMSCredentials.tsx
- frontend/src/components/dashboard/settings/api-key/ApiKey.tsx
- frontend/src/styles/_variables.scss
Minor frontend UI inconsistencies.
- Standardize padding of buttons and labels
- Improve wording for API key regeneration
> chore: UI tweaks

- backend/src/core/constants.ts
- backend/src/core/loaders/sequelize.loader.ts
- backend/src/email/models/email-blacklist.ts
- backend/src/email/models/email-message.ts
- backend/src/email/models/email-op.ts
- backend/src/email/models/index.ts
- backend/src/sms/models/sms-message.ts
- backend/src/sms/models/sms-op.ts
// Insert code to alter table and create enums
> Add models for email blacklist

- backend/src/core/models/statistic.ts
- backend/src/email/models/email-op.ts
- backend/src/sms/models/sms-op.ts
- worker/src/core/loaders/message-worker/sms.class.ts
- worker/src/email/resources/sql/enqueue-messages-email.sql
Adding various fixes after testing the status branch.
```
CREATE TYPE enum_email_messages_status AS ENUM ('SENDING', 'ERROR', 'SUCCESS', 'INVALID_RECIPIENT');
CREATE TYPE enum_sms_messages_status AS ENUM ('SENDING', 'ERROR', 'SUCCESS', 'INVALID_RECIPIENT');
ALTER TABLE email_messages ADD COLUMN status enum_email_messages_status;
ALTER TABLE sms_messages ADD COLUMN status enum_sms_messages_status;
ALTER TABLE statistics ADD COLUMN statistics int4;
```
> Add fixes to status branch

- backend/src/core/services/campaign.service.ts
- backend/src/core/services/stats.service.ts
- backend/src/email/middlewares/email-template.middleware.ts
- backend/src/sms/middlewares/sms-template.middleware.ts
Unsent count = 0 on enqueue since update_stats during sendCampaign has been removed.
Move updating of unsent count to uploading of csv.
> Set unsent count on upload

- serverless/log-twilio-callback/src/config.ts
- serverless/log-twilio-callback/src/index.ts
- serverless/log-twilio-callback/src/sequelize-loader.ts
Update status in sms_messages with the lambda. #400 should go in first.
> chore: update status in sms_messages

- README.md
Added documentation on how to cut a new release based on what was shown during sync up. Let me know if I got anything wrong.
> chore: Add docs on how to create a new release

- amplify.yml
- backend/package-lock.json
- backend/package.json
- frontend/package-lock.json
- frontend/package.json
- package-lock.json
- package.json
- worker/package-lock.json
- worker/package.json
Update amplify for new account
> Release v1.7.1

- backend/package-lock.json
- backend/package.json
- frontend/package-lock.json
- frontend/package.json
- package-lock.json
- package.json
- worker/package-lock.json
- worker/package.json
- IE11 support
- Apply styling to boxicon `i` elements only
- Update guide links for GitBook
- Automatic input and button disabling when executing async functions
- Use environments in sentry backend
> [develop] Release v1.7.2

- amplify.yml
Update environment variables in the frontend.
> chore: Update frontend env vars for Telegram deployment

- backend/package-lock.json
- backend/package.json
- frontend/package-lock.json
- frontend/package.json
- package-lock.json
- package.json
- worker/package-lock.json
- worker/package.json
* **Halt campaign**
* Stop a campaign when a threshold number of emails have bounced, and this number also exceeds a certain percentage of emails.
* Display the halt status on frontend
* **Download invalid recipients**
* Use a read replica db to query as we do not want to overwhelm master db
* Implement endpoint to retrieve recipients for a campaign with invalid or error message delivery status
* Display invalid recipients download link on campaigns page and SMSDetail, EmailDetail page
* Resend OTP button disappears after user tries to login with an invalid OTP.
* `DB_READ_REPLICA_URI`: URI for read replica db
**New database changes**
* Add halt column:  `ALTER TABLE “campaigns” ADD COLUMN “halted” BOOLEAN NOT NULL DEFAULT false;`
> [develop] 1.8.0

- backend/src/telegram/services/telegram.service.ts
- serverless/telegram-handler/src/bot/handlers/contact.ts
A collection of small fixes for issues discovered during the Telegram integration process. 
If the issue/fix is non-trivial, separate it into its own PR.
> chore: Telegram integration fixes

- backend/src/core/services/credential.service.ts
If a credential exists in secrets manager, but not in the db, an error will be thrown while trying to update credentials. 
Disregard the check for whether the credential exists in the db, since we upsert it in the end anyway.
> chore: update secret if exists, else create it

- frontend/src/components/common/file-input/FileInput.module.scss
- frontend/src/components/common/file-input/FileInput.tsx
- frontend/src/components/dashboard/create/email/EmailRecipients.tsx
- frontend/src/components/dashboard/create/email/ProtectedEmailRecipients.tsx
- Disables upload button if template empty
- Remove upload button on csv upload complete
- Add edit message and test message progress buttons
> [Registered] fix: upload button, progress buttons

- serverless/telegram-handler/src/credentials.ts
- serverless/telegram-handler/src/index.ts
- Improve weird SQL syntax for checking bot existence
- Reuse warm db connection between multiple invocations
> chore: Minor Telegram improvements

- backend/package-lock.json
- backend/package.json
- frontend/package-lock.json
- frontend/package.json
- package-lock.json
- package.json
- worker/package-lock.json
- worker/package.json
Add support for Telegram as a new channel type.
- Telegram frontend and backend (#373)
- Telegram workers (#424)
- Telegram handlers (#389)
- Migrated over non-OGP users’ subscribers and bot credentials over to production database
- Set `TELEGRAM_WEBHOOK_URL` and `DEFAULT_COUNTRY` in Elastic Beanstalk
- Deployed Telegram resource on API Gateway
- Deployed production telegram-handler lambda function
- Created tables for Telegram
- Added `TELEGRAM` to `enum_campaigns_type`
- Add a new Telegram bot token under settings
- Subscribe to bot through Telegram client and ensure that the bot is able to successfully capture your phone number
- Send a test message to the newly subscribed number
- Proceed to create and send a Telegram campaign
> [develop] 1.9.0

- backend/src/core/constants.ts
- backend/src/core/services/campaign.service.ts
- frontend/src/classes/Campaign.ts
- frontend/src/components/dashboard/campaigns/Campaigns.module.scss
- frontend/src/components/dashboard/campaigns/Campaigns.tsx
- frontend/src/styles/_variables.scss
- frontend/src/styles/app.scss
Closes #530 
- with some css fixes to campaign list
**AFTER**:
> feat: show protected icon on campaign list

- backend/src/core/config.ts
- backend/src/core/middlewares/campaign.middleware.ts
- backend/src/core/middlewares/protected.middleware.ts
- backend/src/core/routes/protected.routes.ts
- backend/src/core/services/protected.service.ts
- backend/src/email/routes/email-campaign.routes.ts
- frontend/src/services/decrypt-mail.service.ts
- Separate middleware for protected campaign-only routes
- PROTECTED_URL now used instead of FRONTEND_URL
- Better error message for public facing page
> Reg pr fixes

- frontend/src/components/common/sample-csv/SampleCsv.tsx
- frontend/src/components/dashboard/create/email/EmailRecipients.tsx
- frontend/src/components/dashboard/create/sms/SMSRecipients.tsx
- frontend/src/components/dashboard/create/telegram/TelegramRecipients.tsx
Error from templating uncaught when generating sample csv
Wrap handler in callback. Allow passing of setErrorMessage prop.
**After**
> Uncaught exception in sample csv generation

- frontend/src/services/crypto.service.ts
Typo, doesn't affect the code.
> chore: fix misspelled derivedKey

- frontend/src/components/common/action-button/ActionButton.tsx
- frontend/src/components/common/nav-bar/NavBar.module.scss
- frontend/src/components/common/nav-bar/NavBar.tsx
- frontend/src/components/common/primary-button/PrimaryButton.tsx
- frontend/src/components/common/progress-pane/ProgressPane.tsx
- frontend/src/components/common/text-button/TextButton.module.scss
- frontend/src/components/common/text-button/TextButton.tsx
- frontend/src/components/dashboard/create/create-modal/CreateModal.module.scss
- frontend/src/components/dashboard/create/create-modal/CreateModal.tsx
- frontend/src/components/dashboard/create/email/ProtectedEmailRecipients.tsx
- frontend/src/components/dashboard/settings/add-credential-modal/AddCredentialModal.tsx
- frontend/src/components/dashboard/settings/credentials/Credentials.tsx
- frontend/src/components/dashboard/settings/verify-credential-modal/VerifyCredentialModal.tsx
- frontend/src/components/landing/Landing.tsx
- frontend/src/components/login/login-input/LoginInput.tsx
- frontend/src/components/protected/Protected.tsx
- frontend/src/styles/app.scss
- modules/postman-templating/test/template-client.test.ts
- Merge @xming13 pr (ref: #510 )
- Use `<TextButton>` to replace `<a>` tags
> Fix frontend lint warnings

- backend/package-lock.json
- frontend/package-lock.json
- frontend/package.json
- frontend/src/contexts/auth.context.tsx
- worker/package-lock.json
Users not being redirected back to homepage when session has expired. Instead sees a never-ending spinner when loading a new screen.
Closes #596
Redirect user back to homepage.
> Redirect on 401

- backend/.ebextensions/20-eb-memory-monitor.config
Unclear on how much memory is being used.
Add memory monitoring to our elastic beanstalk instances
> chore: add memory monitoring script

- backend/src/email/services/email.service.ts
Old messages not deleted on protected upload complete.
Delete `email_messages` on protected upload complete
> fix: delete existing email messages on protected upload complete

- backend/package-lock.json
- backend/package.json
- frontend/package-lock.json
- frontend/package.json
- package-lock.json
- package.json
- worker/package-lock.json
- worker/package.json
> [develop] 1.10.0

- backend/package-lock.json
- backend/package.json
- backend/src/core/services/upload.service.ts
- backend/src/email/middlewares/email-template.middleware.ts
- backend/src/email/services/email.service.ts
- backend/src/sms/middlewares/sms-template.middleware.ts
- backend/src/sms/services/sms.service.ts
- backend/src/telegram/middlewares/telegram-template.middleware.ts
- backend/src/telegram/services/telegram.service.ts
- frontend/package-lock.json
- frontend/package.json
- package-lock.json
- package.json
- worker/package-lock.json
- worker/package.json
> Release v1.10.1 - fix: transaction was not rolled back when csv upload failed

- frontend/src/components/common/progress-details/ProgressDetails.tsx
- Minor refactoring based on https://github.com/opengovsg/postmangovsg/commit/40df60d83644f0cf6f8b72f711e4149552343b18#r40237414
> refactor(ProgressDetails): remove useState and useEffect for derived state

- frontend/src/components/unsubscribe/Unsubscribe.module.scss
- frontend/src/components/unsubscribe/Unsubscribe.tsx
- serverless/unsubscribe-digest/src/unsubscribe.ts
Closes #660 
- Change proportions of UI elements based on feedback in #660 
- Fix typo in unsubscribe error message
- Update subject for unsubscriber digest email
> fix: Minor unsubscribe UI and copywriting issues

- README.md
- docs/api-usage.md
API users are unsure about how to use the API 
Document sample network calls.
> chore: update api docs

- backend/package-lock.json
- backend/package.json
- frontend/package-lock.json
- frontend/package.json
- package-lock.json
- package.json
- worker/package-lock.json
- worker/package.json
- Email unsubscribe
- Save template draft when user chooses to “Finish later”
- Split serverless Travis build
- Added secrets detection with `detect-secrets`
- Bump bcrypt version to 5.0.0
- Documentation updates:
- Serverless readme
- Installation of detect secrets
- API docs
- Database diagram
- Clean up `ProgressDetail` component
> [develop] 1.12.0

- serverless/log-twilio-callback/src/index.ts
Closes #672 
This parameter is undocumented in Twilio, but recommended by Twilio Support to get past the validation issue
> fix: wrong column name in twilio callback

- worker/package-lock.json
- worker/package.json
- worker/src/core/loaders/message-worker/index.ts
Reverts opengovsg/postmangovsg#608
> Revert "Speed up worker"

- backend/src/core/services/stats.service.ts
Part of #688 
Replace hardcoded strings with enum values in stats.service
> Replace hardcoded strings with enum values in stats.service.ts

- frontend/src/components/common/protected-preview/ProtectedPreview.module.scss
- frontend/src/components/common/text-area/TextArea.module.scss
- frontend/src/components/common/text-input-with-button/TextInputWithButton.module.scss
- frontend/src/components/common/text-input/TextInput.module.scss
- frontend/src/components/dashboard/create/Create.module.scss
- frontend/src/components/dashboard/create/email/EmailTemplate.tsx
- frontend/src/components/dashboard/create/email/ProtectedEmailRecipients.tsx
- frontend/src/styles/_variables.scss
UI/UX improvements were suggested by sarah for the Protected Email feature.
Closes #607
Implements css fixes and refactor components to improve the ux/ui
**Note**
I did not implement the Encryption animation, as there was a performance decrease when the I used Lottie to load the animation json. This is to be implemented in the near future after exploring ways of optimising the animation size.
> UX/UI improvements to Password-Protected feature

- backend/src/core/middlewares/auth.middleware.ts
- backend/src/core/services/auth.service.ts
- backend/src/core/utils/morgan.ts
- backend/src/core/utils/request.ts
> feat: Add originating IP address for OTP email

- backend/src/core/loaders/express.loader.ts
- backend/src/core/routes/index.ts
- backend/src/email/routes/email-callback.routes.ts
- backend/src/email/routes/index.ts
- backend/src/sms/routes/index.ts
- backend/src/sms/routes/sms-callback.routes.ts
- backend/src/telegram/routes/index.ts
- backend/src/telegram/routes/telegram-callback.routes.ts
Before rolling out the refactored callbacks, prepare routes for backward compatibility in case we need to rollback the refactor. 
Add routes that redirect to the current lambdas.
> refactor(callback) - Prepare for rollback

- worker/package-lock.json
- worker/package.json
- worker/src/core/loaders/message-worker/index.ts
- worker/src/core/resources/sql/set-job-to-sent.sql
- worker/src/email/resources/sql/get-messages-to-send-email.sql
- worker/src/sms/resources/sql/get-messages-to-send-sms.sql
- worker/src/telegram/resources/sql/get-messages-telegram.sql
Reverts opengovsg/postmangovsg#693
> Revert "Speed up worker part 2"

- worker/package-lock.json
- worker/package.json
- worker/src/core/loaders/message-worker/index.ts
- worker/src/core/resources/sql/set-job-to-sent.sql
- worker/src/email/resources/sql/get-messages-to-send-email.sql
- worker/src/sms/resources/sql/get-messages-to-send-sms.sql
- worker/src/telegram/resources/sql/get-messages-telegram.sql
This reverts commit 36f9d9591429da94a16c2e75edeec06e961525e6.
> Revert "Speed up worker part 2 (#693)"

- backend/.env-example
- backend/package-lock.json
- backend/package.json
- backend/src/core/config.ts
- backend/src/core/loaders/express.loader.ts
- backend/src/email/interfaces/callback.interface.ts
- backend/src/email/middlewares/email-callback.middleware.ts
- backend/src/email/middlewares/index.ts
- backend/src/email/routes/email-callback.routes.ts
- backend/src/email/services/email-callback.service.ts
- backend/src/email/services/index.ts
- backend/src/email/utils/callback/parsers/index.ts
- backend/src/email/utils/callback/parsers/sendgrid.ts
- backend/src/email/utils/callback/parsers/ses.ts
- backend/src/email/utils/callback/query.ts
- backend/src/email/utils/callback/update-status.ts
I removed support for SNS events since the SES topics will only be subscribed to the new http endpoints, and not the lambda. 
- Create a subscription to the staging ses topic in eu-central-1 like so, to your local tunnel. If you need to confirm the subscription, add this line to get the subscribe url: https://github.com/opengovsg/postmangovsg/pull/684/commits/d67a3e44955f05e0a61a69f11d61d93ed25b39f5
- Use the  eu-central-1 credentials to send out messages 
As our SendGrid account is currently inactive, it's cumbersome to test.
This is the content of a callback for a delivered message:
```
[{"email":"postman@pf.postman.gov.sg","environment":"development","event":"delivered","ip":"167.89.12.138","message_id":"10","response":"250 2.0.0 Ok: queued as …
```
> refactor(callback) : email

- backend/src/core/middlewares/settings.middleware.ts
- backend/src/sms/middlewares/sms.middleware.ts
- backend/src/sms/routes/sms-campaign.routes.ts
- backend/src/sms/routes/sms-settings.routes.ts
- backend/src/telegram/routes/telegram-campaign.routes.ts
- frontend/src/components/common/cred-label-input/CredLabelInput.tsx
- frontend/src/components/dashboard/create/sms/SMSCredentials.tsx
- frontend/src/components/dashboard/create/telegram/TelegramCredentials.tsx
- frontend/src/components/dashboard/settings/add-credential-modal/AddCredentialModal.tsx
- frontend/src/services/sms.service.ts
- frontend/src/services/telegram.service.ts
Reverts opengovsg/postmangovsg#627
> Revert "Save credentials from campaign sending page"

- backend/package-lock.json
- backend/package.json
- backend/src/core/middlewares/settings.middleware.ts
- backend/src/sms/middlewares/sms.middleware.ts
- backend/src/sms/routes/sms-campaign.routes.ts
- backend/src/sms/routes/sms-settings.routes.ts
- backend/src/telegram/routes/telegram-campaign.routes.ts
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/common/cred-label-input/CredLabelInput.tsx
- frontend/src/components/dashboard/create/sms/SMSCredentials.tsx
- frontend/src/components/dashboard/create/telegram/TelegramCredentials.tsx
- frontend/src/components/dashboard/settings/add-credential-modal/AddCredentialModal.tsx
- frontend/src/services/sms.service.ts
- frontend/src/services/telegram.service.ts
- package-lock.json
- package.json
- worker/package-lock.json
- worker/package.json
- Allow saving of credentials added during campaign creation
- Add support for using IAM for database authentication
Follow checklist located [here](https://github.com/datagovsg/postman-internal-docs/blob/rds-iam-checklist/rds-iam-deployment-checklist.md).
> [develop] Release 1.13.0

- README.md
- docs/local-module.md
It was unclear how to make changes to the local node module, `postman-templating`.
Closes #645 
@chinying do let me know if I missed out some parts or there are some things are still unclear.
> chore: add documentation for local node module

- backend/src/telegram/middlewares/telegram.middleware.ts
New telegram credentials could not be saved due to incorrect refactoring
Restore the assignment of credentialName
> Fix to restore saving of new telegram credentials 

- backend/package-lock.json
- backend/package.json
- backend/src/telegram/middlewares/telegram.middleware.ts
- backend/src/telegram/services/telegram-template.service.ts
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/common/export-recipients/ExportRecipients.tsx
- frontend/src/components/common/nav-bar/NavBar.tsx
- frontend/src/components/common/progress-details/ProgressDetails.tsx
- frontend/src/components/common/step-header/StepHeader.module.scss
- frontend/src/components/common/step-header/StepHeader.tsx
- frontend/src/components/dashboard/campaigns/Campaigns.tsx
- frontend/src/components/dashboard/settings/api-key/ApiKey.tsx
- frontend/src/components/dashboard/settings/credentials/Credentials.module.scss
- frontend/src/components/dashboard/settings/credentials/Credentials.tsx
- frontend/src/components/landing/nav-bar/Navbar.tsx
- frontend/src/services/ga.service.ts
- package-lock.json
- package.json
- worker/package-lock.json
- worker/package.json
- Add Google Analytics event to track when user click the download delivery report button
- Added event labels prefix to differentiate outbound links to same destination but from different sections of the app
- Typography
- Delete telegram stats when template is updated with different keys from existing file
- Restore ability to save telegram credentials
> Release v1.16.1

- backend/src/core/services/campaign.service.ts
User managed to create a demo campaign ( demo_messages_limit is not null) but their numDemosSms count was not decremented. 
Await on the transaction to create a campaign.
> fix: await on creation of campaign

- backend/package-lock.json
- backend/package.json
- frontend/package-lock.json
- frontend/package.json
- package-lock.json
- package.json
- worker/package-lock.json
- worker/package.json
- Duplication of campaign 
- Saving of empty sanitised template
- Styles for protected email preview
- Minor UI fixes for demo campaign creation flow
- Minor UI fixes for input boxes
- Added package lockfiles linting 
- Update endpoints interfaces for start upload, complete upload and adding new credentials
> [develop] 1.17.0

- backend/package-lock.json
- backend/package.json
- frontend/package-lock.json
- frontend/package.json
- package-lock.json
- package.json
- worker/package-lock.json
- worker/package.json
- Set reply to email address to logged in user’s email as default
- Add message block to inform users that recipients list are not de-duplicated
- Remove empty rows with tags for protected email preview
> [develop] 1.17.1

- backend/package-lock.json
- backend/package.json
- frontend/package-lock.json
- frontend/package.json
- package-lock.json
- package.json
- worker/package-lock.json
- worker/package.json
- Announcement modal
- Added GA  to track usage of campaign duplication
- Rename SES backend environment variables 
- Add Cronitor monitoring for backup verification
- Allow user to edit draft message when save draft has an error
- Truncate large log messages to prevent causing potential OOM
- Frontend
- `REACT_APP_ANNOUNCEMENT_ACTIVE`
- Backend
- `BACKEND_SES_FROM`
- `BACKEND_SES_HOST`
- `BACKEND_SES_PASS`
- `BACKEND_SES_PORT`
- `BACKEND_SES_USER`
- Backup verification
- `CRONITOR_CODE`
> [develop] 1.18.0

- backend/package-lock.json
- backend/package.json
- frontend/package-lock.json
- frontend/package.json
- package-lock.json
- package.json
- worker/package-lock.json
- worker/package.json
- Frontend campaigns redaction
- Weekly redaction reminder digest
- Updated dependencies for `database-backup` and `verify-backup` lambdas
- Redaction digest
- Production
- `PRODUCTION_REDACTION_ROLE`
- `PRODUCTION_REDACTION_DIGEST_DB_URI`
- `PRODUCTION_REDACTION_DIGEST_DB_READ_REPLICA_URI`
- `PRODUCTION_REDACTION_DIGEST_SES_FROM`
- `PRODUCTION_REDACTION_DIGEST_SES_HOST`
- `PRODUCTION_REDACTION_DIGEST_SES_PASS`
- `PRODUCTION_REDACTION_DIGEST_SES_USER`
- `PRODUCTION_REDACTION_DIGEST_SES_PORT` 
- `PRODUCTION_REDACTION_CRONITOR`
- Staging
- `STAGING_REDACTION_ROLE`
- `STAGING_REDACTION_DIGEST_DB_URI`
- `STAGING_REDACTION_DIGEST_DB_READ_REPLICA_URI`
- `STAGING_REDACTION_DIGEST_SES_FROM`
- `STAGING_REDACTION_DIGEST_SES_HOST`
- `STAGING_REDACTION_DIGEST_SES_PASS`
- …
> [develop] 1.19.0

- backend/package-lock.json
- backend/package.json
- frontend/package-lock.json
- frontend/package.json
- package-lock.json
- package.json
- worker/package-lock.json
- worker/package.json
- Rich text editor for email
- Return `200` when error for Telegram
> [develop] 1.20.0

- README.md
The initial setup docs does not clearly state that lingui translations need to be compiled.
Closes #981
State that the translations need to be compiled in the initial setup docs.
**Features**:
- Details ...
- Details ...
**Bug Fixes**:
- Details ...
**BEFORE**:
[insert screenshot here]
**AFTER**:
[insert screenshot here]
_What tests should be run to confirm functionality?_
_Notes regarding deployment of the contained body of work. These should note any
new dependencies, new scripts, etc._
- `env var` : env var details
**New scripts**:
- `script` : script details
- `dependency` : dependency details
**New dev dependencies**:
- `dependency` : dependency details
> chore: Document the compilation of translations in setup docs

- frontend/src/components/common/rich-text-editor/blocks/ImageBlock.tsx
If there was other text within the block that the image was inserted in, the image block will not be removed correctly through the "Remove" button in the popover. 
Closes #983 
**Bug Fixes**:
- Residual characters in image block causes editor to crash when removing image with tooltip (#983)
- Insert an image in the message and proceed to upload a CSV file
- Return to step 1 to remove the image
- There should not be a crash
> fix(rich-text): unhandled error when removing image from popover

- backend/package-lock.json
- backend/package.json
- frontend/package-lock.json
- frontend/package.json
- package-lock.json
- package.json
- worker/package-lock.json
- worker/package.json
- UI fixes
- Fix unhandled error when removing image from popover
- Fix API documentation 
- Upgraded to lingui 3.0
- Upgraded recommended dependencies by Snyk
- Included info banner on dashboard
New dependencies
- `@lingui/core`: 3.5.1
- `@lingui/react`: 3.5.1
- `@lingui/macro`: 3.5.1
- `lodash` : 4.17.21 
- `mustache`: 4.1.0
- `@types/node`: 14.14.22
- `@types/lodash`: 4.14.168
- `@types/mustache`: 4.1.1
> [develop] 1.21.1

- backend/package-lock.json
- backend/package.json
- frontend/package-lock.json
- frontend/package.json
- package-lock.json
- package.json
- worker/package-lock.json
- worker/package.json
**Commits**:
f54f7c2 (HEAD -> release-v1.22.0, origin/release-v1.22.0) 1.22.0
5f5a655 (origin/develop, origin/HEAD, develop) Migrate worker to get environment variables from Secrets Manager  (#910)
a2a2bbf Update snyk-recommended dependencies (#1031)
e73f096 chore: increase memory and cpu for verify backup service (#998)
**Features**:
- Migrate most worker environment variables to AWS Secrets Manager from ECS task definitions
- Update dependencies recommended by Snyk
**Bug Fixes**:
- Fix intermittent failures in the verify-backup-production service by increasing the memory and CPU core limit
**Renamed worker environment variables**:
- `SES_FROM` -> `WORKER_SES_FROM`
- `SES_HOST` -> `WORKER_SES_HOST`
- `SES_PORT` -> `WORKER_SES_PORT`
- `SES_USER` -> `WORKER_SES_USER`
- …
> [develop] 1.22.0

- backend/package-lock.json
- backend/package.json
- frontend/package-lock.json
- frontend/package.json
- package-lock.json
- package.json
- worker/package-lock.json
- worker/package.json
- Ensure that allowed image sources are loaded correct
- Allow copy pasting within table cells
- Preserve line breaks within table cells
- Shift + Enter to insert new line within paragraph
- Add Singapore government masthead to protected email page and unsubscribe page
- Upgraded dependencies
**New dependencies**
- `aws-sdk`: 2.844.0
- `winston`: 3.3.3
- `nodemailer`: 6.4.18
**New dev dependencies**
- `@types/validator`: 13.1.1
> [develop] 1.22.1

- frontend/src/components/common/nav-bar/NavBar.tsx
- frontend/src/config.ts
- frontend/src/locales/en/messages.po
Closes #1053 
* Add a link next to Settings on the nav bar which navigates to the feature request form. 
Uses the `OutboundLink` element to log event to google analytics.
- Check that nav link works
- Check for associated ga event
> Add Feature Request link in nav bar

- backend/package-lock.json
- backend/package.json
- frontend/package-lock.json
- frontend/package.json
- package-lock.json
- package.json
- worker/package-lock.json
- worker/package.json
- Add feature request form link in nav bar
- Improve UX for duplicating demo campaigns
- Render rich text link popover in top level html
- Display error page if campaign id is invalid 
- Upgrade dependencies recommended by snyk
Feature Request form link in nav bar
Improve UX for duplicating demo campaigns
Display error page if campaign id is invalid 
Render rich text link popover in top level html
Upgrade dependencies recommended by snyk
> [develop] 1.22.2

- backend/package-lock.json
- backend/package.json
- frontend/package-lock.json
- frontend/package.json
- package-lock.json
- package.json
- worker/package-lock.json
- worker/package.json
- Inconsistent font size between normal text and links for protected message
- Allow the use of variables in rich text editor link as both title and URL
- Migrated to better maintained `lottie-react`
- Improved accessibility of dashboard components
- Upgraded dependencies
> [develop] 1.22.3

- backend/package-lock.json
- backend/package.json
- backend/src/core/routes/auth.routes.ts
- backend/src/core/routes/campaign.routes.ts
- backend/src/core/routes/protected.routes.ts
- backend/src/core/routes/settings.routes.ts
- backend/src/core/routes/stats.routes.ts
- backend/src/core/routes/unsubscriber.routes.ts
- backend/src/email/routes/email-callback.routes.ts
- backend/src/email/routes/email-campaign.routes.ts
- backend/src/email/routes/email-settings.routes.ts
- backend/src/sms/routes/sms-callback.routes.ts
- backend/src/sms/routes/sms-campaign.routes.ts
- backend/src/sms/routes/sms-settings.routes.ts
- backend/src/telegram/routes/telegram-callback.routes.ts
- backend/src/telegram/routes/telegram-campaign.routes.ts
- backend/src/telegram/routes/telegram-settings.routes.ts
- serverless/database-backup/package-lock.json
- serverless/database-backup/package.json
- serverless/eb-env-update/package-lock.json
- serverless/eb-env-update/package.json
- serverless/redaction-digest/package-lock.json
- serverless/redaction-digest/package.json
- serverless/unsubscribe-digest/package-lock.json
- serverless/unsubscribe-digest/package.json
- serverless/verify-backup/package-lock.json
- serverless/verify-backup/package.json
- worker/package-lock.json
- worker/package.json
| Dependency | From | To |
| :------------ | :-----| :-- |
| aws-sdk | - | 2.884.0 |
| libphonenumber | - | 1.9.16 |
| swagger-jsdoc | 4.0.0 | 5.0.1 |
| source-map-support | 0.5.16 | 0.5.19 |
| sequelize | 5.22.3 | 5.22.4 |
| @google-cloud/storage | 5.8.1 | 5.8.2 |
> chore: upgrade dependencies

- backend/package-lock.json
- backend/package.json
- frontend/package-lock.json
- frontend/package.json
- package-lock.json
- package.json
- worker/package-lock.json
- worker/package.json
- Avoid calling `setState` on unmounted components
- Disable period updates for `react-moment` components
- Invalid filename on first download of delivery report
- Migrated to use separate callback servers
- Use `customHttp.yml` to specify custom headers on Amplify
- Upgrade dependencies
> [develop] 1.22.4

- backend/src/core/config.ts
- backend/src/core/middlewares/campaign.middleware.ts
- backend/src/email/middlewares/email-template.middleware.ts
- backend/src/email/routes/email-campaign.routes.ts
- backend/src/sms/middlewares/sms-template.middleware.ts
- backend/src/sms/routes/sms-campaign.routes.ts
- backend/src/telegram/middlewares/telegram-template.middleware.ts
- backend/src/telegram/routes/telegram-campaign.routes.ts
Refer 
https://github.com/opengovsg/postmangovsg/pull/1106#discussion_r607438380
https://github.com/opengovsg/postmangovsg/pull/1106#discussion_r607440405
> Remove middleware with duplicated logic and handle expired urls during processing

- backend/package-lock.json
- backend/package.json
- frontend/package-lock.json
- frontend/package.json
- package-lock.json
- package.json
- worker/package-lock.json
- worker/package.json
- Allow use of images as links in rich text editor
- Added character limit for Telegram messages
- Added backend test scaffolding
- Added backend tests for updating campaign templates
- Added backend tests for campaign access control middleware, `canEditCampaign` and `isCampaignOwnedByUser`
- Upgraded React and use new JSX transform
- Fix error when updating Telegram ID for a same phone number
**New dependencies**
- `lodash`: 4.17.21
- `nodemailer` - 6.6.0
- `@sentry/cli`- 1.64.2
- `@google-cloud/secret-manager`- 3.6.0
- `@lingui/react` - 3.8.10
- `mustache` - 4.2.0
> [develop] 1.24.0

- backend/package-lock.json
- backend/package.json
- frontend/package-lock.json
- frontend/package.json
- package-lock.json
- package.json
- shared/package-lock.json
- shared/package.json
- worker/package-lock.json
- worker/package.json
- Allow use of custom sender name
- Refactored to use shared folder
- Login to Docker hub in Travis to avoid rate limits
- `BACKEND_MAIL_VIA` - Use to configure the via line for custom sender name. Defaults to `via Postman`
> [develop] 1.25.0

- backend/src/core/config.ts
- worker/src/core/resources/sql/get-next-job.sql
- worker/src/core/resources/sql/is-credential-used.sql
- worker/src/core/resources/sql/resume-worker.sql
- worker/src/email/resources/sql/enqueue-messages-email.sql
- worker/src/email/resources/sql/get-messages-to-send-email.sql
- worker/src/email/resources/sql/log-job-email.sql
- worker/src/email/resources/sql/log-next-job-email.sql
- worker/src/sms/resources/sql/enqueue-messages-sms.sql
- worker/src/sms/resources/sql/get-messages-to-send-sms.sql
- worker/src/sms/resources/sql/log-job-sms.sql
- worker/src/sms/resources/sql/log-next-job-sms.sql
- worker/src/telegram/resources/sql/enqueue-messages-telegram.sql
- worker/src/telegram/resources/sql/log-job-telegram.sql
Only Whitespace changes
- replace all tabs with two spaces in SQL files
- remove trailing whitespace in SQL files
- fix random tab in config.ts
_Not sure if we should use tabs or spaces? I chose spaces in the end but we can easily change it I guess_
> Standardise sql whitespace

- backend/package-lock.json
- backend/package.json
- frontend/package-lock.json
- frontend/package.json
- package-lock.json
- package.json
- shared/package-lock.json
- shared/package.json
- worker/package-lock.json
- worker/package.json
- Added email template to improve legitimacy of Postman’s emails
**Database migrations**
- `20210621043226-create-get-messages-to-send-email-with-sender-function` - Adds new get message function that includes sender
> [develop] 1.27.0

- shared/src/theme/email-theme.mustache
Updated footer copy for emails
> Alternatively, you may also contact the sender agency or organisation directly through their public contact channels ~~for updates to contact details or email preferences~~
> feat: update footer copy for emails

- backend/package-lock.json
- backend/package.json
- frontend/package-lock.json
- frontend/package.json
- package-lock.json
- package.json
- shared/package-lock.json
- shared/package.json
- worker/package-lock.json
- worker/package.json
**Features**
- Transactional message API
- Agency logo in emails
- Update footer for email template
- Support parentheses in email sender name
**Bug fixes**
- Add Outlook specific styles for pre-header
- Increase timeout for backup
**Database migrations**
- `20210630070237-add-columns-to-agencies`
- `20210630070312-create-domains`
- `20210630070410-add-email-domain-to-user`
- `20210701040653-add-show-logo-to-email-templates`
- `20210701040855-create-get-messages-to-send-email-with-agency-function`
**New dependencies**
- `express-rate-limit`: Express middleware for rate limiting single-send requests.
- `rate-limit-redis`: Redis client for `express-rate-limit`
**New dev dependencies**
- `@types/express-rate-limit`: TypeScript definitions for `express-rate-limit`
- …
> [develop] 1.28.0

- backend/package-lock.json
- backend/package.json
- frontend/package-lock.json
- frontend/package.json
- package-lock.json
- package.json
- shared/package-lock.json
- shared/package.json
- worker/package-lock.json
- worker/package.json
**Features**
- Email read receipt
- Upgraded dependencies and resolved `npm audit` issues
**Bug fixes**
- Move domain creation into same transaction
**Database migrations**
- `20210630095931-alter-enum-email-messages-status.js`
- `20210712142920-create-update-stats-email-with-read-function.js`
- `WORKER_SES_CONFIGURATION_SET`: AWS SES configuration set name. Defaults to `postman-email-open`.
> [develop] 1.29.0

- backend/package-lock.json
- backend/package.json
- backend/src/email/utils/callback/query.ts
- frontend/package-lock.json
- frontend/package.json
- package-lock.json
- package.json
- shared/package-lock.json
- shared/package.json
- worker/package-lock.json
- worker/package.json
Use read replica to determine halting running total.
> hotfix: use read replica to calculate running total for halting

- .travis.yml
- backend/package-lock.json
- backend/package.json
- backend/src/core/loaders/sequelize.loader.ts
- frontend/package-lock.json
- frontend/package.json
- package-lock.json
- package.json
- shared/package-lock.json
- shared/package.json
- worker/package-lock.json
- worker/package.json
- worker/src/core/loaders/message-worker/index.ts
- Add retry config to sequelize
-  Increase memory available for database backup
> Release v1.29.3

- .secrets.baseline
> chore: update secret baseline

- backend/package-lock.json
- backend/package.json
- frontend/package-lock.json
- frontend/package.json
- package-lock.json
- package.json
- worker/package-lock.json
- worker/package.json
- SMS cost calculator
- npm audit fixes
- update secrets baseline
Refer to https://github.com/opengovsg/postmangovsg/pull/1376
> [develop] 1.30.0

- package.json
This PR sets up `npm run test` in the root of the folder
> test: set up npm run test in root

- backend/package-lock.json
- backend/package.json
> build(deps): update jest supporting modules

- backend/src/telegram/middlewares/telegram.middleware.ts
> fix(backend): fix telegram secrets invalid permission to store

- frontend/src/components/common/progress-details/ProgressDetails.tsx
- frontend/src/components/dashboard/create/sms/SMSDetail.tsx
- frontend/src/components/dashboard/create/sms/SMSSend.tsx
Reverts opengovsg/postmangovsg#1440
> Revert "temp(frontend): disable sms sending due to twilio outage"

- backend/src/core/interfaces/campaign.interface.ts
- backend/src/email/middlewares/email.middleware.ts
- frontend/src/classes/EmailCampaign.ts
- frontend/src/components/dashboard/create/email/EmailDetail.tsx
- frontend/src/components/dashboard/create/sms/SMSDetail.tsx
- frontend/src/components/dashboard/create/telegram/TelegramDetail.tsx
> feat(campaigns): viewing of sent campaigns

- backend/src/core/middlewares/campaign.middleware.ts
- backend/src/core/middlewares/tests/campaign.middleware.test.ts
- backend/src/core/models/campaign.ts
- backend/src/core/routes/campaign.routes.ts
- backend/src/core/routes/tests/campaign.routes.test.ts
- backend/src/core/services/campaign.service.ts
- backend/src/database/migrations/20220328105553-add-campaigns-deleted-at.js
- backend/src/email/middlewares/tests/email.middleware.test.ts
- backend/src/email/routes/tests/email-campaign.routes.test.ts
- backend/src/email/services/tests/email-template.service.test.ts
- backend/src/sms/middlewares/tests/sms.middleware.test.ts
- backend/src/sms/routes/tests/sms-campaign.routes.test.ts
- backend/src/sms/services/tests/sms-template.service.test.ts
- backend/src/telegram/middlewares/tests/telegram.middleware.test.ts
- backend/src/telegram/routes/tests/telegram-campaign.routes.test.ts
- backend/src/telegram/services/tests/telegram-template.service.test.ts
- frontend/src/components/common/confirm-modal/ConfirmModal.tsx
- frontend/src/components/dashboard/campaigns/Campaigns.module.scss
- frontend/src/components/dashboard/campaigns/Campaigns.tsx
- frontend/src/components/dashboard/campaigns/actions-button/ActionsButton.module.scss
- frontend/src/components/dashboard/campaigns/actions-button/ActionsButton.tsx
- frontend/src/components/dashboard/campaigns/actions-button/index.ts
- frontend/src/services/campaign.service.ts
> feat: Campaign deletion

- backend/src/core/middlewares/campaign.middleware.ts
- backend/src/core/routes/campaign.routes.ts
- backend/src/core/services/campaign.service.ts
- frontend/src/components/common/text-input-with-button/TextInputWithButton.tsx
- frontend/src/components/dashboard/campaigns/Campaigns.module.scss
- frontend/src/components/dashboard/campaigns/Campaigns.tsx
- frontend/src/components/dashboard/campaigns/OverrideTextInputWithButton.module.scss
- frontend/src/components/dashboard/campaigns/actions-button/ActionsButton.module.scss
- frontend/src/components/dashboard/campaigns/actions-button/ActionsButton.tsx
- frontend/src/services/campaign.service.ts
Pending #1467 to be merged first
Resolves #1418
> feat: rename campaign

- backend/package-lock.json
- backend/package.json
- frontend/package-lock.json
- frontend/package.json
- package-lock.json
- package.json
- shared/package-lock.json
- shared/package.json
- worker/package-lock.json
- worker/package.json
Closes [insert issue #]
**Features**:
- Details ...
- Details ...
**Bug Fixes**:
- Details ...
**BEFORE**:
[insert screenshot here]
**AFTER**:
[insert screenshot here]
_What tests should be run to confirm functionality?_
_Notes regarding deployment of the contained body of work. These should note any
new dependencies, new scripts, etc._
- `env var` : env var details
**New scripts**:
- `script` : script details
- `dependency` : dependency details
**New dev dependencies**:
- `dependency` : dependency details
> [develop] Release v1.33.0

- .github/workflows/ci.yml
- .github/workflows/deploy-eb.yml
- backend/src/test-utils/global-setup.ts
- docker-compose.test.yml
cc: @tan-zx for local test issues
> chore(sql-conn): align tests and CI db credentials

- .github/workflows/deploy-frontend.yml
- scripts/amplify-deploy.sh
Resolves #1404 
Deployment checklist:
> build(aws-amplify): move amplify trigger to github actions

- backend/src/core/models/campaign.ts
small change to clarify what @lamkeewei mentioned today
> docs: add comment to clariy manual override of halting

- .github/workflows/cypress.yml
> fix: actions/checkout version

- frontend/package-lock.json
> build: change in package-lock.json after running npm i

- frontend/src/components/landing/banner/Banner.tsx
closes https://github.com/opengovsg/postmangovsg/issues/1639
in truth, this feels like something we should add into the OGP design system and only change once, rather than re-implement for every product?
> fix: fix gogovsg trusted sites link

- frontend/src/components/dashboard/settings/Settings.tsx
Closes https://github.com/opengovsg/postmangovsg/issues/1644
Only removes for users who have yet to set it up; users who've set it up should not be affected
> feat: remove button to link to custom domain page

- frontend/src/components/common/email-preview-block/EmailPreviewBlock.module.scss
Bullet points missing on preview
Closes #1653 
added styles to css
N/A
> fix: list style on preview

- frontend/src/components/dashboard/campaigns/Campaigns.tsx
- frontend/src/components/dashboard/settings/Settings.module.scss
- frontend/src/components/dashboard/settings/Settings.tsx
Closes https://github.com/opengovsg/postmangovsg/issues/1649
Can @lisatjide help to test on [staging](https://staging.postman.gov.sg/login) that the glitch is gone? Have pushed to staging.
@stanleynguyen Haha I think the way I fixed it is pretty hacky (I went to look into whether to use React Query etc. but it's all a bit too much effort...)
> fix: remove split second lag

- backend/package-lock.json
- backend/package.json
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/common/rich-text-editor/RichTextEditor.tsx
- frontend/src/components/common/rich-text-editor/controls/TableControl.tsx
- frontend/src/components/dashboard/create/Create.tsx
- frontend/src/components/dashboard/create/email/EmailCreate.tsx
- frontend/src/components/dashboard/create/email/EmailTemplate.tsx
- frontend/src/components/dashboard/create/sms/SMSCreate.tsx
- frontend/src/components/login/login-input/LoginInput.tsx
- frontend/src/services/email.service.ts
- frontend/src/services/sms.service.ts
- frontend/src/services/telegram.service.ts
- frontend/src/services/upload.service.ts
- frontend/src/test-utils/api/index.ts
- worker/package-lock.json
- worker/package.json
noticed frontend prettier is quite outdated; have updated it to brought it to versions used elsewhere:
UPDATE: have updated the backend and worker prettier, so that it's `2.6.2` everywhere
> style: upgrade and apply prettier

- .github/workflows/deploy.serverless.redaction-digest.yml
- .github/workflows/deploy.serverless.unsubscribe-digest.yml
- serverless/redaction-digest/package-lock.json
- serverless/redaction-digest/package.json
- serverless/redaction-digest/src/index.ts
- serverless/unsubscribe-digest/package-lock.json
- serverless/unsubscribe-digest/package.json
- serverless/unsubscribe-digest/src/config.ts
- serverless/unsubscribe-digest/src/index.ts
- shared/package-lock.json
- shared/package.json
Fix [this bug](https://ap-southeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-southeast-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252Funsubscribe-digest-production/log-events/2022$252F07$252F11$252F$255B$2524LATEST$255Dc3bd5ddb466d4a478e925b0aa1281a6c)
> build(serverless): fix deployments of serverless functions with shared

- frontend/src/locales/en/messages.po
Closes #1540 
Update in locale
N/A
> refactor(frontend): update guide links to use go gov

- shared/src/theme/email-theme.mustache
- [Ticket](https://www.notion.so/opengov/update-unsub-link-on-email-footer-f79d938905264820887898c0cf2f9c1e)
Update it duh
N/A
> feat(email-template): update footer for more prominent unsubscribe button

- backend/src/core/middlewares/unsubscriber.middleware.ts
- backend/src/core/models/unsubscriber.ts
- backend/src/core/routes/unsubscriber.routes.ts
- backend/src/core/services/unsubscriber.service.ts
- backend/src/database/migrations/20220729073818-add-unsubscribe-reason.js
- frontend/src/components/unsubscribe/Unsubscribe.module.scss
- frontend/src/components/unsubscribe/Unsubscribe.tsx
- frontend/src/components/unsubscribe/tests/Unsubscribe.test.tsx
- frontend/src/services/unsubscribe.service.ts
- frontend/src/test-utils/api/index.ts
Add reason to unsubscribe flow
- [Ticket](https://www.notion.so/opengov/Update-unsub-flow-copy-48f85ed8622142668697703f11a2241c)
Update unsub flow to the new one
> feat(unsubscriber): add reason to unsubscription request

- .secrets.baseline
- README.md
- backend/.env-example
- backend/package.json
- package.json
Have also made the necessary changes to our 1Password vault
> feat: add README, variables, and command for connecting to Grafana dashboard

- backend/src/core/routes/tests/protected.routes.test.ts
> test(backend): add tests for protected routes

- backend/package-lock.json
- frontend/package-lock.json
- package-lock.json
- serverless/redaction-digest/package-lock.json
- serverless/redaction-digest/package.json
- serverless/unsubscribe-digest/package-lock.json
- worker/package-lock.json
Close security issues flagged by Dependabot
(Pushed to staging; pending results)
> chore: upgrade moment-timezone in backend, worker and serverless

- .gitignore
- frontend/package-lock.json
- frontend/src/locales/en/messages.po
- adding `.idea` to `.gitignore` (not sure why this didn't occur with my previous laptop, which was also using Webstorm)
- frontend `package-lock.json` changes; will test these on staging
- `frontend/src/locales/en/messages.po` → think these are changes caused by previous PR on unsubscribe
> build:  changes made after setting up postmangovsg on new laptop

- frontend/src/components/dashboard/create/email/EmailRecipients.tsx
- frontend/src/components/dashboard/create/sms/SMSRecipients.tsx
- frontend/src/components/experimental/ManagedListSection.tsx
- frontend/src/components/experimental/index.ts
This PR introduces a UI section to gather interest in our experimental managed list feature. The dropdown is currently disabled intentionally.
> feat: add UI with link to form for managed list

- frontend/src/components/dashboard/create/email/EmailRecipients.tsx
- frontend/src/components/dashboard/create/sms/SMSRecipients.tsx
- frontend/src/components/experimental/ManagedListInfoBlock.tsx
- frontend/src/components/experimental/ManagedListSection.tsx
- frontend/src/components/experimental/index.ts
See thread [here](https://opengovproducts.slack.com/archives/CT8D1FESY/p1664173965957259?thread_ts=1664170898.630389&cid=CT8D1FESY)
After
> feat: make link to express interest in managed list prominent

- backend/src/database/migrations/20220915123536-create-email-messages-transactional.js
- docs/api-usage.md
> docs: add docs for transactional email API

- .secrets.baseline
- backend/.env-example
- backend/src/core/config.ts
- backend/src/email/services/custom-domain.service.ts
- worker/src/core/config.ts
Closes https://github.com/opengovsg/postmangovsg/issues/759
See [here](https://github.com/opengovsg/postmangovsg/issues/759#issuecomment-1257414111) for context
> feat: validate from address on both worker and backend SES regions

- backend/package.json
- package.json
- serverless/database-backup/package.json
- serverless/verify-backup/package.json
- shared/package.json
- worker/package.json
Closes #1834
Updating all github references to point to opengovsg
NA
> feat: rename datagovsg to opengovsg in codebase

- backend/src/core/models/campaign.ts
- backend/src/database/migrations/20210422073013-create-campaigns.js
- backend/src/database/migrations/20210422073931-create-sms-messages.js
- backend/src/database/migrations/20210422081912-create-email-messages.js
- backend/src/database/migrations/20210422082154-create-telegram-messages.js
- backend/src/database/migrations/20210422083045-create-sms-ops.js
- backend/src/database/migrations/20210422083254-create-telegram-ops.js
- backend/src/database/migrations/20210422083258-create-email-ops.js
- backend/src/database/migrations/20220915123536-create-email-messages-transactional.js
- backend/src/database/migrations/20221009141317-change-json-to-jsonb-everywhere.js
- backend/src/email/models/email-message-transactional.ts
- backend/src/email/models/email-message.ts
- backend/src/email/models/email-op.ts
- backend/src/sms/models/sms-message.ts
- backend/src/sms/models/sms-op.ts
- backend/src/telegram/models/telegram-message.ts
- backend/src/telegram/models/telegram-op.ts
duplicate of https://github.com/opengovsg/postmangovsg/pull/1835, which was reverted due to migration issue
> refactor: jsonb everywhere

- backend/src/email/routes/email-settings.routes.ts
- backend/src/email/routes/email-transactional.routes.ts
[Ticket](https://www.notion.so/opengov/Implement-verify-custom-from-address-endpoint-b193fb45e1794e219964492ed4548c58)
Improve the swagger docs
> docs(backend): improve documentation for custom from verification endpoint

- backend/src/email/interfaces/email.interface.ts
- backend/src/email/routes/email-transactional.routes.ts
GET endpoints for:
- listing transactional emails
- get transactional email by ID
Implement it duh
> feat(backend): transactional email GET endpoints design

- backend/src/sms/middlewares/sms-template.middleware.ts
- backend/src/sms/routes/sms-campaign.routes.ts
[Ticket](https://www.notion.so/opengov/Manage-list-feature-not-working-for-SMS-campaigns-65e78d6f62004857953368bd89ebcadb)
Implement select list endpoint for SMS
> feat(backend): add endpoint to handle list selection for SMS

- frontend/src/components/dashboard/create/email/EmailCredentials.tsx
slightly edited the copywriting to make things clearer
approved by @lisatjide and @khaleedah
> fix: minor copywriting shown after email validation

- backend/src/sms/routes/sms-transactional.routes.ts
Fix error from [here](https://github.com/opengovsg/postmangovsg/commit/ac406561ed22f60ae837958b575296ccd9bfbfd2) that prevents server from starting
> fix(backend): invalid txn sms endpoint swagger doc

- backend/src/core/config.ts
- backend/src/email/middlewares/email-transactional.middleware.ts
Undo https://github.com/opengovsg/postmangovsg/pull/1862 as legacy users have updated their system
> chore: restore 201 status code

- backend/src/core/services/auth.service.ts
[Sentry issue](https://sentry.io/organizations/open-government-products-re/issues/3885075475/?project=5272357&query=is%3Aunresolved&referrer=issue-stream)
> fix: Sentry error

- docs/api-usage.md
docs in `api-usage.md` was wrong
Closes [insert issue #]
- removed `from` because it was confusing ppl
- JSON was malformed
> fix: malformed json in api-usage.md

- .github/workflows/non-serverless-deploy.yml
- .secrets.baseline
Continued effort from #1897 
Use slack gh actions
> build(slack): send messages to slack to notify about builds

- .github/workflows/non-serverless-deploy.yml
- .secrets.baseline
Slack notification failure due to special characters in commit messages like [here](https://github.com/opengovsg/postmangovsg/actions/runs/4230564242)
Only take the first line of the commit message and escape double quote
N/A
> build(slack): fix slack notification payload

- frontend/src/components/common/progress-details/ProgressDetails.tsx
See [ticket](https://www.notion.so/opengov/fd466213f133486d85e4117f1ded521d?v=b24d3dcc31e841d08136631d532ad8f6&p=34f95655db8b4ed7867df2a28b1a7db2&pm=s)
See [Slack thread here](https://opengovproducts.slack.com/archives/CT8D1FESY/p1677470598431129) for related issues + discussion
> feat: remove pause sending campaign button

- frontend/src/components/common/info-banner/InfoBanner.module.scss
Increasing font size of infobanner thru product request
> chore: adjust infobanner font

- .github/workflows/non-serverless-deploy.yml
Restoring the ppt tests that were left out in the previous deployment
> chore: restore tests before deployment

- .github/workflows/non-serverless-deploy.yml
- backend/src/database/migrations/20230316082445-append-transactional-sms-timestamps.js
- backend/src/sms/middlewares/sms-transactional.middleware.ts
- backend/src/sms/models/sms-message-transactional.ts
- backend/src/sms/routes/tests/sms-callback.routes.test.ts
- backend/src/sms/services/sms-callback.service.ts
Adding on callback timestamps for sms_messages_transactional.
Deployment Checklist
> feat: adding callback timestamps for sms_messages_transactional

- .github/workflows/non-serverless-deploy.yml
- backend/src/core/middlewares/api-key.middleware.ts
- backend/src/core/routes/api-key.routes.ts
- backend/src/core/routes/index.ts
- backend/src/core/routes/tests/api-key.routes.test.ts
- backend/src/core/services/api-key.service.ts
As per [ticket](https://www.notion.so/opengov/Delete-an-API-key-endpoint-735bc9991ea94e6c8c4da891e15c67c3?pvs=4)
1. Created new apikey route for new apikey specific endpoints. 
2. Introduce endpoint to delete API key
3. Integration tests for the new endpoint
Deployment Checklist
> feat: deleting api key feature with tests

- e2e/tests/email-campaign.test.ts
- e2e/tests/email-encrypted-campaign.test.ts
- e2e/tests/email-scheduled.test.ts
[Ticket](https://www.notion.so/opengov/Migrate-e2e-away-from-Cypress-6419b67862b14a79800e0a7c758abaa4?pvs=4)
> ci(e2e): add email test cases for playwright

- .github/workflows/e2e.yml
- e2e/config.ts
- e2e/tests/sms.test.ts
[Ticket](https://www.notion.so/opengov/Migrate-e2e-away-from-Cypress-6419b67862b14a79800e0a7c758abaa4?pvs=4)
> ci(e2e): add test case for sms in playwright

- README.md
- backend/openapi.yaml
- backend/src/core/config.ts
- backend/src/database/migrations/20230328025019-add-tx-email-classification-tag-columns.js
- backend/src/email/middlewares/email-transactional.middleware.ts
- backend/src/email/models/email-message-transactional.ts
- backend/src/email/routes/email-transactional.routes.ts
[Ticket](https://www.notion.so/opengov/fd466213f133486d85e4117f1ded521d?v=94cf83ccaa9c4fa4a15235cdf10ba9f4&p=193debfcb61948b98e8e7b5422c8568c&pm=s)
Todo:
Deployment
Note to reviewers: the DoD doesn't include tests. If we decide to permanently add this feature, we can add tests I guess.
> feat: add tag and classification to tx email

- .github/workflows/e2e.yml
- .github/workflows/non-serverless-deploy.yml
[Thread](https://opengovproducts.slack.com/archives/C04H0FTGS5P/p1680054944873659?thread_ts=1680054752.086139&cid=C04H0FTGS5P)
To-do:
> build(ci): update yml to avoid rolling back on staging

- backend/src/core/middlewares/api-key.middleware.ts
- backend/src/core/routes/index.ts
- backend/src/core/services/api-key.service.ts
- frontend/src/components/common/confirm-modal/ConfirmModal.module.scss
- frontend/src/components/common/primary-button/PrimaryButton.tsx
- frontend/src/components/dashboard/settings/Settings.tsx
- frontend/src/components/dashboard/settings/add-api-key-modal/AddApiKeyModal.tsx
- frontend/src/components/dashboard/settings/api-key/ApiKey.module.scss
- frontend/src/components/dashboard/settings/api-key/ApiKey.tsx
- frontend/src/components/dashboard/settings/api-key/CopyModal.module.scss
- frontend/src/components/dashboard/settings/api-key/CopyModal.tsx
- frontend/src/components/dashboard/settings/api-key/CreateModal.module.scss
- frontend/src/components/dashboard/settings/api-key/CreateModal.tsx
- frontend/src/services/api-key.service.ts
- frontend/src/services/settings.service.ts
[Ticket](https://www.notion.so/opengov/Multi-API-key-support-for-API-settings-page-3577b7a7f4414ddca3c4104a3daa7507?pvs=4)
Implement [the design](https://www.figma.com/file/29FkTqWnA4yLKzstnvyY6X/Design-Master-V1?t=NU4IZNYNKd6Dktsm-0)
> feat(frontend): multi API key support for API settings page

- frontend/src/locales/en/messages.po
We want to gather interest from agencies who wants to send messages through WhatsApp.
> announcement modal to gather interest for whatsapp

- backend/package.json
- backend/src/core/config.ts
- backend/src/core/constants.ts
- backend/src/core/routes/index.ts
- backend/src/whatsapp/interfaces/index.ts
- backend/src/whatsapp/interfaces/whatsapp.interface.ts
- backend/src/whatsapp/middlewares/index.ts
- backend/src/whatsapp/middlewares/whatsapp-callback.middleware.ts
- backend/src/whatsapp/middlewares/whatsapp.middleware.ts
- backend/src/whatsapp/routes/index.ts
- backend/src/whatsapp/routes/whatsapp-callback.routes.ts
- backend/src/whatsapp/routes/whatsapp-campaign.routes.ts
- backend/src/whatsapp/services/index.ts
- backend/src/whatsapp/services/whatsapp-callback.service.ts
- backend/src/whatsapp/services/whatsapp.service.ts
- backend/tsconfig.json
- shared/package-lock.json
- shared/package.json
- shared/src/clients/whatsapp-client.class/index.ts
- shared/src/clients/whatsapp-client.class/interfaces.ts
- worker/tsconfig.json
As per [whatsapp](https://www.notion.so/opengov/RFC-Whatsapp-Implementation-b16ba611aced40c1baf52224169de836?pvs=4) epic.
This release has proven:
Please ignore empty files / files with code in them just to enable them to be exported without errors :)
> feat: Init whatsapp service and accompanying placeholder code.

- backend/src/email/middlewares/email.middleware.ts
- backend/src/email/routes/tests/email-transactional.routes.test.ts
While writing docs and looking up code, realise error code handling is inconsistent
- Add db update for `unverified email address` error
- Add tests to ensure consistent behaviour
> refactor: add db update for unverified from address

- backend/src/core/loaders/express.loader.ts
- backend/src/core/services/auth.service.ts
Currently, cookies are being saved in logs. This is potentially a security issue.
Redact cookies
> chore: redact cookie from logs

- backend/openapi.yaml
[Ticket](https://www.notion.so/opengov/Update-swagger-doc-to-reflect-latest-error-response-design-0c4b250233de4d8ca3596abcdf6fd7bf?pvs=4)
Update openapi doc
> docs(openapi): update endpoint responses

- backend/openapi.yaml
- backend/src/core/errors/rest-api.errors.ts
- backend/src/core/middlewares/settings.middleware.ts
- backend/src/email/middlewares/email-template.middleware.ts
- backend/src/sms/middlewares/sms-stats.middleware.ts
- backend/src/sms/middlewares/sms-template.middleware.ts
- backend/src/sms/middlewares/sms-transactional.middleware.ts
- backend/src/sms/middlewares/sms.middleware.ts
- backend/src/telegram/middlewares/telegram-stats.middleware.ts
- backend/src/telegram/middlewares/telegram-template.middleware.ts
- backend/src/telegram/middlewares/telegram.middleware.ts
[Ticket](https://www.notion.so/opengov/Update-responses-for-sms-related-endpoints-errors-7599ca20255e44339fe64b64f2af1454?pvs=4)
- update error responses
> refactor(backend): refactor sms api error responses

- backend/openapi.yaml
- backend/src/core/errors/rest-api.errors.ts
- backend/src/core/middlewares/campaign.middleware.ts
- backend/src/core/middlewares/file-attachment.middleware.ts
- backend/src/core/middlewares/job.middleware.ts
- backend/src/core/middlewares/protected.middleware.ts
- backend/src/core/middlewares/settings.middleware.ts
- backend/src/core/middlewares/upload.middleware.ts
- backend/src/core/services/job.service.ts
- backend/src/email/middlewares/email-template.middleware.ts
- backend/src/email/middlewares/email-transactional.middleware.ts
- backend/src/email/middlewares/email.middleware.ts
- backend/src/email/routes/email-campaign.routes.ts
- backend/src/sms/middlewares/sms-stats.middleware.ts
- backend/src/sms/middlewares/sms-template.middleware.ts
- backend/src/sms/middlewares/sms-transactional.middleware.ts
- backend/src/sms/middlewares/sms.middleware.ts
- backend/src/sms/routes/sms-campaign.routes.ts
- backend/src/telegram/middlewares/telegram-stats.middleware.ts
- backend/src/telegram/middlewares/telegram-template.middleware.ts
- backend/src/telegram/middlewares/telegram.middleware.ts
- backend/src/telegram/routes/telegram-campaign.routes.ts
- frontend/src/components/common/progress-details/ProgressDetails.tsx
- frontend/src/components/dashboard/create/email/EmailDetail.tsx
- frontend/src/components/dashboard/create/sms/SMSDetail.tsx
- frontend/src/components/dashboard/create/telegram/TelegramDetail.tsx
- frontend/src/services/campaign.service.ts
[Ticket](https://www.notion.so/opengov/Update-responses-for-email-related-endpoints-errors-b302ecb6e25f4844969ef76089be287f?pvs=4)
- Adjust responses
- Remove unnecessary endpoints
> refactor(email): refactor responses and remove unnecessary email campaign endpoints

- backend/openapi.yaml
- backend/src/core/errors/rest-api.errors.ts
- backend/src/core/middlewares/campaign.middleware.ts
- backend/src/core/middlewares/job.middleware.ts
[Ticket](https://www.notion.so/opengov/Update-responses-for-campaign-related-endpoints-errors-615ab9a1557c493fb0cf82074a25fd84?pvs=4)
Refactor them to use the share REST API error types
> refactor(backend): update responses for generic campaign endpoints

- .secrets.baseline
- backend/openapi.yaml
- backend/src/core/errors/rest-api.errors.ts
- backend/src/core/loaders/express.loader.ts
- backend/src/core/middlewares/auth.middleware.ts
- backend/src/core/middlewares/campaign.middleware.ts
- backend/src/core/middlewares/file-attachment.middleware.ts
- backend/src/core/middlewares/job.middleware.ts
- backend/src/core/middlewares/protected.middleware.ts
- backend/src/core/middlewares/settings.middleware.ts
- backend/src/core/middlewares/upload.middleware.ts
- backend/src/core/services/job.service.ts
- backend/src/email/middlewares/email-template.middleware.ts
- backend/src/email/middlewares/email-transactional.middleware.ts
- backend/src/email/middlewares/email.middleware.ts
- backend/src/email/routes/email-campaign.routes.ts
- backend/src/sms/middlewares/sms-stats.middleware.ts
- backend/src/sms/middlewares/sms-template.middleware.ts
- backend/src/sms/middlewares/sms-transactional.middleware.ts
- backend/src/sms/middlewares/sms.middleware.ts
- backend/src/sms/routes/sms-campaign.routes.ts
- backend/src/telegram/middlewares/telegram-stats.middleware.ts
- backend/src/telegram/middlewares/telegram-template.middleware.ts
- backend/src/telegram/middlewares/telegram.middleware.ts
- backend/src/telegram/routes/telegram-campaign.routes.ts
- frontend/src/components/common/progress-details/ProgressDetails.tsx
- frontend/src/components/dashboard/create/email/EmailDetail.tsx
- frontend/src/components/dashboard/create/sms/SMSDetail.tsx
- frontend/src/components/dashboard/create/telegram/TelegramDetail.tsx
- frontend/src/services/campaign.service.ts
[Ticket](https://www.notion.so/opengov/Update-responses-for-general-errors-d3d2bb802aa542f2850c83333bf78db0?pvs=4)
Refactor it to use the shared REST API error types
> refactor(backend): refactor general errors declaration

- backend/src/core/middlewares/file-attachment.middleware.ts
- backend/src/core/routes/campaign.routes.ts
[Ticket](https://www.notion.so/opengov/File-download-endpoint-8c4e0e509a634e76bbfa113c53e05d45?pvs=4)
Stream S3 file down to frontend
> feat(backend): download endpoint for commmon attachments

- .github/workflows/e2e.yml
- worker/package-lock.json
> chore: upgrade deps flagged by Snyk

- e2e/README.md
- e2e/config.ts
small changes while trying to run Playwright tests against staging
> test(playwright): add debug mode + improve writeup + fix small bugs

- backend/src/core/services/file-attachment.service.ts
- backend/src/email/middlewares/email-transactional.middleware.ts
- backend/src/email/services/email-transactional.service.ts
found these problems while working on transactional GovSG messages
> refactor: tighten up types and errors

- backend/src/core/constants.ts
- backend/src/core/interfaces/campaign.interface.ts
- backend/src/core/models/statistic.ts
- backend/src/core/services/stats.service.ts
- backend/src/database/migrations/20230621062632-create-enqueue-messages-govsg-function.js
- backend/src/database/migrations/20230621063417-create-get-messages-to-send-govsg-function.js
- backend/src/database/migrations/20230621091609-create-update-stats-govsg-function.js
- backend/src/database/migrations/20230621092552-create-log-job-govsg-function.js
- backend/src/database/migrations/20230621093152-create-log-next-job-govsg-function.js
- backend/src/database/seeders/20230621021627-add-default-govsg-creds.js
- backend/src/govsg/middlewares/govsg-stats.middleware.ts
- backend/src/govsg/middlewares/govsg.middleware.ts
- backend/src/govsg/middlewares/index.ts
- backend/src/govsg/models/govsg-template.ts
- backend/src/govsg/routes/govsg-campaign.routes.ts
- backend/src/govsg/services/govsg-stats.service.ts
- backend/src/govsg/services/govsg.service.ts
- backend/src/govsg/services/index.ts
- frontend/src/classes/Campaign.ts
- frontend/src/components/common/progress-details/ProgressDetails.tsx
- frontend/src/components/dashboard/create/govsg/GovsgCreate.tsx
- frontend/src/components/dashboard/create/govsg/GovsgDetail.tsx
- shared/src/clients/onprem-whatsapp-client.class/index.ts
- worker/src/core/loaders/message-worker/index.ts
- worker/src/core/loaders/message-worker/interface.ts
- worker/src/core/loaders/message-worker/util/govsg.class.ts
> feat(worker): setup govsg message sending worker

- backend/src/core/services/whatsapp.service.ts
- worker/src/core/loaders/message-worker/index.ts
- Noticed that I didn't set connection pool options earlier
- I think the alr existing env vars db pool options should be fine (I notice that the serverless functions use these settings too)
> feat: add connection pool options for connecting to Flamingo DB

- frontend/src/components/common/rich-text-editor/RichTextEditor.tsx
Re-enable inline attachment upload
> feat(frontend): enable inline attachment

- backend/src/govsg/services/govsg-callback.service.ts
> feat: rehprase autoreply message

- backend/src/email/middlewares/email-transactional.middleware.ts
- backend/src/email/routes/email-transactional.routes.ts
[ticket](https://opengovproducts.slack.com/archives/CT8D1FESY/p1690190255044149)
Todo
Deployment notes: N/A
> feat: allow users to exclude params field

- backend/src/core/errors/rest-api.errors.ts
- backend/src/email/middlewares/email-transactional.middleware.ts
- backend/src/email/routes/email-transactional.routes.ts
SES limit of 50: https://docs.aws.amazon.com/ses/latest/APIReference/API_SendEmail.html
> feat: ensure total recipients within SES limit

- backend/src/email/middlewares/email-transactional.middleware.ts
- backend/src/govsg/middlewares/govsg-transactional.middleware.ts
- backend/src/govsg/routes/govsg-transactional.routes.ts
- backend/src/govsg/services/govsg-transactional.service.ts
- backend/src/govsg/services/index.ts
Transactional GovSG get message by ID endpoint
> feat(backend): add govsg txn GET message by ID

- backend/openapi.yaml
- backend/src/core/constants.ts
- backend/src/govsg/middlewares/govsg-transactional.middleware.ts
- backend/src/govsg/routes/govsg-transactional.routes.ts
- backend/src/govsg/services/govsg-transactional.service.ts
GovSG transactional list messages
> feat(backend): list messages endpoint for GovSG

- backend/src/database/migrations/20230713014803-add-cc-table.js
- backend/src/database/migrations/20230728105932-unnecessary-unique-cc.js
with composite primary key, there is no need for the unique constraint
> refactor: drop unnecessary unique constraint

- backend/src/govsg/services/govsg-callback.service.ts
Without the `messages` field, the logs aren't showing up.
> chore: improve logging

- backend/src/govsg/services/govsg-callback.service.ts
https://open-government-products-re.sentry.io/issues/4354572595/?project=5272357&query=&referrer=project-issue-stream
> fix: TypeError: Cannot read properties of undefined (reading 'userId')

- backend/openapi.yaml
should have been part of [this PR](https://github.com/opengovsg/postmangovsg/pull/2101)
> docs: update openapi.yaml

- backend/src/govsg/services/govsg-callback.service.ts
There is suspicion that "delivered" status updates without message ID are being received and subsequently dropped, leading to the absence of `sgc_passcode_generation`.
This PR deals with the above.
> fix: retry delivered status updates without govsg message

- backend/package-lock.json
- backend/package.json
https://security.snyk.io/vuln/SNYK-JS-IMPORTINTHEMIDDLE-5826054
- `import-in-the-middle` is a dep of `dd-trace`
- `dd-trace` for the other `package.json` are already updated but not this. So I'm updating it in this PR.
> chore: make import-in-the-middle ^1.4.2

- backend/src/core/errors/rest-api.errors.ts
- backend/src/core/middlewares/file-attachment.middleware.ts
response to [incident](https://opengovproducts.slack.com/archives/C015VQQ3HMG/p1692068456160179)
tested on local, safe to deploy
> fix: handle JSON attachment edge case

- backend/src/database/migrations/20230816092918-remove-non-null-constraint-from-passcode_creation_wamid.js
- backend/src/govsg/middlewares/govsg-verification.middleware.ts
- backend/src/govsg/models/govsg-verification.ts
- backend/src/govsg/services/govsg-verification-service.ts
- backend/src/govsg/services/govsg.service.ts
- backend/src/govsg/utils/passcode.ts
Closes [SGC-209](https://linear.app/ogp/issue/SGC-209/show-passcode-immediately)
- Remember to run pending migrations in the various envs
> feat: show passcode asap

- backend/src/database/migrations/20230816092918-remove-non-null-constraint-from-passcode_creation_wamid.js
- backend/src/database/migrations/20230818092044-set-on-delete-cascade-for-govsg-verification.js
- backend/src/govsg/middlewares/govsg-verification.middleware.ts
- backend/src/govsg/models/govsg-verification.ts
- backend/src/govsg/services/govsg-verification-service.ts
- backend/src/govsg/services/govsg.service.ts
- backend/src/govsg/utils/passcode.ts
- frontend/src/components/common/action-button/ResendButton.tsx
- frontend/src/components/dashboard/create/govsg/GovsgMessages.tsx
- frontend/src/styles/app.scss
Can run migration before merging. Update: Done!
1. Reverts opengovsg/postmangovsg#2186
1. Plus fix foreign key constraint violation when re-picking template and 2nd+ upload of CSV (see screenshot below)
1. AND #2185
```sql
SELECT update_rule, delete_rule
FROM information_schema.referential_constraints
WHERE constraint_name = 'govsg_verification_govsg_message_id_fkey';
```
> (PR 1) Revert Revert feat: show passcode asap

- backend/src/govsg/middlewares/govsg-verification.middleware.ts
- backend/src/govsg/routes/govsg-campaign.routes.ts
- backend/src/govsg/services/govsg-callback.service.ts
- backend/src/govsg/services/govsg-verification-service.ts
- backend/src/govsg/services/govsg.service.ts
- frontend/src/components/common/action-button/ResendButton.tsx
- frontend/src/components/dashboard/create/govsg/GovsgMessages.tsx
- frontend/src/components/dashboard/create/govsg/GovsgRecipients.tsx
- frontend/src/components/dashboard/create/govsg/GovsgSingleRecipient.tsx
I think I merged this #2189 too late and the changes aren't in `master`.
Here, I rebase on top of `master` and fix any remaining issues (e.g. removing remnants of passcode button code).
> feat: remove passcode button

- backend/src/govsg/services/govsg.service.ts
- frontend/src/components/dashboard/create/govsg/GovsgRecipients.tsx
Manually revert #2153 because we want to allow duplicate recipients, and the new officer verification flow allows this.
> feat: un-dedupe

- frontend/src/components/dashboard/create/govsg/GovsgRecipients.tsx
https://open-government-products-re.sentry.io/issues/4411696399/?alert_rule_id=1124293&alert_type=issue&project=5261024&referrer=slack
> fix: prevent undefined params in govsg recipients frontend

- backend/src/core/services/credential.service.ts
- backend/src/database/migrations/20230906063204-add-partial-index-to-user-credentials.js
- backend/src/sms/middlewares/sms.middleware.ts
Reverts opengovsg/postmangovsg#2217
> Revert revert feat: add partial index to user credentials table and remove upsert to AWS secrets manager

- backend/package-lock.json
- backend/package.json
- worker/package-lock.json
There is a critical vulnerability in `@babel/traverse` (raised by snyk) that we need to fix. This PR aims to patch the issue.
The issue was flagged out by npm as well so running `npm audit fix` helped to solve it
> fix: update package vulnerabilities

- frontend/src/components/dashboard/create/email/EmailRecipients.tsx
- frontend/src/components/dashboard/create/sms/SMSRecipients.tsx
e2e tests are failing because it relied on a subtitle that was part of the phonebook UI. Added it back here.
> fix: ui bug

- .github/workflows/e2e.yml
- backend/src/core/config.ts
- e2e/config.ts
- sst/packages/functions/src/cron-jobs/redaction-digest/helper.ts
- worker/src/core/config.ts
In this PR, I change some hardcoded variables in postman that will help facilitate our DNS migration on staging
> refactor: change protected and unsubscribe url

- frontend/package-lock.json
https://github.com/advisories/GHSA-72xf-g2v4-qvf3
```
npm audit fix
```
> chore: update tough-cookie

- backend/src/email/middlewares/email-transactional.middleware.ts
Removes redundant logging left behind from previous team.
> chore: remove redundant message logs

- .github/workflows/deploy-worker.yml
https://github.com/aws-actions/amazon-ecs-deploy-task-definition/issues/705
> chore: prevent unexpected key error enableFaultInjection
